### ISSUE TITLE
Web site is not showing components

### ISSUE THREAD

**Issue by sabatinim** [facultyai/dash-bootstrap-components#1005]
Opening components docs web site I get this:

![image](https://github.com/facultyai/dash-bootstrap-components/assets/736134/e4ccadbf-aa30-4864-8174-1c3ee066feb8)

**Comment by tcbegley** [comment]
Hey @sabatinim 

I can't reproduce this. Is it possible you are trying to view the documentation on a corporate network and the firewall is preventing your browser from downloading the javascript bundles?

**Comment by sabatinim** [comment]
Unfortunately, I'm getting the issue using several browsers with my mobile internet connection.

> Hey @sabatinim
> 
> I can't reproduce this. Is it possible you are trying to view the documentation on a corporate network and the firewall is preventing your browser from downloading the javascript bundles?

**Comment by tcbegley** [comment]
Can you refresh the page with the Network tab open in the developer tools and check my hypothesis that the `dash_html_components.min.js` script is failing to load?

If that is the case, there might be some indication as to what went wrong.

**Comment by sabatinim** [comment]
> Can you refresh the page with the Network tab open in the developer tools and check my hypothesis that the `dash_html_components.min.js` script is failing to load?
> 
> If that is the case, there might be some indication as to what went wrong.
Yes sure:

![image](https://github.com/facultyai/dash-bootstrap-components/assets/736134/ed427734-d278-4ead-b8a3-6a4be9b7bab4)

![image](https://github.com/facultyai/dash-bootstrap-components/assets/736134/14cf36de-8102-4eb6-8f71-fee44803e4f2)

**Comment by tcbegley** [comment]
Looks like the unpkg CDN is having issues, not much we can do about this on our end, but hopefully it will be resolved quickly.
