### ISSUE TITLE
Graphs in tabs example not rendering

### ISSUE THREAD

**Issue by glsdown** [facultyai/dash-bootstrap-components#1017]
### What is happening?

On the documentation site, the "graphs in tabs" [example](https://dash-bootstrap-components.opensource.faculty.ai/examples/graphs-in-tabs/) isn't rendering any data.

![image](https://github.com/facultyai/dash-bootstrap-components/assets/52132406/bcf3341b-d96c-4738-9173-f575b20e1cad)

![image](https://github.com/facultyai/dash-bootstrap-components/assets/52132406/0bf5851e-11ce-4e49-8659-e2d3870329cb)

This is on Google Chrome as well as Safari on iPhone.

### What should be happening?

Data should appear on the graphs

**Comment by AnnMarieW** [comment]
Hi Gemma :wave: 

This seems to be working as intended.  If you click on the Regenerate Graph button it shows the figure.

In the callback it  specifies starting  with an empty graph.

```python
 if not n:
        # generate empty graphs when app loads
        return {k: go.Figure(data=[]) for k in ["scatter", "hist_1", "hist_2"]}

```
