### ISSUE TITLE
Support 'clearable' in Input

### ISSUE THREAD

**Issue by BellLongworth** [facultyai/dash-bootstrap-components#1018]
Like in dcc.Dropdown, a clearable=True (default false) option.

**Comment by tcbegley** [comment]
Hey @BellLongworth 

Unfortunately unlike `dcc.Dropdown` which is a fully fledged React component under the hood, the Bootstrap select is simply a styled HTML `<select>` element, and so it doesn't support adding features like this.

If you really want the clear button like `dcc.Dropdown`, I suggest you use that component instead. 

[This project](https://github.com/tcbegley/dash-bootstrap-css) is overdue an update, but it might give you some ideas on how to apply Bootstrap styles to the `dcc.Dropdown`
