### ISSUE TITLE
Bootstrap stopped working 

### ISSUE THREAD

**Issue by BaljaaSS** [facultyai/dash-bootstrap-components#1024]
- dash version: `2.7.0`
- dash-bootstrap-components version: `1.4.1`
- components affected by bug: **Layout**

### What is happening?

I am developing a small web application. It was working fine before I took some time off (1 month). When I came back and run it the bootstrap stopped working. App runs fine but without bootscrap layouts. And also when I check your website [https://dash-bootstrap-components.opensource.faculty.ai/](https://dash-bootstrap-components.opensource.faculty.ai/), bootscrap also doesn't work there.

I also checked my commits and there were no changes that could affect this.  

### Example

Please check the attached picture of your website. Mine is also same. Bootscrap doesn't work
![website](https://github.com/facultyai/dash-bootstrap-components/assets/15252654/e0a0ec60-983f-418e-92c7-627f396f3d81)

### Question

How can I fix this? What is the reason?

**Comment by tanmaychimurkar** [comment]
Same issue here

**Comment by tcbegley** [comment]
Hi, thanks for raising this.

I am not able to reproduce this:

![image](https://github.com/facultyai/dash-bootstrap-components/assets/15220906/52a42281-746d-4e6b-bcd6-344d6a68c149)

It looks to me like the CSS is not being loaded. Can you check the network tab in your browser's developer tools when you load the docs (you can filter to show only CSS). 

![image](https://github.com/facultyai/dash-bootstrap-components/assets/15220906/8d3b9105-7eb5-494d-baeb-d9398653f5d9)

The key one to look for is `bootstrap.min.css`. If you see an error code there might be some clues as to what's going on.

Can you also try loading the CSS directly by clicking [this link](https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css). Again, that might give some idea as to why it's not loading.

**Comment by tanmaychimurkar** [comment]
Hi @tcbegley, thank you for your response. I see now that the cdn I was using was wrong, and the one your provided in the link fixed it. Thank you very much, everything works for me now

**Comment by BaljaaSS** [comment]
It is fixed now. Thanks
