### ISSUE TITLE
Offcanvas component not rendering as intended

### ISSUE THREAD

**Issue by lythose** [facultyai/dash-bootstrap-components#1042]
- dash version: `#2.14.2`
- dash-bootstrap-components version: `#1.5.0`
- components affected by bug: Offcanvas

### What is happening?

The offcanvas component is very much rendering in-canvas. It does not pop up as a side-bar object to interact with, and the additional flavor attributes have no effect (except for toggling scrolling). 

### What should be happening?

Screenshot from the dbc docs page: 
![Screenshot 2024-05-19 173724](https://github.com/facultyai/dash-bootstrap-components/assets/65376203/eedb4259-4dac-48da-bf42-7f5486c703b4)

### Code

(Taken almost entirely from the dbc docs)

```python
import dash_bootstrap_components as dbc
from dash import Dash, html, dcc, Input, Output, State, callback, ctx

app = Dash(__name__)

offcanvas = html.Div(
    [
        dbc.Button("Open Offcanvas", id="open-offcanvas", n_clicks=0),
        dbc.Offcanvas(
            html.P(
                "This is the content of the Offcanvas. "
                "Close it by clicking on the close button, or "
                "the backdrop."
            ),
            id="offcanvas",
            title="Title",
            is_open=False,
        ),
    ]
)

app.layout = offcanvas

@app.callback(
    Output("offcanvas", "is_open"),
    Input("open-offcanvas", "n_clicks"),
    [State("offcanvas", "is_open")],
)
def toggle_offcanvas(n1, is_open):
    if n1:
        return not is_open
    return is_open



if __name__ == '__main__':
    app.run(debug=False)
```

### Result:
![Screenshot 2024-05-19 173413](https://github.com/facultyai/dash-bootstrap-components/assets/65376203/d1fcc1bf-789c-4560-869f-baa0000b7520)

I don't know if I'm somehow missing something obvious that the docs page is doing differently in their implementation, but this component should really not require special treatment in order to use the minimum viable product.

**Comment by AnnMarieW** [comment]
Hi @lythose 

Thanks for including the code to reproduce the issue you reported. :slightly_smiling_face: 

It's necessary to include a Bootstrap stylesheet when  you instantiate the app, for example;

```python
app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])
```


You can find more information here:

https://dash-bootstrap-components.opensource.faculty.ai/docs/quickstart/

Note  - you have lots of themes you can  choose from, see more info here:

https://dash-bootstrap-components.opensource.faculty.ai/docs/themes/

**Comment by pharouhk** [comment]
Thank you @AnnMarieW. This helped me a lot
