### ISSUE TITLE
Question - is there a way to configure custom CDN URL?

### ISSUE THREAD

**Issue by synergiator** [facultyai/dash-bootstrap-components#1043]
Is CDN URL of bootstrap hardcoded? Or is there a way to overwrite it, if there is a custom CDN, either the requirement would be to load the static content from the local server?

**Comment by tcbegley** [comment]
`dbc.themes.BOOTSTRAP` is just a string. You can pass any other string you like to `external_stylesheets` when instantiating your app, including a link to a custom stylesheet on your own CDN.

```python
app = Dash(external_stylesheets=[
    "https://my_cdn.com/bootstrap.css"
])
```

Alternatively, if your stylesheet is not hosted anywhere and you want to serve locally, just put the file in the `assets/` folder.

See Dash docs for more details: https://dash.plotly.com/external-resources

**Comment by synergiator** [comment]
thx @tcbegley

**Comment by synergiator** [comment]
thx
