### ISSUE TITLE
active_tab_style does not set background color of active tab 

### ISSUE THREAD

**Issue by ansys-satyajeet** [facultyai/dash-bootstrap-components#1048]
Please fill out the below information as much as possible.

- dash version: `2.17.1`
- dash-bootstrap-components version: `1.6.0`
- components affected by bug: `active_tab_style`

### What is happening?

The background color of active tab is not changes upon setting 
`dbc.Tab(tab1_content, label="Tab1", tab_id="tab-1", active_tab_style={"color":"#0d6efd"})`

The code line above was based on the code snippets in 
https://dash-bootstrap-components.opensource.faculty.ai/docs/components/tabs/

### What should be happening?

The background color of active tab should be changing.

### Code

```python
import dash
from dash import dcc, html
import dash_bootstrap_components as dbc

app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

tab1_content = dbc.Card(
    dbc.CardBody(
        [
            html.P("This is tab 1!", className="card-text"),
            dbc.Button("Click Here", color="success"),
        ]
    ),
    className="mt-3",
)

tab2_content = dbc.Card(
    dbc.CardBody(
        [
            html.P("This is tab 2!", className="card-text"),
            dbc.Button("Don't Click Here", color="danger"),
        ]
    ),
    className="mt-3",
)

app.layout = dbc.Container([
    dbc.Tabs([
            dbc.Tab(tab1_content, label="Tab1", tab_id="tab-1", active_tab_style={"color":"#0d6efd"}),
            dbc.Tab(tab2_content, label="Tab2", tab_id="tab-2", active_tab_style={"color":"#0d6efd"})
        ],
        id="app_tabs",
        active_tab="tab-1"
    )
])

if __name__ == "__main__":
    app.run_server(debug=True)
```

### Error messages

There is no error message. The effect of change of background color is not seen.

**Comment by tcbegley** [comment]
Hi @ansys-satyajeet 

You need to make 2 changes:
1. The style you need is `backgroundColor` rather than `color`
2. The bootstrap tab has a few different parts, you need to set the background color of the "label" rather than the tab itself. Use the `active_label_style` prop for this.

I updated the layout in your example as follows

```python
app.layout = dbc.Container(
    [
        dbc.Tabs(
            [
                dbc.Tab(
                    tab1_content,
                    label="Tab1",
                    tab_id="tab-1",
                    active_label_style={"backgroundColor": "#0d6efd"},
                ),
                dbc.Tab(
                    tab2_content,
                    label="Tab2",
                    tab_id="tab-2",
                    active_label_style={"backgroundColor": "#0d6efd"},
                ),
            ],
            id="app_tabs",
            active_tab="tab-1",
        )
    ]
)
```

And I got the desired result:

<img width="247" alt="image" src="https://github.com/user-attachments/assets/fa43a5c3-4f80-43d4-ad01-f64f27faf4c5">

**Comment by AnnMarieW** [comment]
Hey Tom - odd that you can't set the text color too.  Any idea why?

**Comment by tcbegley** [comment]
@AnnMarieW Does setting color in the label style not work? If not then I'm not sure, will have to investigate when I'm back at a computer.

**Comment by AnnMarieW** [comment]
@tcbegley It doesn't seem to - here's a link to a live example:

https://py.cafe/amward/dash-tab-navigation

**Comment by tcbegley** [comment]
That actually seems to be working, I think you chose combinations of colours that create an optical illusion. Try something like

```python
active_label_style={"color":"red", "backgroundColor": "yellow"}
```

and it seems to work for me...

<img width="470" alt="image" src="https://github.com/user-attachments/assets/41c56db9-dfec-4469-88e7-b55fd111a6da">

**Comment by AnnMarieW** [comment]
oops, my bad.  That's what I get for coding before coffee. :see_no_evil: 
I guess this can be closed now :blush:
