### ISSUE TITLE
Create toggle switch

### ISSUE THREAD

**Issue by happyshows** [facultyai/dash-bootstrap-components#136]
Hi,

Is there plan to add something like this?
https://github.com/twbs/bootstrap/issues/15783

**Comment by tcbegley** [comment]
Yes, we would like to add those. They actually only fairly recently got [added to reactstrap](https://github.com/reactstrap/reactstrap/pull/1353), the underlying ReactJS library that we use to make *dash-bootstrap-components*. This means that adding the switch will require upgrading the version of reactstrap that we use and as a result is a bigger job than just adding a new component. But it would definitely good for us to support the toggle and all the other custom inputs.

**Comment by tcbegley** [comment]
I think reactstrap 7 uses `createPortal` for rendering `Popover` and maybe some other components we currently have, which is incompatible with the version of React that `dash-renderer` uses. If I'm not mistaken about that, then updating the version of reactstrap we're using will have to wait until [Dash 1.0](https://github.com/plotly/dash/issues/469) is released, which might take a little while.

**Comment by happyshows** [comment]
ok thanks.

**Comment by tcbegley** [comment]
This is now being tracked in #142
