### ISSUE TITLE
'Random name' button in documentation not working

### ISSUE THREAD

**Issue by pbugnion** [facultyai/dash-bootstrap-components#149]
In the button section of the [input group docs](https://dash-bootstrap-components.opensource.faculty.ai/l/components/input_group), the random name button isn't working.

Happy to look into this in the coming days.

**Comment by tcbegley** [comment]
I noticed the other day that the “generate” example below is also not working but didn’t get around to raising the issue yet. If you look at that one too it would be cool if you could adapt it to use the new `callback_context` feature. It’s documented under ‘How do I determine which Input has changed?’ in the [Dash FAQs](https://dash.plot.ly/faqs).

**Comment by tcbegley** [comment]
Resolved by #154
