### ISSUE TITLE
Support dashR

### ISSUE THREAD

**Issue by tcbegley** [facultyai/dash-bootstrap-components#150]
An R interface for Dash is [in development](https://github.com/plotly/dashr), it would be cool if we supported this. A cursory look at the *dash-core-components* repo suggest it may not be too much extra work?? Perhaps those will be famous last words.

**Comment by happyshows** [comment]
If it's your interest and really quick, sure why not.

Just my 2 cents, In R space, shiny is way more powerful than dashR (which focus on viz graph primarily) and has support on plotly already. I don't see dashr is going to play well honestly...

**Comment by firasm** [comment]
For what it's worth, I found `dbc` invaluable when I taught Dash to my class of 100 students at UBC in the [Master of Data Science](https://masterdatascience.ubc.ca) program.

Students very creatively used dbc and Dash to build pretty sophisticated dashboards with various interface elements.

When we got to using Dash in R in the second half of the course, there were significant grumblings about having to use CSS and HTML to achieve the same effects as dbc. I would absolutely teach Dash in R again if dbc existed for R. I'm teaching a similar course in the spring this year (starting early March) with 40 students that would also benefit from this.

All this is to say: if dbc existed for R, there would be an immediate audience and use!

**Comment by firasm** [comment]
so... probably no chance for R support soon eh? thought I'd check where this was on the priority list before trying to find an alternative.

**Comment by tcbegley** [comment]
Hey @firasm 

Sorry for not responding before, I actually looked into it again after your first comment, but it turns out it's a little complicated. The `dash-generate-components` command line tool that comes bundled with Dash fails building R components for dash-bootstrap-components because it assumes a particular project structure that we don't conform to. 

After a bit of experimentation with a fork of Dash I think I managed to patch it, however ideally a fix would be integrated into Dash itself rather than me uploading builds for R generated with a patched fork of Dash. Unfortunately I haven't got around to submitting a PR to Dash yet, and because (afaict) a fix requires them to merge changes their end, it makes it very hard for me to estimate how soon all of this can be resolved.

Since you have a compelling use case I will bump this to the top of my priorities list, but I don't know if I'll be able to get things in place by the start of your course.

**Comment by firasm** [comment]
Oh no worries at all!

I'll likely teach this again in the fall, so it's worth getting something out, even if not for this iteration!

I'm in touch with some folks at Dash - let me see if I can ping one of them to see if they're willing to help :-)

**Comment by tcbegley** [comment]
I opened a [PR](https://github.com/plotly/dash/pull/1125) to start a discussion. Feel free to chime in there or just monitor it if you want to get involved.

**Comment by tcbegley** [comment]
This is now done! Check out the (limited) [docs](https://dash-bootstrap-components.opensource.faculty.ai/docs/dashr/) for info on how to get started. Still much to do in the way of documentation and testing, but closing this particular issue for now.

**Comment by firasm** [comment]
Awesome! Thanks :-) Will ask the students to file reports as they're discovered.
