### ISSUE TITLE
Expose 'style' for button_group

### ISSUE THREAD

**Issue by vivekvs1** [facultyai/dash-bootstrap-components#163]
Hi, 

Is it possible to expose the `style` property for `button_group`? Interestingly, when I use a callback to modify the `style `for the `button-group`, it works. But I am unable to define the `style `during definition.

Thanks,
Vivek

**Comment by tcbegley** [comment]
Hi @vivekvs1

Thanks for raising, we can definitely do that.

**Comment by tcbegley** [comment]
Resolved by #167
