### ISSUE TITLE
Tab component does not work with dash v0.40

### ISSUE THREAD

**Issue by vivekvs1** [facultyai/dash-bootstrap-components#164]
Hi,

After updating `Dash `to `v0.40`, the Tab component results in '`Error Loading Layout`'.  I have confirmed that the Tab component works well if I switch back to `v0.39`.

Thanks,
Vivek

**Comment by tcbegley** [comment]
Hi @vivekvs1 

Thanks for raising this. I have managed to reproduce the problem, and will try to understand what's changed and why things are breaking now as soon as possible. Sorry for the inconvenience.

**Comment by vivekvs1** [comment]
Thank you :)

**Comment by tcbegley** [comment]
Resolved by #166

**Comment by vivekvs1** [comment]
Thank you!!

**Comment by tcbegley** [comment]
No worries, thanks for alerting us to this in the first place!
