### ISSUE TITLE
Improve Row syntax error traceback

### ISSUE THREAD

**Issue by amarvin** [facultyai/dash-bootstrap-components#169]
If you forget the square brackets with the layout component Row, the error traceback is misleading.

For example, this is the correct syntax for a row with two columns:
```python
import dash
import dash_bootstrap_components as dbc

app = dash.Dash(__name__)
app.layout = dbc.Row([
    dbc.Col('test1'),
    dbc.Col('test2')
])

if __name__ == "__main__":
    app.run_server()
```

But if the square brackets are ommitted:
```python
import dash
import dash_bootstrap_components as dbc

app = dash.Dash(__name__)
app.layout = dbc.Row(
    dbc.Col('test1'),
    dbc.Col('test2')
)

if __name__ == "__main__":
    app.run_server()
```
This causes an error, as dbc.Row will interpret the second input as its `id`, but the error traceback isn't informative:
```
...
...\site-packages\dash\dash.py", line 1089, in _validate_layout
    component_ids = {layout_id} if layout_id else set()
TypeError: unhashable type: 'Col'
```

Is there anyway to make this more clear for users?

**Comment by tcbegley** [comment]
Hi @amarvin 

Thanks for raising this. I think that unfortunately this is kind of out of our hands. It's actually a problem that's true of Dash components generally, as they are all generated from JavaScript by the `dash` module itself (in fact you'll notice in your traceback that the error is being raised in `\site-packages\dash\dash.py`), so any change to the error messages would need to be implemented in `dash`.

I think it's a valuable point though, I've been confused by this error myself, so it would definitely be worth raising as an issue over on the [Dash repo](https://github.com/plotly/dash).

**Comment by amarvin** [comment]
Good points, thanks @tcbegley.
