### ISSUE TITLE
Add Toast component

### ISSUE THREAD

**Issue by tcbegley** [facultyai/dash-bootstrap-components#185]
Add support for Toasts:

[Bootstrap docs](https://getbootstrap.com/docs/4.3/components/toasts/)
[reactstrap docs](https://reactstrap.github.io/components/toasts/)

**Comment by vivekvs1** [comment]
Hi! It would be awesome to have support for Toasts. Is it something planned for the future?
I use the dash-bootstrap-components for every project of mine now. The web-pages turn out refined looking and feel fantastic, with minimal efforts! So than you very much!

**Comment by tcbegley** [comment]
Hey @vivekvs1 

Glad you're enjoying _dash-bootstrap-components_ so much 🙂 

This is definitely something we want to add, we just haven't got around to it yet. Since you showed interest in it I'll bump it up the list of priorities and see how hard it is to include.

**Comment by vivekvs1** [comment]
Thanks! You are the best!

**Comment by tcbegley** [comment]
@vivekvs1 I just opened #234 to add toasts and have made a [prerelease](https://pypi.org/project/dash-bootstrap-components/0.7.0rc1/) that includes them, you can install with

```
pip install dash-bootstrap-components==0.7.0rc1
```

If you have a chance to test it out and let me know what you think that would be much appreciated!

**Comment by tcbegley** [comment]
Resolved by #234, available in 0.7.0
