### ISSUE TITLE
Add auto_dismiss function in alert

### ISSUE THREAD

**Issue by happyshows** [facultyai/dash-bootstrap-components#190]
Hi,

I was looking for some features like shiny notification (https://shiny.rstudio.com/articles/notifications.html)

Which will dismiss msg after the duration is over. Is it possible to implement in this package?

**Comment by tcbegley** [comment]
Thanks for the suggestion. I'll investigate how this is implemented in RShiny and whether we could do something similar.

It may be that [toasts](https://getbootstrap.com/docs/4.3/components/toasts/#basic) which we haven't added yet would be the best components on which to build something like this.

**Comment by tcbegley** [comment]
Hey, I'm afraid not, I haven't had time to look at this. I'll try to prioritise it, but would also welcome contributions from anyone that wants to take a pass at it.

**Comment by tcbegley** [comment]
This is available for both `Alert` and `Toast` in version 0.7.1 of _dash-bootstrap-components_. They each have a new `duration` prop through which you can supply a duration in milliseconds after which the `Alert` / `Toast` will dismiss. Check out the examples in the docs for `Alert` and `Toast`. 

Sorry it took a while for me to get around to it.
