### ISSUE TITLE
Use react-bootstrap?

### ISSUE THREAD

**Issue by vnijs** [facultyai/dash-bootstrap-components#192]
FYI: React Bootstrap, The most popular front-end framework Rebuilt for React.

https://github.com/react-bootstrap/react-bootstrap

**Comment by tcbegley** [comment]
Thanks @vnijs. We are aware of this. The reason we chose reactstrap was that when we started the project react-bootstrap only supported Bootstrap v3.

I think at this point we're pretty invested in reactstrap, so I don't think we'd switch out the underlying library unless there is a compelling reason to do so. Are there any good reasons to make the switch you have in mind?

**Comment by vnijs** [comment]
Just an FYI ...
