### ISSUE TITLE
Support stretch

### ISSUE THREAD

**Issue by romainmartinez** [facultyai/dash-bootstrap-components#203]
Hey @tcbegley and thank you for this awesome package! 

I have the following container:

```python
dbc.Container(
    [
        dbc.Row(
            [
                dbc.Col(..., md=2),
                dbc.Col([..., ...], md=4),
                dbc.Col(...),
            ],
            align="stretch",
        )
    ],
    fluid=True,
)
```
And I am looking to make every `Col` element the same height as the maximal height. I am quite new to bootstrap and web dev, but it seems that's the purpose of the `align-items` option set to `stretch`. However, `dbc.Row` supports only `'start', 'center', 'end'`.

![align-items svg](https://user-images.githubusercontent.com/17710617/57571316-68cf6d80-73da-11e9-9411-8929cb8a6a0f.png)

Do you plan to support this option? Or Is there another way to dynamically adapt the height of items (without hardcoding a pixel value)?

**Comment by tcbegley** [comment]
Hey @romainmartinez, thanks for raising this.

I actually hadn't noticed Bootstrap supports this because it's not in [the documentation](https://getbootstrap.com/docs/4.3/layout/grid/#vertical-alignment) (at least, as far as I can tell?). I've just submitted PR #204 to add support for this, and made a prerelease for testing the changes. I've tested it out at my end, would you mind testing it out too and seeing if it resolves your issue?

```
pip install dash-bootstrap-components==0.6.1rc1
```

If it all looks good I'll make a full release, and document it when I get around to an already planned refresh of the layout documentation.

**Comment by romainmartinez** [comment]
Thanks for the quick update.

I tested you pre-release, and it seems to work fine as the `dbc.Col` elements from my previous snippet have the same height. However, the element _inside_ the `dbc.Col` did not scale up. In my case, I have a bunch of `dbc.Card`: 

```Python
dbc.Container(
    [
        dbc.Row(
            [
                dbc.Col(dbc.Card(...), md=2),
                dbc.Col([dbc.Card(...), dbc.Card(...)], md=4),
                dbc.Col(dbc.Card(...)),
            ],
            align="stretch",
        )
    ],
    fluid=True,
)
```
And I would like those cards to be the same height (as in the `stretch` image from my previous post). Do you have any idea on how to make this work? Again, I may have missed something as I'm a beginner in web design.

**Comment by tcbegley** [comment]
I think you'll have to set height to 100% on the Card. You can use the Bootstrap utility class `h-100` to do this, see [here](https://getbootstrap.com/docs/4.3/utilities/sizing/#relative-to-the-parent) for more details. 

Or if you prefer, set it with `style` or some custom CSS of your own.  For example if every time you set `align="stretch"` on a `Row` you want all the cards to be full height you could put something like this in a local stylesheet to avoid having to always add `h-100` to the cards:

```css
.align-items-stretch .card {
  height: 100%;
}
```

**Comment by romainmartinez** [comment]
Oh makes sense! Thanks. 

I'll let you close the issue. How can I be notified when the new documentation is updated?

**Comment by tcbegley** [comment]
Keep a lookout for a pull request called something like “layout documentation”. I’ll try to remember to tag you also.
