### ISSUE TITLE
Input Max and Min keywords not working

### ISSUE THREAD

**Issue by ZeCarlosCoutinho** [facultyai/dash-bootstrap-components#207]
Even if in the docs it says that the Input component has _max_ and _min_ keywords, I still get a TypeError.

![image](https://user-images.githubusercontent.com/15149259/57856880-3664ac80-77ee-11e9-89b4-5b4ec5795be2.png)

The code is:
```python
import dash_bootstrap_components as dbc
dbc.Input(
    id='distinct-distributions-min-support-input',
    type='number',
    placeholder="Supp",
    min=0.0,
    #max=1.0
)
```

**Comment by tcbegley** [comment]
Hey @ZeCarlosCoutinho 

Thanks for reporting, I ran your code snippet successfully. Could you check which version of *dash-bootstrap-components* you are using?

```
python -c "from dash_bootstrap_components import __version__; print(__version__)"
```

**Comment by ZeCarlosCoutinho** [comment]
Oh, sorry. Should have checked the version before.
I'm using version 0.3.6, that's why.
