### ISSUE TITLE
Support request: HowTo Form submit

### ISSUE THREAD

**Issue by jfrank87** [facultyai/dash-bootstrap-components#210]
Dear community,

I'm not sure if this is the right place to ask for support, if not, my apologies. 
I'm quite new at designing apps (with Dash), so my question may be a straightforward one.. 

I created a form using components from the Dash bootstrap components library. I want to retrieve the data from the filled out form (form submit). I'm not sure how to achieve this. I could not find an example in the documentation here https://dash-bootstrap-components.opensource.faculty.ai/l/components

I found a working example using Dash core components here: https://community.plot.ly/t/form-submission-and-routing-to-new-page/13590
However, this does not seem to work for me when I use the Bootstrap components in stead of the Dash core components.

Any ideas? Help is much appreciated.
Best,
Jeroen

**Comment by tcbegley** [comment]
Hi @jfrank87 

I tried the *dash-core-components* example you linked to, replacing *dash-core-components* with *dash-bootstrap-components* and it seemed to work. Could you post a code snippet that demonstrates the problem you're having, and explain how the behaviour differs from what you expect?

**Comment by jfrank87** [comment]
@tcbegley Thanks for the fast response! I',m sorry, I messed up, everything is working fine. I only provided id attribute and forgot the name attribute for every component. I need more sleep. Apologies, this issue can be closed/removed.

**Comment by tcbegley** [comment]
No worries, glad it's working 🙂
