### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by LePuppy** [facultyai/dash-bootstrap-components#223]
Hi,
I've just heard about dash boostrap components and tried to install it on my virtual environment using pip:
`pip install dash-boostrap-components`

returning the following error:

ERROR: Could not find a version that satisfies the requirement dash-boostrap-components (from versions: none)
ERROR: No matching distribution found for dash-boostrap-components

**Comment by tcbegley** [comment]
Hi @LePuppy 

You are missing a "t" in boo*t*strap

```
pip install dash-bootstrap-components
```

should work 🙂

**Comment by LePuppy** [comment]
I'm sorry I actually managed to mistype it in the issue ! Because I did tried with the correct syntax as well (just checked it a minute ago):

**ERROR: Could not find a version that satisfies the requirement dash-bootstrap-components (from versions: none)
ERROR: No matching distribution found for dash-bootstrap-components**

Could it be connected to the fact it's a virtual environment and I'm under a company's proxy ? Still, it worked out for other libraries.

**Comment by tcbegley** [comment]
Hmm, the virtual environment probably shouldn't be causing a problem. What are you using to create the virtual environment?

Your company's proxy seems like a more likely explanation, though if you can install other packages from PyPI using pip I don't really see why you wouldn't be able to install dash-bootstrap-components. Do other packages work? E.g. do you get the same error when running `pip install dash`?

If pip isn't working but you have conda installed you could try installing with that

```
conda install -c conda-forge dash-bootstrap-components
```

**Comment by LePuppy** [comment]
I created the virtual environment using conda.

`conda install`  worked, Thank you !

**Comment by niksdeliya** [comment]
Hi,
I'm unable to install dash-bootstrap-components using pip. I don't want to use conda. Is there any other way I can achieve this?
