### ISSUE TITLE
Format for ints like float_format

### ISSUE THREAD

**Issue by renxida** [facultyai/dash-bootstrap-components#224]
I like my large integrs in the format
123,456,789

Currently, I don't see a way to do so in the documentation.

Is there a way I could accomplish? If not, would it be a worthwhile thing to implement?

**Comment by renxida** [comment]
And sometimes I want my ints in the format
1,2345,6789

Would it be hard to do that too?

**Comment by tcbegley** [comment]
Hey @renxida 

Do you mean for a particular component? How would you like to use this?

You can use Python string formatting to add commas to an integer. For example, using [Python's format specification mini-language](https://docs.python.org/3.7/library/string.html#formatspec) with an f-string.

```python
n = 1234567890
print(f"Adding commas: {n:,d}")
```
```
Adding commas: 1,234,567,890
```

You should be able to use this to build the content you want for your components. I don't think this is the sort of thing that needs its own component?

**Comment by tcbegley** [comment]
Closing due to no response, and because this doesn’t seem like an issue with dash-bootstrap-components. Feel free to reopen if you have further questions.
