### ISSUE TITLE
 toggleClassName and toggle_style no longer working in DropdownMenu

### ISSUE THREAD

**Issue by kbrostrom** [facultyai/dash-bootstrap-components#231]
I'm trying to create a dropdown menu from my navbar in my dash app with a custom style for my Dropdown toggle. It no longer accepts toggleClassName or toggle_style as options to change the format.

**Comment by tcbegley** [comment]
Hi @kbrostrom 

Can you verify you're using version 0.6.3 of _dash-bootstrap-components_?

```
python -c "from dash_bootstrap_components import __version__; print(__version__)"
```

If you are and you're still having issues could you post a code snippet that reproduces the error?

**Comment by tcbegley** [comment]
Closing due to no response. Feel free to reopen if you are still having issues.
