### ISSUE TITLE
The collapse component doesn't work, automatic unfold itself

### ISSUE THREAD

**Issue by bo-sfl** [facultyai/dash-bootstrap-components#233]
I had this problem when reproducing the `Simple example` for `collapse` in the doc, the collapse component will hide but immediate show up again.  The `Multiple targets` and `Accordion` were fine.
I have `dash-bootstrap-components 0.6.3` and `dash 1.0.0`.
A example: 
```
import dash
import dash_bootstrap_components as dbc
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])
collapse = html.Div(
    [
        dbc.Button(
            "Open collapse",
            id="collapse-button",
            className="mb-3",
            color="primary",
        ),
        dbc.Collapse(
            html.P("never hide component"),
            id="collapse",
        ),
    ]
)
app.layout = collapse

@app.callback(
    Output("collapse", "is_open"),
    [Input("collapse-button", "n_clicks")],
    [State("collapse", "is_open")],
)
def toggle_collapse(n, is_open):
    if n:
        return not is_open
    return is_open

if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by tcbegley** [comment]
Hey @bo-sfl,

Thanks for reporting. I just tried running your code snippet with Dash 1.0.0 and dash-bootstrap-components 0.6.3 and it seemed to work ok for me, see below gif.

![dbc](https://user-images.githubusercontent.com/15220906/61009833-f80de880-a36b-11e9-949f-c1ae206ef070.gif)

Are you seeing different behaviour to this?

**Comment by bo-sfl** [comment]
This is behavior on my side.  @tcbegley
![captured](https://user-images.githubusercontent.com/49077071/61013031-07cb0400-a34f-11e9-8e8f-cd6e0bf94763.gif)

**Comment by tcbegley** [comment]
Hmm, that's strange... Which browser / OS are you using?

Does the interactive example the documentation app work for you? https://dash-bootstrap-components.opensource.faculty.ai/l/components/collapse

Does anything get output to the terminal / browser logs?

From your gif it looks like the transition works ok, but the collapse content isn't hidden correctly. During the transition the `collapsing` class should be applied, and while the collapse is open the `show` class should be applied. Can you check the inspector to see if that's happening? Should look something like this:

![dbc2](https://user-images.githubusercontent.com/15220906/61024197-c49b8000-a3a4-11e9-8303-374671a9a3c8.gif)

Can you also check that nothing is interfering with this being applied:

![image](https://user-images.githubusercontent.com/15220906/61024276-09bfb200-a3a5-11e9-87a6-60b5ac517ff3.png)

**Comment by bo-sfl** [comment]
Hi @tcbegley.

I'm using Chrome on Windows. The Collapse worked as expected with the inspector open. I also built a fresh env and that also works. So far I wasn't able to find the root cause to this.

**Comment by tcbegley** [comment]
Hmm, that's really strange. I'm glad you managed to get things working. I'll close this for now, but if it breaks again in the future feel free to reopen.

**Comment by corbinhudson** [comment]
had a similar issues with chrome windows, works no problem with firefox
