### ISSUE TITLE
badge accept but does not apply style

### ISSUE THREAD

**Issue by happyshows** [facultyai/dash-bootstrap-components#245]
Please check...

**Comment by tcbegley** [comment]
I'm not quite sure what you mean?

**Comment by happyshows** [comment]
I can put whatever style into the dbc.Badge() but when rendering, these style get ignored...

**Comment by tcbegley** [comment]
Ah ok, understood.

I tried the following example and things worked as expected:

```python
import dash
import dash_bootstrap_components as dbc

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Badge(
    "This is a badge", color="primary", style={"background-color": "red"}
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

![image](https://user-images.githubusercontent.com/15220906/63495550-0b0def80-c4b8-11e9-9819-3c1295f92cc2.png)

Could you share an example demonstrating the issue you you're having?

**Comment by happyshows** [comment]
I'll dig up my code later and get back to you on this, was really frustrated on why it's not working :(

**Comment by tcbegley** [comment]
Any update on this @happyshows? I'm going to close this for now, but feel free to reopen if you find the example you were having trouble with and can reproduce it.
