### ISSUE TITLE
callbacks don't work with DBC checklist component bc of misnamed parameter

### ISSUE THREAD

**Issue by ritviknv** [facultyai/dash-bootstrap-components#246]
I could be wrong, but it appears that the `value` parameter in the DCC checklist component is specified as `values` (plural) in DBC. This inhibits one from using callbacks. The documentation [here](https://dash-bootstrap-components.opensource.faculty.ai/l/components/input) seems incorrect. Examples: 
```python
dcc.Checklist(
                    options=[{'label':"Option 1",'value':'1'},
                            {'label':"Option 2", 'value': '2'}],
                    value=['1', '2'],
                    id = 'my-checklist')
```

```python
dbc.Checklist(
                    options=[{'label':"Option 1",'value':'1'},
                            {'label':"Option 2", 'value': '2'}],
                    value=['1', '2'],
                    id = 'my-checklist')
```
The latter will generate the following error (prompting you to use `values` instead: 
```bash
Unexpected keyword argument `value`
Allowed arguments: className, id, inline, inputClassName, inputStyle, key, labelClassName, labelStyle, loading_state, options, style, values
```

**Comment by tcbegley** [comment]
Hi @ritviknv 

Could you check which version of _dash-bootstrap-components_ you have installed? 

```
python -c "from dash_bootstrap_components import __version__; print(__version__)"
```

We changed `values` to `value` in version 0.7.0 since _dash-core-components_ made the same change in version `1.0.0`. You might just have an older version of _dash-bootstrap-components_?

**Comment by ritviknv** [comment]
Ah good catch, I was on 0.6.3. Thanks!

**Comment by tcbegley** [comment]
No worries
