### ISSUE TITLE
Responsive sidebar with toggle button

### ISSUE THREAD

**Issue by vab2048** [facultyai/dash-bootstrap-components#256]
The current example of responsive-sidebar creates a sidebar which becomes a navbar (with a toggle button) once it reaches a smaller size.

Is it possible to create a sidebar which behaves like this (responsive enough to become a navbar for a small screen) but also provides a toggle button for larger screens?

I am referring to something along the lines of number 2 here: https://bootstrapious.com/p/bootstrap-sidebar (see this page for demo: https://bootstrapious.com/tutorial/sidebar/index2.html)

**Comment by tcbegley** [comment]
Hey @vab2048,

Thanks for raising this. It certainly should be possible, I’ll try to add an example at some point.

Just to clarify, you’re happy for it to be a navbar on small screens. Just that on large screens the sidebar should also be toggleable?

**Comment by tcbegley** [comment]
Sorry, didn’t mean to close

**Comment by vab2048** [comment]
> Just to clarify, you’re happy for it to be a navbar on small screens. Just that on large screens the sidebar should also be toggleable?

Yes, that would be wonderful. Thank you very much.

**Comment by tcbegley** [comment]
Hey @vab2048,

I came up with a first version of this and submitted it as part of #257. If you have a chance, could you check it out and let me know what you think? In particular let me know if it works ok and does what you would want it to.

**Comment by vab2048** [comment]
Wonderful! 

This is exactly what I was after.

Thank you very much for creating this!
