### ISSUE TITLE
How to set Button link for an InputGroup addon Button

### ISSUE THREAD

**Issue by TiemenSch** [facultyai/dash-bootstrap-components#258]
I was trying to set a link for a button that is used as an ``dbc.InputGroupAddon``. However, where you can usually wrap a ``dbc.Button`` with a ``html.A`` or ``dcc.Link`` to set the href, this currently breaks the button's styling as an actual addon as it is no longer a direct child of the ``dbc.InputGroupAddon``.

Any ideas on how to obtain the desired result being an Addon button with a href set?

Example components:
```python
dbc.InputGroupAddon(
    html.A(
        dbc.Button(  # No longer styled as an addon
            "Download",
            id="download-button",
            disabled=True,  # Enabled after selection of something
            className="",
        ),
        id="download-link",
        href="/actions/download",
        className="btn-secondary",
    ),
    addon_type="prepend",
),
dbc.Select(
    id="download-select",
    options=[dict(label="select something", value="", disabled=True)],
    value="",
),
```

**Comment by tcbegley** [comment]
Hey @TiemenSch 

Thanks for raising this. I think the ideal solution would be if `Button` had a `href` prop which would allow you to use it like a link or `dcc.Link`. I'll look into adding that in the next release.

In the meantime, you could do what you appear to have maybe already tried, which is just apply the relevant Bootstrap classes to the `html.A` or `dcc.Link` element. Something like:

```python
dbc.InputGroup(
    [
        dbc.InputGroupAddon(
            html.A(
                "Download",
                id="download-button",
                href="/actions/download",
                className="btn btn-secondary disabled",
            ),
            addon_type="prepend",
        ),
        dbc.Select(
            id="download-select",
            options=[
                dict(label="select something", value="", disabled=True)
            ],
            value="",
        ),
    ]
)
```

That's probably going to be annoying though if you want to use a callback to disable the button. Alternatively I think the only styling you're missing is the border radius? Defined [here](https://github.com/twbs/bootstrap/blob/v4.3.1/dist/css/bootstrap.css#L3581-L3589). You can see why it's not getting applied, because it expects to be an immediate child of the `InputGroupAddon`. You could just manually set the border radius to 0 as a work around for now. For example with the `style` argument of the `Button` you could do

```python
dbc.InputGroup(
    [
        dbc.InputGroupAddon(
            html.A(
                dbc.Button(  # No longer styled as an addon
                    "Download",
                    id="download-button",
                    disabled=True,  # Enabled after selection of something
                    className="",
                    style={
                        "borderTopRightRadius": 0,
                        "borderBottomRightRadius": 0,
                    },
                ),
                id="download-link",
                href="/actions/download",
            ),
            addon_type="prepend",
        ),
        dbc.Select(
            id="download-select",
            options=[
                dict(label="select something", value="", disabled=True)
            ],
            value="",
        ),
    ]
)
```

Or more generally you could write some custom CSS that doesn't require the button to be a direct child of the `InputGroupAddon` like

```css
.input-group > .input-group-prepend .btn {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
```

**Comment by TiemenSch** [comment]
I guess the suggestion of a href property for the Button class depends on what philosophy you want to follow with this package. I think it would make for a great convenience, but at the same time you will introduce deviations with respect to the regular HTML components' implementations. I have the feeling that these conveniences are slightly more common in this package than the relatively "vanilla" dash_html_components and dash_core_components. 

W.r.t. to applying the styling manually, I will probably follow the ``dbc.Button`` style override as a workaround, thank you for that! I'm loving using these components as my experience with HTML/CSS is limited and this just offloads that so well :). On a side note, this would work as long as other themes also just need this override and nothing else (don't know if those exist, but still).

**Comment by tcbegley** [comment]
> I guess the suggestion of a href property for the Button class depends on what philosophy you want to follow with this package.

Yeah, interesting point. I think I'm all for being consistent with _dash-html-components_ and _dash-core-components_ where there is shared functionality, but not restricting ourselves to only implementing the same functionality. In general when deciding what or what not to add it's probably more important to be consistent with Bootstrap itself. In this case it is quite natural to have [links styled as buttons](https://getbootstrap.com/docs/4.3/components/buttons/#button-tags).

> By the way, just to document this: this issue also occurs with other group-like constructs like ButtonGroup.

Noted, thanks. I guess that should also be fixed if `Button` gains a `href` prop but I will be sure to test it out.

> I'm loving using these components as my experience with HTML/CSS is limited and this just offloads that so well :)

Really glad to hear that! One of the main reasons we initially created this package was precisely for that reason, we had colleagues with little HTML / CSS experience getting really bogged down trying to align / arrange things or make stuff look nice. Bootstrap is really great for just making sensible decisions for you.

**Comment by TiemenSch** [comment]
I hear the alignment issue loud and clear! I still have http://howtocenterincss.com/ lurking on my bookmarks bar 🤡. Please let me know if I can help out in any way going forward! Happy to take things for a testdrive.

**Comment by tcbegley** [comment]
@TiemenSch, I added `href` and `external_link` props to `Button`. So you can now use it like

```python
app.layout = dbc.Container(
    [
        dbc.Button("Internal link", href="/test"),
        dbc.Button("External relative link", href="/test", external_link=True),
        dbc.Button("External link", href="https://google.com"),
        dbc.Button("Button"),
    ]
)
```

you can try it out with 

```
pip install dash-bootstrap-components==0.7.2rc2
```

I've tested it with `InputGroup` and `ButtonGroup` and all seems well, but if you could try it out and let me know how you get on that would be very helpful!

**Comment by TiemenSch** [comment]
Hi, I just gave it a spin! Styling works perfectly as far as I can tell.

Could it be that the "type" of link is not automatically picked up? 

My old nested anchor button allowed me to href a route such as ``"/actions/save?kind=graph"``, which leads to a file being downloaded. 

The Button's href however only puts the link in the address bar and nothing is downloaded. Pressing F5 afterwards does!

**Comment by tcbegley** [comment]
Glad it's working for you!

> Is this intended behaviour or could the logic behind NavLinks be reused?

We have an [internal `Link` component](https://github.com/facultyai/dash-bootstrap-components/blob/master/src/private/Link.js) modelled on `dcc.Link`  that tries to guess if you wanted a `dcc.Link` or a `html.A` style link based on the `href` (essentially just checks if it's relative or absolute URL). It allows you to override the guessed behaviour with the `external_link` boolean. That component is used by `NavLink`, `DropdownMenuItem` and now `Button` as well. Is that what you meant by reusing the logic? Or did you mean something else about users of _dash-bootstrap-components_ reusing logic?

**Comment by TiemenSch** [comment]
I think I made a mistake in thinking my "save" link was something internal, as it needed an html Anchor to work previously. It's a route to serve a file instead of going to an actual page, which I guess needs the external flag manually set in the keyword arguments in any case.

In conclusion:
Great work :)

**Comment by tcbegley** [comment]
Haha, thanks!

This will make it into the next release in the coming days. I'll close this issue for now. Feel free to reopen if you have any more troubles.
