### ISSUE TITLE
Provide a CDN for dash_bootstrap_components.min.js

### ISSUE THREAD

**Issue by Dref360** [facultyai/dash-bootstrap-components#263]
Hi,
I really love your library!
Would it be possible to host 
`dash_bootstrap_components/_components/dash_bootstrap_components.min.js` on a CDN somewhere?

Thank you!
Dref360

**Comment by tcbegley** [comment]
Hey @Dref360,

> I really love your library!

Glad to hear it!

Thanks for raising this. We're planning on setting up a CDN for serving our own compiled versions of Bootstrap and Bootswatch that add support for some other Dash components, so happy to look into how we could also host the javascript bundle at the same time.

**Comment by tcbegley** [comment]
Hi, sorry this took so long, but as of version 0.10.6 the javascript bundle will be available at

`https://unpkg.com/dash-bootstrap-components@<version-number>/dist/dash_bootstrap_components.min.js`

and will be used automatically if you set `serve_locally=False` in `dash.Dash`.
