### ISSUE TITLE
using dbc bootstrap does not allow print layout in chrome

### ISSUE THREAD

**Issue by jezlax** [facultyai/dash-bootstrap-components#269]
loving dbc so far, it's been a life-saver. i'm not 100% that this is on the dbc side, but i thought i would raise it and see if anyone else has encountered it. 

When I go to print my web app (ctrl+p in chrome). I do not have the "layout" option available to me. this is true whether or not i am printing to pdf, to a printer etc. 

![image](https://user-images.githubusercontent.com/10966945/67415436-46916c80-f582-11e9-9902-2b42bd57dbda.png)

some googling lead me to this: https://stackoverflow.com/questions/49018636/bootstrap-4-css-causing-chromes-print-layout-to-disappear and I'm not sure if it is related or not, but i tried updating my CSS as shown below, to no avail. 

`.modebar{
      display: none !important;
}

@media print
{
    .no-print, .no-print *
    {
        display: none !important;
    }
}
Collapse

@page{
  size: auto;
}`

any insights here would be great, or if i need to be pointed in another direction outside of the dbc ecosystem, that's super helpful as well. thanks!

**Comment by tcbegley** [comment]
Hey @jezlax,

Thanks for reporting this, what a strange bug! This appears to be a known problem with Bootstrap, in addition to the StackOverflow post you linked, if found [this issue](https://github.com/twbs/bootstrap/issues/25629) on the Bootstrap repo.

I was able to get the layout option to reappear using the fix they recommended. It looks like something you tried already, but can you try this minimal example?

```
.
├── app.py
└── assets
    └── style.css
```

```python
# app.py
import dash
import dash_bootstrap_components as dbc

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container("Hello, Dash!")

if __name__ == "__main__":
    app.run_server(debug=True)
```

```css
/* style.css */
@page {
  size: auto;
}
```

Note you may want to do a hard refresh of the app in case CSS has been cached and is affecting things. In Chrome you can do this with `Ctrl+F5` on windows or `cmd+shift+r` on macOS.

Let me know how you get on.

**Comment by jezlax** [comment]
thanks @tcbegley - i had tried to implement the size:auto CSS earlier to no avail, i actually ended up having a bad path to the the custom CSS file in my app=dash.Dash() ... i'm up and running now with the layout function. I'll close this bug. hopefully this helps folks in the future as well, thanks.
