### ISSUE TITLE
how to make multiple InputGroup show in the same line

### ISSUE THREAD

**Issue by ieipi** [facultyai/dash-bootstrap-components#278]
Hi, I have multiple itemGroup, and by default they showed one per line.
how can i make the show inline in 1 line? and how to customize the length of Input?

**Comment by tcbegley** [comment]
Hi @ieipi 

You can add `className="list-group-horizontal"` to the `ListGroup`, and then set the width of items using inline styles or CSS.

For example

```python
import dash
import dash_bootstrap_components as dbc

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.ListGroup(
    [
        dbc.ListGroupItem("Item 1"),
        dbc.ListGroupItem("Item 2", style={"width": "200px"}),
        dbc.ListGroupItem("Item 3"),
    ],
    className="list-group-horizontal",
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

Hope that helps.

**Comment by tcbegley** [comment]
Closing this, feel free to reopen if you’re still having problems
