### ISSUE TITLE
Missing navigation on homepage

### ISSUE THREAD

**Issue by firasm** [facultyai/dash-bootstrap-components#279]
Hey there,

Thanks for the awesome package. Just thought I'd point out there is no navigation links on the homepage...checked on Safari and Chrome on macOS. See screenshots below:

homepage:

<img width="1552" alt="Screen Shot 2019-11-16 at 8 45 16 PM" src="https://user-images.githubusercontent.com/2507459/69003175-83672f80-08b2-11ea-8ea8-1050adb24dd2.png">

Sub-page (which I found through google):

<img width="1552" alt="Screen Shot 2019-11-16 at 8 46 00 PM" src="https://user-images.githubusercontent.com/2507459/69003179-8eba5b00-08b2-11ea-9ca6-291de58f9168.png">

**Comment by tcbegley** [comment]
Thanks @firasm, the documentation definitely needs an update. Until recently the focus was mostly on adding content. Now that all the components are documented the plan is to go back and restructure it a bit. Unfortunately I have limited time to do it right now so it won't happen immediately, but when it does I'll make sure navigation is more consistent.

**Comment by tcbegley** [comment]
Resolved by #332
