### ISSUE TITLE
Bootstrap sidenav

### ISSUE THREAD

**Issue by dre2004** [facultyai/dash-bootstrap-components#281]
Hello,

Is it possible to use the bootstrap sidenav?

I can't find anything relating to a sidenav on the documentation or in the issues, I was hoping to use something like the sidenav push here https://www.w3schools.com/howto/howto_js_sidenav.asp.

Cheers!

**Comment by tcbegley** [comment]
Hey  @dre2004 

There's [this example](https://github.com/facultyai/dash-bootstrap-components/tree/master/examples/multi-page-apps/responsive-collapsible-sidebar) in the examples folder which is pretty close to what you want I think?

Bootstrap doesn't actually have a native sidenav weirdly enough, so it will always be necessary to build it somewhat manually with custom CSS etc. I'm sure the W3Schools example could be translated to Dash too.

**Comment by dre2004** [comment]
Awesome, thanks! I did actually have a play around over the weekend and did manage to get to the same solution for the nav part but I hadn't come up with a way to set the active portion which this solves!
