### ISSUE TITLE
Tooltip fails to attach to element

### ISSUE THREAD

**Issue by snsmac** [facultyai/dash-bootstrap-components#282]
Adding a a tooltip to a component sometimes fails with the following error:
"The target 'vdd' could not be identified in the dom, tip: check spelling"

This code is enough to reproduce the error:
```
drop = dcc.Dropdown(options=dicts, multi=True, value="MTL", id="vdd")

body = html.Div([drop, dbc.Tooltip("Filtern nach ICD4-Werten", target="vdd")])

LAYOUT = html.Div(children=[body])
```

This may be related to following issue: https://github.com/reactstrap/reactstrap/issues/773
Stacktrace: 

 Le@http://127.0.0.1:8050/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_7_2m1571994096.min.js:31:52545

We@http://127.0.0.1:8050/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_7_2m1571994096.min.js:31:52758

window["dash_bootstrap_components/_components"]</_c</n.updateTarget@http://127.0.0.1:8050/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_7_2m1571994096.min.js:31:181028

window["dash_bootstrap_components/_components"]</_c</n.componentDidMount@http://127.0.0.1:8050/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_7_2m1571994096.min.js:31:177675

commitLifeCycles@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:17469:22

commitAllLifeCycles@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:18871:23

callCallback@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:143:14

invokeGuardedCallbackDev@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:193:16

invokeGuardedCallback@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:250:31

commitRoot@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:19083:28

completeRoot/<@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:20553:15

unstable_runWithPriority@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react@16.v1_2_0m1573763542.8.6.js:735:12

completeRoot@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:20552:27

performWorkOnRoot@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:20481:21

performWork@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:20389:24

performSyncWork@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:20363:14

requestWork@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:20232:5

scheduleWork@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:20046:16

enqueueSetState@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react-dom@16.v1_2_0m1573763542.8.6.js:11304:17

Component.prototype.setState@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/react@16.v1_2_0m1573763542.8.6.js:423:16

handleChange@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/dash_renderer.v1_2_0m1573763549.dev.js:27180:14

dispatch@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/dash_renderer.v1_2_0m1573763549.dev.js:28180:7

createThunkMiddleware/</</<@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/dash_renderer.v1_2_0m1573763549.dev.js:27669:16

dispatch@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/dash_renderer.v1_2_0m1573763549.dev.js:27727:18

./src/actions/api.js/apiThunk/</</<@http://127.0.0.1:8050/_dash-component-suites/dash_renderer/dash_renderer.v1_2_0m1573763549.dev.js:30347:19

**Comment by tcbegley** [comment]
Hey @snsmac 

I think this is probably because recent changes to Dash mean that the dropdown is now loaded lazily, so at the moment the tooltip looks for an element with `id="vdd"` it hasn't been inserted into the DOM yet.

I'll see if that can be fixed with a change to _dash-bootstrap-components_, though it might just be the case that you'll need to target an element that isn't loaded lazily.

In this case you can achieve that by just wrapping the dropdown with a `html.Div`

```python
drop = html.Div(dcc.Dropdown(options=dicts, multi=True, value="MTL"), id="vdd")
body = html.Div([drop, dbc.Tooltip("Filtern nach ICD4-Werten", target="vdd")])
LAYOUT = html.Div(children=[body])
```

**Comment by tcbegley** [comment]
Closing this, let me know if the suggested solution isn't working for you or if you are having further problems.
