### ISSUE TITLE
How to set row height?

### ISSUE THREAD

**Issue by PGijsbers** [facultyai/dash-bootstrap-components#286]
Sorry if this is a webdev/bootstrap question and not related to the framework.
I'm using `dbc.Row` and `dbc.Col` to place four elements on my page. 
I want them fill the page roughly like this:

```
______________________
|            |       |
|            |       |
----------------------
|            |       |
----------------------
```
The top row taking roughly 65% of height and the bottom row the remainder.
The left column should take roughly 65% of width and the right column the remainder.
Each element inside the cell should then fit to the size of the cell.

Setting the width was easy through the column's width parameter. But I can't find any documentation on setting height. Looking at bootstrap documentation I can find information on setting height through class name (e.g. `class='row h-75`). But I can't get that to work. I don't see a word on height in the Layout component either. Any pointers?

**Comment by tcbegley** [comment]
Height in CSS can be a bit annoying. I think the utility classes in Bootstrap like `h-75` are a good way to go. You just need to remember that the 75 means 75% of the height of the parent. If the height of the parent isn't set then it will likely just be as big as it needs to be to contain the child and so the `h-75` class ends up not really having an effect.

Instead, you should set the height of the parent of the two rows, then it should work out. Here's an example where I have the two rows inside a `Container` where I set `height: 100vh` (`vh` is "viewport height", so `100vh` means "100% of screen height", see [here](https://www.w3schools.com/cssref/css_units.asp)). The ugly background colors and `height: 100%` on the columns is just to visually confirm the correct spacing.

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Row(
            [
                dbc.Col(
                    html.P("This is column 1"),
                    width=8,
                    style={"height": "100%", "background-color": "red"},
                ),
                dbc.Col(
                    html.P("This is column 2"),
                    width=4,
                    style={"height": "100%", "background-color": "green"},
                ),
            ],
            className="h-75",
        ),
        dbc.Row(
            [
                dbc.Col(
                    html.P("This is column 3"),
                    width=8,
                    style={"height": "100%", "background-color": "blue"},
                ),
                dbc.Col(
                    html.P("This is column 4"),
                    width=4,
                    style={"height": "100%", "background-color": "cyan"},
                ),
            ],
            className="h-25",
        ),
    ],
    style={"height": "100vh"},
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

Hope that helps.
![image](https://user-images.githubusercontent.com/15220906/69833542-60326d80-122c-11ea-8632-0c439954bb6b.png)

**Comment by tcbegley** [comment]
Closing this, but feel free to reopen if you're still having problems.

**Comment by pridi** [comment]
Probably I very stupid question but if I try to insert a plotly chart in one of these column, the height of this chart is going over...how can I have a chart inside for example the cyan rectangle?

**Comment by wuestnjo** [comment]
Changing the properties of the figure, that is to be displayed in the "Container" like so;
`
fig.update_layout( {"margin": {"l": 0, "r": 0, "b": 0, "t": 20}, "autosize": True})
`
did the job for me. Though I was struggling too, trying to set this within the dcc.Graph options.
