### ISSUE TITLE
DropdownMenuItem as link prevents DropdownMenu dismissing

### ISSUE THREAD

**Issue by tcbegley** [facultyai/dash-bootstrap-components#287]
If `DropdownMenuItem` is used as an internal link it prevents the `DropdownMenu` from being dismissed on click.

See [relevant thread](https://community.plot.ly/t/make-dropdown-menu-disappear-after-link-is-clicked/32021) on Plotly forum.

**Comment by jezlax** [comment]
I literally came here to post this today. So wanted to +1 it, I guess. I use almost all of the dropdownMenuItems as href's across my apps.

**Comment by tcbegley** [comment]
@jezlax would you mind testing out the prerelease that addresses this issue? It works at my end but it's always good to have it tested on a few different setups before releasing.

```
pip install dash-bootstrap-components==0.7.3rc1
```

Note that in addition to fixing the dismissal issue, `DropdownMenuItem` now has a property `toggle` that can be used to control whether that item does or doesn't dismiss the menu on click.

**Comment by jezlax** [comment]
Thanks Tom,

Will test today and get back to you, as time permits. Thanks for the quick
fix!

**Comment by jezlax** [comment]
hi Tom. I'm getting the following when i go to pip install the dev package... 

   raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

it very well could be something on my end. I'll keep toying with it

**Comment by tcbegley** [comment]
Hmm, that's strange... What OS / Python version are you using? Can you try in a fresh virtual environment  maybe?

**Comment by jezlax** [comment]
I'll do that. windows, python 3.7.3

**Comment by tcbegley** [comment]
Might also be worth trying

```
pip install --no-cache-dir dash-bootstrap-components==0.7.3rc1
```

**Comment by jezlax** [comment]
Boom. Works beautifully. Looks like it deprecates me to dcc 1.0.0 on that
dbc version, so I have to revert back. Not sure if that's just an issue on
my end, but the dropdowns worked as expected in the dev environment.

**Comment by tcbegley** [comment]
Great! Glad to hear it's resolved the issue for you

> Looks like it deprecates me to dcc 1.0.0 on that dbc version

That is surprising, since dcc is not a dependency of dbc, so it shouldn't require that. Can you update dcc without breaking dbc `pip install -U dash-core-components`? Keep me posted if you figure out what's going on.

**Comment by jezlax** [comment]
This is what I get when i pip install the dev package...

Installing collected packages: dash-bootstrap-components,
dash-core-components
  Found existing installation: dash-bootstrap-components 0.7.2
    Uninstalling dash-bootstrap-components-0.7.2:
      Successfully uninstalled dash-bootstrap-components-0.7.2
  Found existing installation: dash-core-components 1.6.0
    Uninstalling dash-core-components-1.6.0:
      Successfully uninstalled dash-core-components-1.6.0
Successfully installed dash-bootstrap-components-0.7.3rc1
dash-core-components-1.0.0

**Comment by jezlax** [comment]
I could be related to this issue (assuming you guys have DASH 1.0.2 as a
dependency)

ERROR: dash 1.0.2 has requirement dash-core-components==1.0.0, but you'll
have dash-core-components 1.6.0 which is incompatible.

**Comment by tcbegley** [comment]
Hmm, we just have `dash>=1.0.0` as a requirement, it shouldn't downgrade you if you have a more recent version of Dash installed... What happens if you `pip install -U dash`?

**Comment by tcbegley** [comment]
This has been resolved in version 0.8.0

**Comment by jezlax** [comment]
hi @tcbegley - me again :) ... hope your team and families are well in the UK. I might want to re-open this, or I may need to adjust my layout with the DropdownMenu ... I have nested two dropdown menus to create a sub-menu of sorts (see screenshot). It is no longer auto-dismissing the "parent" menu i.e. Bayesian Market Values, when I select "Bayesian Dashboard" for example. Is there a better way to accomplish this in DBC, or would this be considered a bug? Thanks.

![image](https://user-images.githubusercontent.com/10966945/78945020-88549780-7a7c-11ea-847b-62e87ee5bae0.png)

**Comment by tcbegley** [comment]
Hi @jezlax,

Thanks for reporting. I hadn't anticipated people using nested DropdownMenus like that, I haven't seen that sort of usage documented in the Bootstrap docs for example.

That said, we can control the dismissal somewhat, so I'll take a look at whether it's easy to fix.

In terms of a better way, I'm not sure that there is. If I had a lot of links like that to manage I would probably consider having the high level links in the Navbar, and then on each page a second set of navigation options for the lower level links. I did something roughly like that in our [docs](https://dash-bootstrap-components.opensource.faculty.ai/).
