### ISSUE TITLE
Setting options of Select via callback

### ISSUE THREAD

**Issue by chk2817** [facultyai/dash-bootstrap-components#290]
Hi There,

Struggle to set the options of a Select using a call

i have a Form / FormGroup with the following 

``dbc.Col(dbc.Select(id='columns_list',options=[{'label':'','value':'0'}]),width=2)``

First, we apparently need to init the options as done above with a dummy

use load a data file into a dash_table and then I want to list the dash_table columns into the Select options

my callback

``@app.callback([Output('columns_list','options'),],[Input('dataset_table','columns')])``

``
def get_data_columns(columns):
    options=[{'label':x['name'], 'value':x['name']} for x in columns]
    return options
``

got the following error msg, i use the version 0.7.2. What am I doing wrong here? Thanks a lot

![image](https://user-images.githubusercontent.com/23385702/70982906-22e92f00-20b8-11ea-9b46-14138652b41b.png)

**Comment by tcbegley** [comment]
Can you try changing

```python
@app.callback([Output('columns_list','options'),],[Input('dataset_table','columns')])
```

to

```python
@app.callback(Output('columns_list', 'options'), [Input('dataset_table', 'columns')])
```

I think because you are wrapping the `Output` in a list, Dash is treating it like a multiple output callback, and unpacking `options` when you return it, rather than passing it as a list to the `Select`.

Let me know if that fixes it.

**Comment by chk2817** [comment]
Got it, thanks a lot, little details that makes sometimes miserable :=(
just realized issue was also there with the dcc.Dropdown
many thanks and wish you a happy festive year end break

**Comment by tcbegley** [comment]
No worries, glad I could help 🙂
