### ISSUE TITLE
Form vs Input - what's the difference?

### ISSUE THREAD

**Issue by filippo82** [facultyai/dash-bootstrap-components#307]
Dear faculty.ai,

what is the difference between **Form** and **Input** components?

Thanks.

**Comment by tcbegley** [comment]
Traditionally HTML forms were used to collect values of inputs and then submit them together to the server for processing. In Dash however, you don't really submit forms in the traditional way, instead you bind callbacks to the values of your input components. As a result the `dbc.Form*` components are really just structural components that will help you control the layout of a collection of inputs.

Check [the documentation](https://dash-bootstrap-components.opensource.faculty.ai/l/components/form) for some examples of using form components to organise inputs.

**Comment by tcbegley** [comment]
Closing this for now, but feel free to reopen if you have further questions.
