### ISSUE TITLE
Latest offline installer contains bug

### ISSUE THREAD

**Issue by tonywang531** [facultyai/dash-bootstrap-components#316]
- dash-bootstrap-components version: `#0.8.3`

### What is happening?

The offline installer does not work for 0.8.3 because it is detecting the setuptools is out of date even though it is not. The previous version of 0.8.2 offline installer worked without problems.

### What should be happening?

The installer should work without problems

### Error messages

![image](https://user-images.githubusercontent.com/51065728/74811314-8ef44780-5334-11ea-8188-5f8f551a417d.png)

**Comment by tcbegley** [comment]
Hi @tonywang531,

Thanks for reporting. Could you confirm what you mean by offline installer? Are you downloading the source from PyPI then installing that?

Could you also confirm what command you ran that gave you that output?

**Comment by tonywang531** [comment]
> Hi @tonywang531,
> 
> Thanks for reporting. Could you confirm what you mean by offline installer? Are you downloading the source from PyPI then installing that?
> 
> Could you also confirm what command you ran that gave you that output?

Yes I am referring to the tar file on pypi. Some coorperate computer does not have internet access so have to be installed offline.

I used `pip -install filename `in the directory with the file

**Comment by tcbegley** [comment]
Which version of Dash do you have installed? If you're unsure you can find out with

```
python -c "from dash import __version__; print(__version__)"
```

Your error suggests you are using Anaconda, is that correct? dash-bootstrap-components 0.8.3 requires Dash 1.9.0 or later, but this is not yet available through conda. Perhaps that could be to blame? I will look into this a bit more in any case.

**Comment by tonywang531** [comment]
> Which version of Dash do you have installed? If you're unsure you can find out with
> 
> ```
> python -c "from dash import __version__; print(__version__)"
> ```
> 
> Your error suggests you are using Anaconda, is that correct? dash-bootstrap-components 0.8.3 requires Dash 1.9.0 or later, but this is not yet available through conda. Perhaps that could be to blame? I will look into this a bit more in any case.

Hello @tcbegley ,

Thank you for your message. Yes the computer which have problems is using Dash 1.8.0. This is probably why it did not work. Although it is kind the installer should fail at detecting Dash version instead of setuptools.

**Comment by tcbegley** [comment]
> I have updated Dash to 1.9.0. The same error still appears.

Strange. I tried downloading the tar file myself and installing and didn't seem to have any issues.

Is the screenshot you shared above all of the error messages you get? Is there any additional logging output?

**Comment by tonywang531** [comment]
> > I have updated Dash to 1.9.0. The same error still appears.
> 
> Strange. I tried downloading the tar file myself and installing and didn't seem to have any issues.
> 
> Is the screenshot you shared above all of the error messages you get? Is there any additional logging output?

This is the full error log. 
![image](https://user-images.githubusercontent.com/51065728/74910371-b531ea00-53fd-11ea-963e-52a51a655889.png)

The setuptool version 

![image](https://user-images.githubusercontent.com/51065728/74910533-15c12700-53fe-11ea-8f74-6d350f54191b.png)

Which is why the error is not making sense

**Comment by tcbegley** [comment]
Do you have multiple versions of Python installed? Is `pip` definitely installing for the version that has `setuptools` installed? You should be able to check with `where python` and `where pip` and checking the paths match (assuming you're on Windows, try `which python` and `which pip` if you're on Unix). 

If they are different, you could try installing with

```
python -m pip install filename
```

which would ensure `pip` is installing for the right version of Python.

**Comment by tonywang531** [comment]
> Do you have multiple versions of Python installed? Is `pip` definitely installing for the version that has `setuptools` installed? You should be able to check with `where python` and `where pip` and checking the paths match (assuming you're on Windows, try `which python` and `which pip` if you're on Unix).
> 
> If they are different, you could try installing with
> 
> ```
> python -m pip install filename
> ```
> 
> which would ensure `pip` is installing for the right version of Python.
where python
![image](https://user-images.githubusercontent.com/51065728/74916573-730ea580-5409-11ea-90bb-fc99c1ec3953.png)
where pip
![image](https://user-images.githubusercontent.com/51065728/74916597-79048680-5409-11ea-9073-f8d89472b98a.png)
I am assuming they are installed in the correct place, is this right? Also I have tried python -m pip install and it did not work either.

**Comment by tcbegley** [comment]
Hmm, yeah that looks ok to me. You're not having this problem with any other packages?

There's one more thing I can think to try which is adding the `--no-deps` flag.

```
pip install --no-deps filename
```

Since your install is failing to fetch `setuptools` (presumably due to lack of internet), this flag should tell `pip` to skip it. If `setuptools` is already installed the installation should still complete successfully.

**Comment by tonywang531** [comment]
Sorry it still does not work, I have logged the full process.
[log.txt](https://github.com/facultyai/dash-bootstrap-components/files/4233580/log.txt)
I do not know much about pip install process but it looks the default is to just go check for: 
```
1 location(s) to search for versions of setuptools:
2020-02-21T08:46:17,559     * https://pypi.org/simple/setuptools/
```

**Comment by tcbegley** [comment]
Ok, I think I managed to reproduce the problem with a bit of hacking and turning off my internet connection. 

With that setup in place I managed to resolve the issue by running the `setup.py` script manually as a Python script. To do that, untar the file downloaded from PyPI, then from inside the untarred directory run

```
python setup.py install
```

Let me know if that works.

**Comment by tonywang531** [comment]
> Ok, I think I managed to reproduce the problem with a bit of hacking and turning off my internet connection.
> 
> With that setup in place I managed to resolve the issue by running the `setup.py` script manually as a Python script. To do that, untar the file downloaded from PyPI, then from inside the untarred directory run
> 
> ```
> python setup.py install
> ```
> 
> Let me know if that works.

Thanks, it worked this time. Usually I can install the offline module with just pip install filename. Next time if similar things happen I know what to do.
