### ISSUE TITLE
Navbar and Sidebar in a single app

### ISSUE THREAD

**Issue by ktrev** [facultyai/dash-bootstrap-components#321]
Somehow I am not able to achieve this. When I add a sidebar, the top part gets hidden under the navbar

My code is as below (The sidebar code is taken from the example and used as such. Just put it in a function.)

````
navbar = dbc.NavbarSimple(
  brand="My Analytics Dashboard",
  brand_href="#",
  color="#3C8DBC",
  dark=True,
  fixed="top"
)

sidebar = Sidebar()
content = html.Div(id="page-content")

app.layout = html.Div([dcc.Location(id="url"), navbar, sidebar, content])
app.config['suppress_callback_exceptions'] = True
````

**Comment by dmintercept** [comment]
either margin or padding should do the trick.  I was facing a similar issue with a sidebar and some content I was displaying on the page

**Comment by tcbegley** [comment]
Yes, as @dmintercept said if you want the navbar running along the top, and the sidebar below you just need to increase the padding at the top of the sidebar. Assuming you're following [the simple sidebar example](https://github.com/facultyai/dash-bootstrap-components/blob/master/examples/multi-page-apps/simple_sidebar.py) you should just be able to modify the `SIDEBAR_STYLE` dictionary like this:

```python
SIDEBAR_STYLE = {
    ...,
    "padding": "4rem 1rem 2rem",
    ...,
}
```

**Comment by ktrev** [comment]
Thanks.
"padding": "4rem 1rem 2rem", worked.
Closing the issue.
