### ISSUE TITLE
Getting 'dash\component\dash_bootstrap_components\_components\dash_bootstrap_components.min.js' could not be found

### ISSUE THREAD

**Issue by baluinfo86** [facultyai/dash-bootstrap-components#326]
When i use dash bootstrap component in my django template , getting below error

'dash\component\dash_bootstrap_components\_components\dash_bootstrap_components.min.js' could not be found

**Comment by tcbegley** [comment]
Hi @baluinfo86 

Could you give some more detail? Are you using [django-plotly-dash](https://github.com/GibbsConsulting/django-plotly-dash/)?

**Comment by baluinfo86** [comment]
yes am using django-plotly-dash

Setting.py file has below config

INSTALLED_APPS = [
    .....
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'channels',
    'channels_redis',
]

MIDDLEWARE = [
    'django_plotly_dash.middleware.BaseMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

**Comment by tcbegley** [comment]
As far as I can tell this is either an issue with Django-Plotly-Dash or with your Django configuration rather than an issue with dash-bootstrap-components. You should raise an issue on the Django-Plotly-Dash repo instead.
