### ISSUE TITLE
dash_table overflowX partially crops the first and last column

### ISSUE THREAD

**Issue by KyleKing** [facultyai/dash-bootstrap-components#334]
### Overview

The negative margins in the Bootstrap flex-box row appear to crop the first and last column of dash_table when `overflow-x` is set to `scroll` (I think the negative margin may cropany element when `overflow-x` is set). I'm not all that familiar with flex box and I'm not sure what an easy solution would be.

How should responsive (x-scroll-able) tables be created when using bootstrap/`dbc`?

I've looked around and couldn't find a solution on StackOverflow/Github. It appears that overflow-x should work with Bootstrap ([started a Fiddle](https://jsfiddle.net/KyleKing/x38jgprz)), but something from `dbc`/Dash is contributing to this issue

## Versions

- dash version: `1.9.1`
- dash-bootstrap-components version: `0.9.1` (`Bootstrap 4.4.1`)
- components affected by bug: `dbc.themes.*`

### What is happening?

The first and last column of dash_table.datatable are cutoff when using with bootstrap and setting `overflow-x`. The `margin-right: -15px` / `margin-left: -15px` for the `row` class appear to be the problem

Shown below are the cutoff row selectors. Should be a full circle

<img width="564" alt="Screen Shot 2020-03-15 at 10 18 28" src="https://user-images.githubusercontent.com/3784339/76703255-cb526380-66a6-11ea-89f6-bc122830aaa0.png">

### What should be happening?

Expected the full table to be visisble

<img width="746" alt="Screen Shot 2020-03-15 at 10 19 40" src="https://user-images.githubusercontent.com/3784339/76703260-d6a58f00-66a6-11ea-81d1-784da48c3071.png">

### Code

Simple example based on the quick start example for dash_table: https://dash.plot.ly/datatable

```python
import dash
import dash_bootstrap_components as dbc
import dash_table
import plotly.express as px

raw_data = px.data.gapminder()

datatable = dash_table.DataTable(
    columns=[{'name': i, 'id': i} for i in raw_data.columns],
    data=raw_data.head(5).to_dict('records'),
    row_selectable='single',
    style_table={'overflowX': 'auto'},
)

app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])
app.layout = dbc.Container([
    dbc.Row([
        dbc.Col([
            datatable,
        ]),
    ]),
])

# # The issue is seen with an even simpler example as well
# app = dash.Dash(__name__, external_stylesheets=[dbc.themes.GRID])
# app.layout = html.Div([datatable])

if __name__ == '__main__':
    app.run_server(debug=True)
```

Update: moved the overview/info to the top, linked a jsfiddle, and added two-line code example in comments

**Comment by tcbegley** [comment]
Hey @KyleKing 

Thanks for the very detailed report!

The problem here is that `dash-table` applies the `row` class to table rows, which is also defined by Bootstrap. As you say the negative margin is causing the problem.

Bootstrap is very unlikely to rename `row`, and I don't have any say over `dash-table`, but you can work around this by writing some custom CSS to kill the negative margins only inside the Dash Table itself. Something like

```css
.dash-table-container .row {
  margin: 0;
}
```

I put that snippet into a file called `style.css` in my `assets/` folder and it fixed the problem. You could make additional changes like setting `display` to something other than `flex`, but as far as I could tell that wasn't the cause of the specific issue you raised.

**Comment by KyleKing** [comment]
Thanks! That makes sense

I also found that you can use the `css` keyword: `dash_table.DataTable(css=[{'selector': '.row', 'rule': 'margin: 0'}], ...)`
