### ISSUE TITLE
bootstrap style sheet breaks the table when using fixed_column

### ISSUE THREAD

**Issue by mbkupfer** [facultyai/dash-bootstrap-components#335]
- dash version: `#1.9.0`
- dash-bootstrap-components version: `#0.9.1`
- components affected by bug: `dash_table.DataTable
### What is happening?

When freezing first column, it ends up creating what visually looks like two rows.

![image](https://user-images.githubusercontent.com/6313008/76885441-77798300-683c-11ea-9e91-17bea6a8e108.png)

### What should be happening?

When removing the dbc.themes.BOOTSTRAP external_stylesheet, it then begins to look normal:

![image](https://user-images.githubusercontent.com/6313008/76885590-b0b1f300-683c-11ea-8220-48f7ad54bda8.png)

### Code

```python
from collections import OrderedDict

import dash
import dash_core_components as dcc
import dash_html_components as html
import dash_bootstrap_components as dbc
import dash_table
import pandas as pd

app = dash.Dash(
        __name__, 
        external_stylesheets=[dbc.themes.BOOTSTRAP]
)

election_data = OrderedDict(
    [
        (
            "Date",
            [
                "July 12th, 2013 - July 25th, 2013",
                "July 12th, 2013 - August 25th, 2013",
                "July 12th, 2014 - August 25th, 2014",
            ],
        ),
        (
            "Election Polling Organization",
            ["The New York Times", "Pew Research", "The Washington Post"],
        ),
        ("Rep", [1, -20, 3.512]),
        ("Dem", [10, 20, 30]),
        ("Ind", [2, 10924, 3912]),
        (
            "Region",
            [
                "Northern New York State to the Southern Appalachian Mountains",
                "Canada",
                "Southern Vermont",
            ],
        ),
    ]
)

df_election = pd.DataFrame(election_data)

app.layout = html.Div(
    [
        dash_table.DataTable(
            data=df_election.to_dict('records'),
            columns=[{'id': c, 'name': c} for c in df_election.columns],
            fixed_columns={'headers': True, 'data': 1},
        )
    ]
)
if __name__ == '__main__':
    app.run_server(debug=True)

```

### Error messages
None

**Comment by mbkupfer** [comment]
I noticed then when I toggle the `flex-wrap` style property, it removes this issue. Any idea how to incorporate this as a patch?

![image](https://user-images.githubusercontent.com/6313008/76886524-266a8e80-683e-11ea-9342-c19bfde96cf8.png)

**Comment by tcbegley** [comment]
Hey @mbkupfer 

This is because Bootstrap and dash-table both use a CSS class called `row`. The fix you identified is the right way forward here. You can incorporate it into your app by writing some custom CSS like the following and placing it in your `assets/` folder

```css
.dash-table-container .row {
  flex-wrap: nowrap;
}
```

This will set the `flex-wrap` property back to the default `nowrap` on any element with class `row` that is part of the table.

**Comment by mbkupfer** [comment]
Thanks @tcbegley!

I figured I could overwrite, but just wanted to make sure there were no unintended consequences. Appreciate the guidance.
