### ISSUE TITLE
DBC layouts not allows dash-tables to render correctly

### ISSUE THREAD

**Issue by jezlax** [facultyai/dash-bootstrap-components#336]
Before opening:

- [Search for duplicate or closed issues](https://github.com/facultyai/dash-bootstrap-components/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/facultyai/dash-bootstrap-components/blob/master/.github/CONTRIBUTING.md)

Please fill out the below information as much as possible.

- dash version: `#1.9.0`
- dash-bootstrap-components version: `#0.8.3`
- components affected by bug: dbc.Layout, dash-tables

### What is happening?
When trying to use dbc.Row and dbc.Col to set a layout which contains a dash-table, I am getting margins which overrun the table and force a horizontal scrollbar when one should not be necessary.

### What should be happening?

In the below code, you should see a full table, without a horizaontal scrollbar, as the div is wide enough to accommodate the table.

### Code

```python
import dash
import dash_table
import pandas as pd
import dash_html_components as html
import dash_bootstrap_components as dbc
from app import app, con

df_final = pd.read_csv('http://mlr.cs.umass.edu/ml/machine-learning-databases/abalone/abalone.data')
colnames = df_final.columns
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP,'.assets/custom.css'])

t = dash_table.DataTable(
    id = 'modeling-table',
    columns=[{"name": i, "id": j} for i,j in zip(colnames,df_final.columns)],
    data=df_final.to_dict('records'),
    style_table={
        'maxHeight': '600px',
        'overflowY': 'scroll',
        },
    sort_action="native",
    sort_mode="multi"
    )

app.layout = html.Div(children=[
                 dbc.Col(
                    children=[
                        dbc.Row(children=[html.H5("My Table",style={"margin-left":"auto","margin-right":"auto"})],style={"background-color":"#002B5C","color":"white","margin-bottom":"25px"}),
                        dbc.Row(children=[t],style={"width":"100%"})
                        ], style={"width":"900px"}
                        ),

                 dbc.Col(html.H5("Other Data"), style={"width":"300px","height":"1500px","border":"1px solid green"})
                 ])


if __name__ == '__main__':
    app.run_server(debug=True)

```
![image](https://user-images.githubusercontent.com/10966945/77119210-9d995180-69fb-11ea-8477-4c759f8408d6.png)

**Comment by tcbegley** [comment]
Hi @jezlax 

There's a couple of things going on here. First is that Bootstrap defines a CSS class called `row`, and `dash-table` also uses this class, so they interfere with each other. You can add the following custom CSS to assets to fix this.

```css
.dash-table-container .row {
  display: block;
  margin: 0;
}
```

The other thing is that your use of `Row` and `Col` is the wrong way around. Bootstrap expects rows of columns rather than columns of rows. The following example is based on yours, not sure exactly what you were aiming for but hopefully it clarifies a few things:

```python
import dash
import dash_table
import pandas as pd
import dash_html_components as html
import dash_bootstrap_components as dbc

df_final = pd.read_csv(
    "http://mlr.cs.umass.edu/ml/machine-learning-databases/"
    "abalone/abalone.data"
)
colnames = df_final.columns
app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

t = dash_table.DataTable(
    id="modeling-table",
    columns=[{"name": i, "id": j} for i, j in zip(colnames, df_final.columns)],
    data=df_final.to_dict("records"),
    style_table={"maxHeight": "600px", "overflowY": "scroll"},
    sort_action="native",
    sort_mode="multi",
)

app.layout = html.Div(
    dbc.Row(
        [
            dbc.Col([html.H1("My Table"), html.Hr(), t], width=12, xl="auto"),
            dbc.Col(
                [html.H1("Other data"), html.Hr()],
                style={"border": "black 1px solid"},
            ),
        ]
    ),
    className="p-5",
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by jezlax** [comment]
Tom, thanks immensely for the pointer. Will try adding in the assets to see
if it takes. Will re-organize the Col/Row makeup as well and report back.
Will post another sample if still stuck. Hope you all are well in the UK,
stay safe. Cheers.

**Comment by jezlax** [comment]
Tom! Thanks so much. this took care of my problem, both in the "dummy" example provided and in my production application. And the "proper" instantiation of the Row/Col setup is much much cleaner as well. Rewriting a lot of my app this way, with my new found time :) 

Appreciate your help during these crazy times. Stay safe. thanks.

**Comment by tcbegley** [comment]
Glad I could help! And thanks for the well wishes, look after yourself also.
