### ISSUE TITLE
add n_clicks_timestamp to checklist & radioItems

### ISSUE THREAD

**Issue by HedgeShot** [facultyai/dash-bootstrap-components#338]
Hi,

Thanks for the package!
Would it be possible to add something like `n_clicks_timestamp ` for Checklist & radioItems?

For instance, if we have 2 checklists that affect one component it gets tricky to know which one was triggered last. 

Thanks!

**Comment by tcbegley** [comment]
Hey @HedgeShot 

Thanks for raising this. `*_timestamp` properties are technically deprecated by Dash, to quote the documentation:

> Prior to v0.38.0, you needed to compare timestamp properties like n_clicks_timestamp to find the most recent click. While existing uses of `*_timestamp` continue to work for now, this approach is deprecated, and may be removed in a future update. The one exception is `modified_timestamp` from `dcc.Store`, which is safe to use, it is NOT deprecated.

Hence it's probably not advisable to add new instances of these props if they could be removed in the future.

Happily you can achieve what you want using `dash.callback_context`. See the [Dash docs](https://dash.plot.ly/faqs) for details (under the question "How do I tell which input has changed?"), but here's a quick example to get you up and running.

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Checklist(
            id="list-1",
            options=[
                {"label": "Item 1", "value": 1},
                {"label": "Item 2", "value": 2},
            ],
        ),
        dbc.Checklist(
            id="list-2",
            options=[
                {"label": "Option 1", "value": 1},
                {"label": "Option 2", "value": 2},
            ],
        ),
        html.Div(id="output"),
    ],
    className="p-5",
)


@app.callback(
    Output("output", "children"),
    [Input("list-1", "value"), Input("list-2", "value")],
)
def get_list_value(value1, value2):
    ctx = dash.callback_context

    if (value1 is None and value2 is None) or not ctx.triggered:
        return "No change yet..."

    list_id = ctx.triggered[0]['prop_id'].split('.')[0]
    value = value1 if list_id == "list-1" else value2

    return f"Callback triggered by {list_id} with value {value}"


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by HedgeShot** [comment]
Thanks a lot, I didn't know about depreciation of those values. Your solution is what I need to avoid using dcc.Store.
