### ISSUE TITLE
Broken links in themes documentation

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [facultyai/dash-bootstrap-components#340]
- dash version: `online docs`
- dash-bootstrap-components version: `online docs`
- components affected by bug: online docs

### What is happening?

Some of the links [cyborg, lux, yeti] in the [theme documentation](https://dash-bootstrap-components.opensource.faculty.ai/docs/themes/) incorrectly point to "cosmos", a theme that doesn't seem to exits.

### What should be happening?

They should be pointing to their respective links.

I wasn't sure if the documentation branch was this or /documentation, but PR #339 fixes this.

**Comment by tcbegley** [comment]
Thanks for reporting and for submitting the fix. 🎉

I've merged #339 and pushed the updated docs.
