### ISSUE TITLE
dbc.Jumbotron Style Keyword Arg

### ISSUE THREAD

**Issue by dmintercept** [facultyai/dash-bootstrap-components#341]
I noticed that the dbc.Jumbotron component doesn't have a style keyword argument.  I wanted to set a background-image attribute

**Comment by tcbegley** [comment]
Thanks @dmintercept, good spot. Will make sure this gets added. Would also happily approve a PR that addresses this.

**Comment by tcbegley** [comment]
This is available in version 0.9.2. Upgrade with

```
pip install -U dash-bootstrap-components
```
