### ISSUE TITLE
dbc doesn't seem to work well with Django

### ISSUE THREAD

**Issue by coe-team** [facultyai/dash-bootstrap-components#342]
Hi, 

the below code will work fine in my desktop IDE.
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Navbar(
    dbc.Container(
        [
            dbc.NavbarBrand(
                [
                    html.Span("A", style={"color": "red"}),
                    html.Span("B", style={"color": "green"}),
                    html.Span("C", style={"color": "blue"}),
                ]
            ),
            dbc.Nav(
                [
                    dbc.NavItem(dbc.NavLink("Item 1", href="#")),
                    dbc.NavItem(dbc.NavLink("Item 2", href="#")),
                ],
                navbar=True,
            ),
        ]
    )
)

if __name__ == "__main__":
    app.run_server(debug=True)

However, 

once I do
from sqlalchemy import create_engine
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output, State
import dash_table
from django_plotly_dash import DjangoDash
import pandas as pd
import mysql.connector
import dash_bootstrap_components as dbc

app = DjangoDash('test', [dbc.themes.BOOTSTRAP])

and then a dbc. whatever widget in the app I get

Django version 3.0.4, using settings ‘UPS.settings’
Starting ASGI/Channels version 2.4.0 development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
HTTP GET /test/ 200 [0.13, 127.0.0.1:60098]
HTTP GET /django_plotly_dash/app/test/ 200 [0.03, 127.0.0.1:60098]
HTTP GET /django_plotly_dash/app/test/_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v0_9_0m1585057943.min.js 302 [0.01, 127.0.0.1:60098]
Not Found: /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js
HTTP GET /static/dash/component/dash_bootstrap_components/_components/dash_bootstrap_components.min.js 404 [0.02, 127.0.0.1:60098]
HTTP GET /django_plotly_dash/app/test/_dash-layout 200 [0.05, 127.0.0.1:60098]
HTTP GET /django_plotly_dash/app/test/_dash-dependencies 200 [0.07, 127.0.0.1:60099]

It seems Django skips the files pip install dash-bootstrap-components installs? Maybe I am wrong, but I can't seem to find documentation or a lot of stackoverflow questions on this.

I embedded a djangdash app as a tag in Django. With bootstrapping I can do everything. With it, I the page is stuck on load.

**Comment by coe-team** [comment]
****Without bootstrapping, I can do everything

**Comment by tcbegley** [comment]
Hi @coe-team,

Thanks for reporting this. We aren't involved in the development of Django-Plotly-Dash, so I'm not sure we can help with this issue. You'd be better off raising an issue on [their repo](https://github.com/GibbsConsulting/django-plotly-dash) instead.
