### ISSUE TITLE
Display images in Table

### ISSUE THREAD

**Issue by rbw-lpp** [facultyai/dash-bootstrap-components#350]
Hey everybody!

I wanted to show images inside dbc.Table.
I figured that I can just use HTML code for image <img> and that would work, unfortunately it doesn't.
Is this not a supported feature or am I doing something wrong?

I've tried 2 ways, one shown below where I just make the table manually, but I also tried to create table from DataFrame (with the HTML code inside the dataframe) and it didn't work either.

- dash version: `#1.10.0`
- dash-bootstrap-components version: `#0.9.2`

### What is happening?

HTML image code is shown inside the table as raw HTML code

### What should be happening?

HTML image code should display a picture

### Code

```python
table_header = [
    html.Thead(html.Tr([html.Th("image"), html.Th("SKU")]))
]

row1 = html.Tr([
    html.Td('<img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/sheep-5.jpg" style="width:100px;height:100px;">'),
    html.Td('sku')
])

row2 = html.Tr([
    html.Td('<img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/sheep-3.jpg" style="width:100px;height:100px;">'),
    html.Td('sku'),
])

table_body = [html.Tbody([row1, row2])]

table = dbc.Table(table_header + table_body)

app.layout = (
    dbc.Container([
        table
    ],
    fluid = True
    )
)
```

When I inspect the page I can see that the HTML image code is rendered inside "" in the page:
```
<td>&lt;img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/sheep-5.jpg" style="width:100px;height:100px;"&gt;</td>
```
Rather then being intepreted.
If I edit the table using Developer Tools and just paste my <img> inside it works as expected so I'm suspecting it's getting mixed up somewhere when being constructed.

**Comment by tcbegley** [comment]
Hey @rbw-lpp 

React (and hence Dash) won't convert strings to HTML elements for security reasons. You should use `html.Img` instead.

```python
table_header = [html.Thead(html.Tr([html.Th("image"), html.Th("SKU")]))]

row1 = html.Tr(
    [
        html.Td(
            html.Img(
                src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/sheep-5.jpg",
                style={"width": "100px", "height": "100px"},
            )
        ),
        html.Td("sku"),
    ]
)

row2 = html.Tr(
    [
        html.Td(
            html.Img(
                src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/sheep-3.jpg",
                style={"width": "100px", "height": "100px"},
            )
        ),
        html.Td("sku"),
    ]
)

table_body = [html.Tbody([row1, row2])]

table = dbc.Table(table_header + table_body)

app.layout = dbc.Container([table], fluid=True)
```

**Comment by rbw-lpp** [comment]
It does make sense to not convert string to HTML, thanks @tcbegley.
With your example it now works as expected.

So for this to work with the `from_dataframe` method I would have to modify the code here:
https://github.com/facultyai/dash-bootstrap-components/blob/master/dash_bootstrap_components/table.py

And for images instead of doing this:
```
html.Tr([html.Td(df.iloc[i][col]) for col in df.columns])
for i in range(len(df))
```
It should do:
```
html.Tr([html.Td(html.Img(df.iloc[i][col])) for col in df.columns])
for i in range(len(df))
```
Am I somewhere in the ballpark?

**Comment by tcbegley** [comment]
Yeah that looks good to me. Though I think `from_dataframe` should also work without modification if you have `html.Img` objects in the dataframe itself.

For example, if your original dataframe has `image_src` and `SKU` columns you could do something like the following (I haven't tested this)

```python
df["image"] = df["image_src"].map(lambda x: html.Img(src=x))
dbc.Table.from_dataframe(df[["image", "SKU"]])
```

**Comment by rbw-lpp** [comment]
I've just tested it and it works.
Thank you Tom for the help and have a lovely afternoon!
