### ISSUE TITLE
Row / Col and un-necessary H scrollbar

### ISSUE THREAD

**Issue by audetto** [facultyai/dash-bootstrap-components#351]
Please fill out the below information as much as possible.
```
dash                      1.10.0    
dash-auth                 1.3.2     
dash-bootstrap-components 0.9.2     
dash-core-components      1.9.0     
dash-html-components      1.0.3     
dash-renderer             1.3.0     
dash-table                4.6.2   
```

### What is happening?
 An unnecessary scrollbar is present even with the simplest layout example.
Chrome & FFox.

### What should be happening?

No H Scrollbar is required

### Code

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html

external_stylesheets = [dbc.themes.BOOTSTRAP]

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = html.Div(
    [
        dbc.Row(dbc.Col(html.Div("A single column"))),
        dbc.Row(
            [
                dbc.Col(html.Div("One of three columns")),
                dbc.Col(html.Div("One of three columns")),
                dbc.Col(html.Div("One of three columns")),
            ]
        ),
    ]
)
if __name__ == '__main__':
    app.run_server()
```

This, and other issues I have opened are my attempts to narrow down bigger problems I am seeing in a more complex app.
This H scroll bar is not a big deal, but other (or maybe the same?) scroll bar related issues affect my dashboard.

**Comment by tcbegley** [comment]
Hi @audetto,

Thanks for raising this and the detailed report.

You should wrap your rows and columns with a `Container`. You can set `fluid=True` to make sure that the content has 100% width. The reason for the horizontal scrolling is that Bootstrap's rows have some negative width margins set for alignment reasons, but in this case the row is falling off the side of the screen. The container counteracts this and makes everything work again. Here's the modified version of your code.

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html

external_stylesheets = [dbc.themes.BOOTSTRAP]

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

app.layout = dbc.Container(
    [
        dbc.Row(dbc.Col(html.Div("A single column"))),
        dbc.Row(
            [
                dbc.Col(html.Div("One of three columns")),
                dbc.Col(html.Div("One of three columns")),
                dbc.Col(html.Div("One of three columns")),
            ]
        ),
    ],
    fluid=True,
)
if __name__ == '__main__':
    app.run_server()
```

I'll leave this open as a reminder to make this clearer in the documentation.

**Comment by audetto** [comment]
I always forget to set fluid=True otherwise I do not really understand what container does.
Indeed with fluid it helps.

I dont really know where to ask questions, so I do it here if it is acceptable.

The doc says one should have multiple Cols as children of a Row.
On the other hand I have read (about bootstrap not necessarily related to dash), the it is possible to do something like this

row1 (col11, col12, col13)
row2 (col21, col22, col23, col24)

and so on

and then to set children of (e.g. col12) a similar structure with multiple rows of columns.
So columns are always children of rows, but it seems to be possible to set rows as children of columns as well.
```
row1(col11, 
     col12(row(col, col), row(col, col)),
     col13)
```

Is this supported? If not, how can one create a more complex layout with different parts having different row/col layout?

**Comment by tcbegley** [comment]
Yes, that's certainly supported. I think the only two rules really are:

1. Use `Row` and `Col` inside `Container`.
2. The immediate children of `Row` should always be `Col`s, but the children of `Col` can be anything, including further `Row`s.

**Comment by audetto** [comment]
I take that 1. means that I should just put entire layout in a Container 

and not that every time I use Row (and Col) I should wrap them in a Container (so potentially having many in the layout)?

**Comment by tcbegley** [comment]
Yes, you only need one container in the layout. To quote the Bootstrap docs

> While containers can be nested, most layouts do not require a nested container.

Sorry for the confusion. I'll figure out how to make our docs clearer

**Comment by tcbegley** [comment]
Sorry it took me so long to update the docs 😳 

This has finally [been done](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/layout/), apologies for past confusiong.
