### ISSUE TITLE
How to adjust the size/position when using dbc.Container with Sidebar

### ISSUE THREAD

**Issue by swatakit** [facultyai/dash-bootstrap-components#353]
Hello,

I am using dbc.Container with navbar and sidebar.

The layout of the container with navbar look perfectly balanced, equally spaced on both size.
![container_navbar](https://user-images.githubusercontent.com/33592900/79359986-7b004700-7f6d-11ea-9f91-d91193bdd800.png)

![code_navbar](https://user-images.githubusercontent.com/33592900/79361147-1fcf5400-7f6f-11ea-8db5-55141616a506.PNG)

But when I tried with Sidebar (https://github.com/facultyai/dash-bootstrap-components/tree/master/examples/multi-page-apps), 

it is a little bit off
![container_sidebar](https://user-images.githubusercontent.com/33592900/79360079-9ff4ba00-7f6d-11ea-9a60-683bd789ea4b.PNG)

![code_sidebar](https://user-images.githubusercontent.com/33592900/79361158-2362db00-7f6f-11ea-90f7-36a2eda64dac.PNG)

**Comment by tcbegley** [comment]
Hi @swatakit 

Try putting the `Container` as a child of the page-content div.

For example, using the simple sidebar example I would just change [this line](https://github.com/facultyai/dash-bootstrap-components/blob/master/examples/multi-page-apps/simple_sidebar.py#L60) to

```python
content = html.Div(dbc.Container(id="page-content"), style=CONTENT_STYLE)
```

The test I just did it worked well for me (red background added in screenshot to show where the margins are)

![image](https://user-images.githubusercontent.com/15220906/79364197-e7188600-7f40-11ea-8267-12676a839c71.png)

**Comment by swatakit** [comment]
> Hi @swatakit
> 
> Try putting the `Container` as a child of the page-content div.
> 
> For example, using the simple sidebar example I would just change [this line](https://github.com/facultyai/dash-bootstrap-components/blob/master/examples/multi-page-apps/simple_sidebar.py#L60) to
> 
> ```python
> content = html.Div(dbc.Container(id="page-content"), style=CONTENT_STYLE)
> ```
> 
> The test I just did it worked well for me (red background added in screenshot to show where the margins are)
> 
> ![image](https://user-images.githubusercontent.com/15220906/79364197-e7188600-7f40-11ea-8267-12676a839c71.png)

@tcbegley it works perfectly! thank you very much!

**Comment by tcbegley** [comment]
Glad I could help :)
