### ISSUE TITLE
Accordion Table

### ISSUE THREAD

**Issue by Tokusei** [facultyai/dash-bootstrap-components#354]
Hi, is it possible to create a table object where each row entry has an accordion/arrow to expand and show additional data, If so, Is there any example code?

**Comment by tcbegley** [comment]
Hi @Tokusei 

Unfortunately I don't think that's going to be possible using just the components that are currently available (though I'm quite happy for someone to prove me wrong). I think it would require some custom javascript / components to be created.

If you're up for the challenge there's [good documentation for building custom components](https://dash.plotly.com/plugins)

**Comment by Tokusei** [comment]
Thanks for the reply @tcbegley, I will look into the docs however I am not a web developer, So I doubt Ill be able to create one. If I do, Ill update this thread.

Another question: I am generating the table from a pandas dataframe,  However one of the table columns needs to include a html.checkbox component. Is there some way to add dash/html components into the dataframe, and then generate the table?

**Comment by tcbegley** [comment]
> Is there some way to add dash/html components into the dataframe, and then generate the table?

Yep! Just have the entries in the dataframe be `dbc.Checkbox` components. You could to it using `.map` for example, something like the following ought to work (haven't actually tested it).

```python
df["checkbox_col_name"] = df["checkbox_id"].map(lambda id_: dbc.Checkbox(id=id_))
app.layout = dbc.Table.from_dataframe(df.drop("checkbox_id", axis=1))
```

You can then add interactivity using the cool new pattern matching callbacks feature of Dash 1.11.0

**Comment by Tokusei** [comment]
Cheers, I will try to use this. Also, I would like to add pagination to the bootstrap table. Is there an example pattern for that somewhere?
