### ISSUE TITLE
How to add a close button in the upper right corner of card component?

### ISSUE THREAD

**Issue by yuzhujiutian** [facultyai/dash-bootstrap-components#374]
two questions:

1. How to add a close button in the upper right corner?

2. How to code to support dragging and changing positions between different card?

output card like as follows:
![image](https://user-images.githubusercontent.com/386347/82108777-94123880-9763-11ea-850a-99b48a052fdc.png)

picture come from:
[Python, Dash: how to add a KPI Card component to a dashboard](https://stackoverflow.com/questions/57586258/python-dash-how-to-add-a-kpi-card-component-to-a-dashboard)

**Comment by tcbegley** [comment]
Hey @yuzhujiutian 

[Here's an example](https://gist.github.com/tcbegley/b7c49d0aec605e383d3b8190448f45f2) that addresses question 1.

![image](https://user-images.githubusercontent.com/15220906/82116693-970d2900-9763-11ea-9588-a4b74de92a37.png)

Making the cards draggable to reorder them would likely require a custom Dash component, maybe one that wraps something like [this](https://github.com/StreakYC/react-draggable-list)

**Comment by yuzhujiutian** [comment]
thank you very much give me the example.

@tcbegley
