### ISSUE TITLE
Input component not clearing

### ISSUE THREAD

**Issue by gioxc88** [facultyai/dash-bootstrap-components#392]
I have a drop down menu that generates Input buttons when a value is selected 
Every time a value is selected the inputs a re-generated from scratch.

The problem is, as you can see in the gif below, that when I change the value in the drop down,  **the values in the input form do not get cleared**, even if I generate them from scratch. 

**Everything works as expected if I use `dcc.Input`** instead od `dbc.Input`, unfortunately I cannot use it because it does not play well with the `InputGroupAddon`. 

At the bottom I also posted the code used to generete `dbc.Input` on the fly

![dash-scipy](https://user-images.githubusercontent.com/41852601/83414195-5da01300-a41d-11ea-8c3c-d3adaeb13683.gif)

```
@app.callback(Output('more_params', 'children'),
              [Input({'name': 'dist', 'type': 'input'}, 'value')])
def update_params_list(dist):
    if dist is None:
        return
    params_name = get_params_list(dist)

    form = []
    for i, name in enumerate(params_name):
        addon = dbc.InputGroupAddon(name, addon_type="prepend")
        input_ = dbc.Input(id={'name': name, 'type': 'input'}, type='number',
                           debounce=True)

        if name == 'scale':
            input_.min = 0

        elements = [addon, input_]
        pair = dbc.InputGroup(elements, className="mb-1")
        form.append(dbc.Col(pair, width=11))

    form.append(dbc.FormText('fill the form and press enter to show the plot', color="secondary"))

    return html.Div(form)
```

**Comment by tcbegley** [comment]
Hey @gioxc88 

This is react trying to be clever and not re-rendering things if it doesn't have to. For now you can work around this by setting the `key` prop on the `Input` components, which will force a re-render and clear the component.

```python
input_ = dbc.Input(
    id={"name": name, "type": "input"},
    type="number",
    debounce=True,
    key=f"{dist}-{name}",
)
```

It might be possible for us to make some internal changes that means this isn't necessary, but that should do the trick.

**Comment by tcbegley** [comment]
Just a follow up, I realised that the reason this is happening is because the `id` of the components isn't changing (e.g. you have parameters called `loc` and `scale` for both distributions), so an alternative fix if you don't want to mess around with `key` is to just add `dist` to your `id`

```python
input_ = dbc.Input(
    id={"name": name, "type": "input", "dist": dist},
    type="number",
    debounce=True,
)
```

**Comment by gioxc88** [comment]
thank you for taking the time to answer my question. I use the key workaround and it works as expected.

I just wonder why if I use `dcc.Input` even if the `id` doesn't change the input gets cleared.
Many thanks
Gio

**Comment by tcbegley** [comment]
I think it's because they use the actual underlying HTML input element [to manage state](https://github.com/plotly/dash-core-components/blob/dev/src/components/Input.react.js#L69) whereas our `Input` manages its state entirely in React. Typically this distinction is not something a user would notice, but in this case it seems to make a difference to how things get rendered.
