### ISSUE TITLE
ERROR: No matching distribution found for setuptools>=40.8.0

### ISSUE THREAD

**Issue by kadusrahul** [facultyai/dash-bootstrap-components#401]

**Comment by kadusrahul** [comment]
Getting ERROR: No matching distribution found for setuptools>=40.8.0 while installing dbc package

**Comment by tcbegley** [comment]
Are you installing without internet connection / behind a firewall?

If `setuptools` is installed (check with `python -c "from setuptools import __version__; print(__version__)"`) try passing the `--no-build-isolation` flag to `pip`

**Comment by klaus3331** [comment]
@tcbegley ’s answer works for me.

**Comment by tcbegley** [comment]
We now publish wheels to PyPI which should resolve this issue. Feel free to reopen if you're still having problems.
