### ISSUE TITLE
clientside_callback hooks for dash-bootstrap-components

### ISSUE THREAD

**Issue by kkollsga** [facultyai/dash-bootstrap-components#403]
Hi,
I'm working on a dash app with collapse component but the server sidecallback is quite slow. I want to speed up the component by using the clientside_callback, but the browser cannot access the is_open property. Is there a property (or other work around) that the clientside_callback can access and trigger the collapse animation?
Thanks =)

**The collapse component:**
```
collapse = html.Div(
    [
        dbc.Button(
            "Modify",
            id="collapse-button",
            className="mb-3",
            color="primary",
        ),
        dbc.Collapse(
            dbc.Card(
                [
                    dbc.CardBody("This content is hidden in the collapse")
                ],
                style={"width": "18rem"},
            ),
            id="collapse",
        ),
    ]
)
```

**Here is the clientside_callback that is triggering an error:**
```
app.clientside_callback(
    """
    function(n, is_open) {
        if n {
            return { not is_open }
        } else {
            return { is_open }
        }
    }
    """,
    Output("collapse", "is_open"),
    [Input("collapse-button", "n_clicks")],[State("collapse","is_open")],
)
```

**Here is the equivalent serverside callback (from examples):**
```
@app.callback(
    Output("collapse", "is_open"),
    [Input("collapse-button", "n_clicks")],
    [State("collapse", "is_open")],
)
def toggle_collapse(n, is_open):
    if n:
        return not is_open
    return is_open
```

**Comment by tcbegley** [comment]
Hey @kkollsga 

I don't think we need to do anything to support this, it looks like your function isn't valid JavaScript though? Try this:

```python
import dash
import dash_bootstrap_components as dbc
from dash.dependencies import Input, Output, State

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Button("Toggle", id="collapse-button"),
        dbc.Collapse("Some content", id="collapse"),
    ]
)

app.clientside_callback(
    """
    function(n, is_open) {
        if (n) {
            return !is_open;
        }
        return is_open;
    }
    """,
    Output("collapse", "is_open"),
    [Input("collapse-button", "n_clicks")],
    [State("collapse", "is_open")],
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by kkollsga** [comment]
Thanks @tcbegley =) My javascript was indeed pretty poor, and I understand you guys cannot support everything =) 

I still don't think the [State("collapse", "is_open")] works from clientside callback though. I was hoping there was a simple workaround to get clientside callbacks to work, since their performance is so much higher than server side callbacks. 
At the moment I'm getting the error message: _"Cannot read property 'is_open' of undefined"_. Maybe I'll need to set up some custom styling or something. I'll poke around and see if I can get something out of it.

**Comment by kkollsga** [comment]
Thanks @tcbegley my fault =) It does actually work :)

**Comment by tcbegley** [comment]
Great! Will close this then.
