### ISSUE TITLE
Error when running graphs_in_tabs.py

### ISSUE THREAD

**Issue by anhailing** [facultyai/dash-bootstrap-components#404]
Before opening:

- [Search for duplicate or closed issues](https://github.com/facultyai/dash-bootstrap-components/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/facultyai/dash-bootstrap-components/blob/master/.github/CONTRIBUTING.md)

Please fill out the below information as much as possible.

- dash version: `#1.12.0`
- dash-bootstrap-components version: `#0.10.2`
- components affected by bug:

### What is happening?
when running the code forked from this github, an error popped up in the dashboard "An object was provided as `children` instead of a component, string, or number (or list of those). Check the children property that looks something like:...."

### Code

```python
# your code here
```

### Error messages

```bash
"An object was provided as `children` instead of a component, string, or number (or list of those). Check the children property that looks something like:...."
```

**Comment by tcbegley** [comment]
Hey @anhailing 

Thanks for reporting, I just merged a fix for this. I made a related improvement to the implementation of `Tabs` which will make it into the next release.
