### ISSUE TITLE
Home page examples are broken

### ISSUE THREAD

**Issue by tschmel** [facultyai/dash-bootstrap-components#407]
### What is happening?

The examples provided on the home page seem to be broken right now. I tried different browsers yielding the same results. [This example](https://dash-bootstrap-components.opensource.faculty.ai/examples/graphs-in-tabs/) doesn't show any graphs for me. [Here](https://dash-bootstrap-components.opensource.faculty.ai/examples/simple-sidebar/) I only see the sidebar content, but not the page content.

### What should be happening?

From the [example overview page](https://dash-bootstrap-components.opensource.faculty.ai/examples/) there seem to be graphs and content visible on the pages.

**Comment by tcbegley** [comment]
Thanks @tschmel 

Looks like the callbacks are all not firing in those examples for some reason, looking into it.

**Comment by tcbegley** [comment]
Seems to be related to a change made in Dash 1.11.0, so I've pinned the version of Dash being used to host the docs for now. The examples themselves work fine, it's something to do with how they are embedded in the docs. Will leave this open until I have time to figure out a permanent fix.

**Comment by tcbegley** [comment]
Still some issues with the multi-page example. Deployed docs are fine as still using Dash 1.10.0.
