### ISSUE TITLE
NavLink disabled attribute broken

### ISSUE THREAD

**Issue by michelbecker** [facultyai/dash-bootstrap-components#409]
- dash version: `#1.12.0`
- dash-bootstrap-components version: `#0.10.2`
- components affected by bug: NavLink

### What is happening?

The 'disabled' attribute of the dbc.NavLink component is not being applied correctly. When set to 'True' the link is not greyed out and still clickable.
As far as I can tell, this only affects `#0.10.2`. `#0.10.1` is fine.

I noticed this in my app after a recent upgrade but it's noticable even in the documentation (as of today):
https://dash-bootstrap-components.opensource.faculty.ai/docs/components/nav/

**Comment by tcbegley** [comment]
Thanks @michelbecker 

Looks like a bug introduced in the recent refactor. Will fix and add some tests so I don't miss it again.

For now, if you're not already, I recommend sticking to `0.10.1`: `pip install dash-bootstrap-components==0.10.1`

**Comment by tcbegley** [comment]
Resolved in version 0.10.3. Upgrade with

```
pip install -U dash-bootstrap-components
```

Thanks again for reporting.
