### ISSUE TITLE
[QUESTION] Use some components in React app only

### ISSUE THREAD

**Issue by HedgeShot** [facultyai/dash-bootstrap-components#414]
Hi,

Is it possible to use these components in a React webapp directly? I am trying to re-write a dash app into a pure react app & tried to use the RadioItems component. It looks more or less fine but radio items (switch=true) can't be toggled (visually that is, they are triggered on click. It looks like it is coming from `setProps` that is undefined & coming from dash directly. Any advice?

Thank a lot for this great package!

**Comment by tcbegley** [comment]
Hey @HedgeShot 

State in Dash components is managed by dash-renderer, it passes props to each component in the layout as well as the `setProps` function you observed. You call `setProps` when a prop value has been modified by the component, dash-renderer then takes care of triggering the appropriate callbacks and so on. The components in this library have been designed under the assumption that they are being managed by something like dash-renderer, so don't really work properly in isolation as you observed.

You have a few options I can think of:

1. You could write a lightweight wrapper that passes a `setProps` function into the component and manages state one level up. See the [Dash component boilerplate](https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/src/demo/App.js) for an example of this.
2. You could copy the source code from this repository and modify it appropriately.
3. You could build your own version on top of either [reactstrap](https://reactstrap.github.io/) or [react-bootstrap](https://react-bootstrap.github.io/)

**Comment by HedgeShot** [comment]
thanks a lot for your answer!
