### ISSUE TITLE
Drag and drop cards

### ISSUE THREAD

**Issue by santialferez** [facultyai/dash-bootstrap-components#415]
Hi,

Thank you very much for your great extension of dash.

is it possible use the current dbc to drag and drop cards? it is something like this: https://codepen.io/mgmarlow/pen/YwJGRe

It would be great to use inside dash!

Best

**Comment by tcbegley** [comment]
Hi @santialferez 

That functionality isn't part of this library unfortunately. The example you linked to is using _dragula_, which looks pretty simple and powerful, there are [React bindings available](https://github.com/bevacqua/react-dragula) for it to. You might be able to use it to make your own dash-dragula component using the [dash-component-boilerplate](https://github.com/plotly/dash-component-boilerplate).

**Comment by tcbegley** [comment]
I just saw [this post](https://community.plotly.com/t/drag-and-drop-cards/42480/2) on the Plotly forums, looks like a possible solution that wouldn't require you to implement a new component.

**Comment by santialferez** [comment]
Hi @tcbegley.

Thank you for answering so quickly.  Yes, I saw it because I wrote that post, ;).

**Comment by tcbegley** [comment]
> Yes, I saw it because I wrote that post

Ah right 😅 well I'm glad you got an answer. 

His idea of using clientside callbacks to run some JavaScript after components have been rendered really neat.
