### ISSUE TITLE
Setting column sizes for individual screens still sets default col-* class

### ISSUE THREAD

**Issue by technicallyrice** [facultyai/dash-bootstrap-components#417]
- dash version: `#1.12.0`
- dash-bootstrap-components version: `#0.10.3`
- components affected by bug:

### What is happening?

When I add in specific breakpoints for specific screen sizes, the formatting isn't correct. Looking at the classes applied to the elements via Inspect, it looks to apply all the correct classes, but it does not change from the sizes set for sm when the screen goes to medium, large, or xl.

### What should be happening?

It should resize properly.

### Code

In my code, the columns all are defined with the following as added parameters:

```python
sm=6, md=2, lg=2, xl=2
```

Those are the only things set for column size. No width is set.

When I look at the HTML generated I see the following (mini_container is custom that just sets background and text color):

```html
class="mini_container col-sm-6 col-md-2 col-lg-2 col-xl-2"
```

This looks right but it still does not work. Removing it all and setting width works fine, however.

EDIT

In addition, when I set the breakpoints only using sm and md such as:

```python
sm=6, md=2
```
It only uses the md size and stays that way even after switching to a mobile view.

I will also note that with only the width set it works as it should on large screens and stacks them all on top of each other on mobile. I'm trying to edit how it shows on mobile and it just looks like it isn't working.

**Comment by tcbegley** [comment]
Hi @technicallyrice, thanks for reporting

That sounds strange, could you share some screenshots or a bit more code? I come up with the following very simple example to test things out and wasn't able to see any problems.

```python
import dash
import dash_bootstrap_components as dbc

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    dbc.Row(dbc.Col(dbc.Card("Testing", body=True), sm=6, md=2)),
    fluid=True,
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by tcbegley** [comment]
Closing due to lack of response, feel free to reopen if you're still having problems.
