### ISSUE TITLE
Minor issue: Missing documentation for dbc.Label on site

### ISSUE THREAD

**Issue by oegedijk** [facultyai/dash-bootstrap-components#418]
It seems that the documentation on the site for the parameters of dbc.Label has gone missing. I would have expected it maybe on the Forms page [https://dash-bootstrap-components.opensource.faculty.ai/docs/components/form/](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/form/ )but it's not there. 

I can inspect the docstring ofcourse, but would be nice to have it on the site as well!

**Comment by tcbegley** [comment]
Thanks for reporting! It's an easy fix so I just opened #419 to address it.

**Comment by tcbegley** [comment]
Pushing the change now, should appear in the documentation shortly.
