### ISSUE TITLE
Adding text to a spinner

### ISSUE THREAD

**Issue by FilomenoSanchez** [facultyai/dash-bootstrap-components#420]
Hi, first of all thanks for an amazing package, I found it very useful and it really saved me tons of time! I've been trying for a while now to display a text under a `dbc.Spinner` when `fullscreen=True` (I'm using python). The problem I've got right now is that certain process on my app takes quite a long time to complete (up to 3 minutes), and most users won't wait for that long without wondering if their internet connection is broken and refreshing the website. I've been trying to display a message under this spinner, something like "Please wait this can take up to 3 minutes". I know in html this can be done as described in this [post](https://stackoverflow.com/questions/55528321/put-text-under-a-spinner-bootstrap), here is the snippet:

```html
<div class="d-flex flex-column align-items-center justify-content-center">
   <div class="row">
       <div class="spinner-border" role="status">
           <span class="sr-only">Loading...</span>
       </div>
    </div>
    <div class="row">
      <strong>Please wait this process can take up to 3 minutes</strong>
    </div>
</div>
```
Is there a way to achieve this effect through `dbc.Spinner`? The effect I want to achieve is something like this image: 

![image](https://user-images.githubusercontent.com/17200301/88319304-de8bd480-cd13-11ea-8969-f82282ea94d0.png)

**Comment by tcbegley** [comment]
Hey @FilomenoSanchez 

This is possible with some sneaky custom CSS. Take a look at this example

```python
import time

import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Spinner(
            html.Div(id="output"),
            fullscreen=True,
            fullscreenClassName="spinner-with-text",
        ),
        dbc.Button("Click", id="button"),
    ],
    className="p-5",
)


@app.callback(Output("output", "children"), [Input("button", "n_clicks")])
def load_content(n):
    if n:
        time.sleep(100)
        return f"Button clicked {n} time{'s' if n > 1 else ''}"
    return "Button not yet clicked"


if __name__ == "__main__":
    app.run_server(debug=True)
```

with the following CSS in `assets/style.css`

```
.spinner-with-text::after {
  content: 'Please wait, this process can take up to 3 minutes';
  position: fixed;
  top: 55vh;
  font-weight: 500;
}
```

With those, I see the following

![image](https://user-images.githubusercontent.com/15220906/88369725-893dda80-cd88-11ea-859b-2ed664c08ff4.png)

**Comment by FilomenoSanchez** [comment]
Awesome, it works! Thanks a lot for the answer, I think we can close this now.
