### ISSUE TITLE
Adding placeholder capability to dbc.Select

### ISSUE THREAD

**Issue by tmcf2775** [facultyai/dash-bootstrap-components#426]
Hi, I would like to request that the dbc.Select component have the same placeholder capability as the dcc.Dropdown component please? 
It is much easier for a new user to see which menu they are supposed to click on, rather than blindly click through a whole heap of menus ( I am using dbc for some heavy calc's that require a fair few different parameter settings). I currently use the dcc.Dropdown component because of this, however, that component doesn't align well with the dbc button component I am also using. I would prefer to use exclusively dbc components so that I have no css / styling issues. 
Hope its a quick win.
Cheers. 
![image](https://user-images.githubusercontent.com/43426280/88885096-36c65780-d27b-11ea-85cb-3d62a66031f3.png)

**Comment by tcbegley** [comment]
Hi @tmcf2775 

Thanks for raising this, I'll take a look into it. The difficulty is that the HTML `<select>` element on which `Select` is based doesn't actually have a placeholder attribute, but there might a work around.

Some alternatives that might work for you in the meantime:

1. You could use `FormGroup` along with `Label` and `FormText` to add information about the input for users. Take a look [here](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/form/) in our docs for example.

2. I've made some [Bootstrap stylesheets](https://github.com/tcbegley/dash-bootstrap-css) with added support for dash-core-components. It will restyle the `dcc.Dropdown` to make it look more bootstrappy, and in particular should line things up with the button (I need to make a few updates still, but for this use case it should be fine).

**Comment by tcbegley** [comment]
Just merged #431 which adds support for a placeholder to Select. Will make it into the next release.

**Comment by tmcf2775** [comment]
Thanks very much!
