### ISSUE TITLE
Adding 'disabled' option in Checkbox

### ISSUE THREAD

**Issue by bmarcote** [facultyai/dash-bootstrap-components#428]
When creating a Checklist, one can add the "disabled" option through the options parameter, for example:

```
dbc.Checklist(options=[
        {"label": "First radio", "value": 1},
        {"label": "Second radio", "value": 2},
        {
            "label": "Third disabled radio",
            "value": 3,
            "disabled": True,
        }])
```

However, the `Checkbox` class does not support this. There is no explicit `disabled` attribute that could be called, as happens with the `checked` option (or haven't seen any workaround for that). While Checklist is always recommended, in a few cases a FormGroup with Checkbox and Label is the only option (e.g. when the labels need to be decorated with some extra HTML code).

I made it working just by adding an extra `disabled` attribute to the `Checkbox.py` class, following the same approach as performed in that class to the `checked` attribute, and this is apparently working. However, you may get a cleaner implementation in the original code.

**Comment by tcbegley** [comment]
Thanks @bmarcote, should be possible to add that, I'll take a look.

**Comment by tcbegley** [comment]
Added this in #432, will make it into the next release soon.
