### ISSUE TITLE
Number dbc.Input does not trigger callbacks with up/down arrow buttons when debounce is True.

### ISSUE THREAD

**Issue by ZackArnold** [facultyai/dash-bootstrap-components#430]
- dash version: `#1.14.0`
- dash-bootstrap-components version: `#0.10.3`
- components affected by bug: dbc.Input

### What is happening?

When setting `debounce` to True a numeric Input component does not trigger the callbacks for value changes when clicking the up/down arrow buttons on the input box. Instead, you have to press enter or click in and outside the box so that it loses focus as described in the documentation.

### What should be happening?

I would expect that with `debouce` enabled the act of clicking the up/down arrow would still be sufficient for triggering a callback. Admittedly this is just my opinion but I have been confused by the above behavior as a user for some time until I reviewed the documentation.

### Code

```python
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output, MATCH
import dash

app = dash.Dash(__name__)
app.layout = html.Div(
    [
        html.P("This numeric input works (debounce = False). Using the arrow buttons will trigger the callback."),
        dbc.Input(id={"type": "number", "index": 0}, type="number", min=0, max=10, step=1, debounce=False),
        html.P(id={"type": "output", "index": 0}),
        html.P("This numeric input doesn't work (debounce = True). You have to click in and out of the text field to trigger the callback."),
        dbc.Input(id={"type": "number", "index": 1}, type="number", min=0, max=10, step=1, debounce=True),
        html.P(id={"type": "output", "index": 1}),
    ]
)


@app.callback(Output({"type": "output", "index": MATCH}, "children"), [Input({"type": "number", "index": MATCH}, "value")])
def output_text(value):
    return value


if __name__ == "__main__":
    app.run_server(debug=True)

```

**Comment by tcbegley** [comment]
Hi @ZackArnold,

Thanks for reporting and including an example.

The docstring for `debounce` says

> If true, changes to input will be sent back to the Dash server only when the enter key is pressed or when the component loses focus.  If it's false, it will sent the value back on every change.

which matches the behaviour you describe. Moreover this is consistent with `dash_core_components.Input`, and I think if we were to deviate from their behaviour that could create more confusion. Is there a reason you expected different behaviour / or that different behaviour seemed more intuitive to you?

**Comment by ZackArnold** [comment]
Hi @tcbegley,

I hadn't noticed that it was consistent with `dash_core_components.Input`. Thanks for pointing that out. I agree, deviating from that behavior probably would be confusing to users. In that case, this may be the wrong place to have this discussion.

I suppose my opinion is just that I would see using the arrow buttons as an equivalent action to enter key presses. That is, each press of a button is a deliberate and discrete action by the user with the intent to adjust the value by some fixed step. If they were to desire a far off value then they would choose to type it in manually as usual.

Maybe a better thought on the matter: I would say it is intuitive that when I type in a value, then go do something else with the page, that my value has been handled by the server due to losing focus. I would not say it is intuitive that when I deliberately press those buttons, then go do something else on the page, the value I see in the box has *not* been handled by the server because I didn't (seemingly arbitrarily) click the inside of the box first.

For now I will think a bit more about my own design and maybe bring this up in the other project where it rightfully belongs. Thanks for the clarification and commentary.

**Comment by tcbegley** [comment]
> each press of a button is a deliberate and discrete action by the user with the intent to adjust the value by some fixed step

I can see that argument, though it's possible that to go from e.g. 6 to 10 the user does 4 clicks in rapid succession and doesn't want any of the intermediate values to be used in the callback?

In any case, thanks for linking the other issue, I'll keep an eye on it and maintain parity with their implementation if they change the behaviour.

Will close this for now in favour of monitoring the other issue.
