### ISSUE TITLE
getting started app - missing ,

### ISSUE THREAD

**Issue by ann-marie-ward** [facultyai/dash-bootstrap-components#433]
Before opening:

- [Search for duplicate or closed issues](https://github.com/facultyai/dash-bootstrap-components/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/facultyai/dash-bootstrap-components/blob/master/.github/CONTRIBUTING.md)

Please fill out the below information as much as possible.

- dash version: `#x.x.x`
- dash-bootstrap-components version: `#x.x.x`
- components affected by bug:

### Code

```python
# your code here
```

### Error messages

```bash
paste any error messages here
```

**Comment by ann-marie-ward** [comment]
Hi!

dash- bootstrap is awesome!  Thanks for making this available.  

 If you get to this site by clicking on the link in the Dash documentation:  

![image](https://user-images.githubusercontent.com/56776578/90578695-d1c69900-e178-11ea-9de2-855a2dad9f51.png)


https://dash-bootstrap-components.opensource.faculty.ai/
You get to a page where the "getting started" app has a typo:  missing comma:

`app.layout = dbc.Alert(
    "Hello, Bootstrap!" className="m-5"
)`

This version has a corrected "getting started app:
https://dash-bootstrap-components.opensource.faculty.ai/docs/

`app.layout = dbc.Container(
    dbc.Alert("Hello Bootstrap!", color="success"),
    className="p-5",
)`

It's a small thing, but somebody new to dash and bootstrap might be confused by the error message.  Might be good to update the link on the dash-docs.

**Comment by tcbegley** [comment]
Yikes, good spot! Thanks for reporting, addressed in #434
