### ISSUE TITLE
[Question] Button click on enter key press.

### ISSUE THREAD

**Issue by meteoDaniel** [facultyai/dash-bootstrap-components#469]
Does any one know how to trigger button click with the enter key ? 
E.g. like this example https://getbootstrap.com/docs/4.0/examples/sign-in/

**Comment by tcbegley** [comment]
Hey @meteoDaniel 

You could use the `n_submit` property of the inputs to trigger your callback, this increments when the user presses enter while the input has focus. That might look something like this

```python
html.Div([
    dbc.Input(id="email", type="email"),
    dbc.Input(id="password", type="password"),
    dbc.Button("Log in", id="button"),
])

@app.callback(
    Output(..., ...),
    [Input("email", "n_submit"), Input("password", "n_submit"), Input("button", "n_clicks")],
    [State("email", "value"), State("password", "value")],
)
def handle_login(n1, n2, n3, email, password):
    print("form submitted)
    # rest of callback
```

I just submitted #470 which will allow you to set `type="submit"` on `dbc.Button`. When that's released you can do this instead which I think is a bit cleaner.

```
dbc.Form(
    [
        dbc.Input(id="email", type="email"),
        dbc.Input(id="password", type="password"),
        dbc.Button("Log in", type="submit"),
    ],
    id="form",
)

@app.callback(
    Output(..., ...),
    Input("form", "n_submit"),
    [State("email", "value"), State("password", "value")],
)
def handle_login(n, email, password):
    print("form submitted")
    # rest of callback
```

**Comment by meteoDaniel** [comment]
Dear @tcbegley,
thanks for this nice feature. That is something that is really missed in the das core components. 

 when do you plan a new release ? 

Best regards

**Comment by tcbegley** [comment]
Hey @meteoDaniel 

It might be a few weeks before a new release as there's a few more features I want to finalise to include.

I made a pre-release with the Button type fix described above though. See [here](https://pypi.org/project/dash-bootstrap-components/0.10.8rc1/)

Install with

```
pip install dash-bootstrap-components==0.10.8rc1
```

**Comment by meteoDaniel** [comment]
Awesome ! :)
