### ISSUE TITLE
Hot to style active_tab seperately?

### ISSUE THREAD

**Issue by meteoDaniel** [facultyai/dash-bootstrap-components#473]
I have implemented a change of the style of an active_tab to highlight it. 
But unfortunately the change in the style with a callback caused a flickering screen. 

Here is an example code: 
```
import dash_html_components as html
import dash
import dash_bootstrap_components as dbc
import flask
import os

server = flask.Flask(__name__)
app = dash.Dash(
    __name__,
    server=server,
    meta_tags=[{"name": "viewport", "content": "width=device-width"}],
    title='meteoDash',
    update_title=None,
)

app.layout = html.Div(
        [
               dbc.Tabs(
            [
                dbc.Tab([html.P('Tab 1')], label="Tab 1", tab_id="tab-1", id="tab-1"),
                dbc.Tab([html.P('Tab 2')], label="Tab 2", tab_id="tab-2", id="tab-1"),
            ],
            id="tabs",
            active_tab="tab-1",
        )
         ])

@app.callback(
    [Output('tab-1', 'label_style'),
     Output('tab-2', 'label_style')],
    [Input('tabs-maps-container', 'active_tab')],)
def change_background_color_of_tab(active_tab: str):
    if active_tab == 'live-weather-tab':
        return [{'background-color': 'red', 'color': 'white'}, {}]
    else:
        return [{}, {'background-color': 'red', 'color': 'white'}]

if __name__ == "__main__":
    server.run(host='0.0.0.0', port=8050)
```
Is there a way to avoid this flickering? Would be nice to define a style of an active_tab directly.

**Comment by tcbegley** [comment]
Could you clarify what you mean by flickering? I wasn't seeing the issue running your code:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/15220906/98557236-d98b6a80-229b-11eb-963d-b54f43ac7ffa.gif)

We could certainly add `active_label_style` etc. though. I'll add it to the backlog.

**Comment by meteoDaniel** [comment]
1.: `active_label_style` is what I mean!
2.: Which software/tool do you use to make this gif? Because I think this flickering has to do with my App size? Is this possible? I am running these tabs in a huge multi page app with around 30 callbacks.

**Comment by tcbegley** [comment]
1. Great, should be doable
2. I used macOS' native screen capture and converted to a GIF with ezgif.com. I don't think the size of the app by itself should cause the flickering here... but it is possible that one of your other callbacks might be interacting with the tabs and causing an issue? Which OS and browser are you using?
3. If you're happy to write some custom CSS, you can do the same with bootstrap tabs, something like

    ```css
    .nav.nav-tabs .nav-link.active {
      background-color: red;
    }
    ```
    
    will probably work (untested).

**Comment by meteoDaniel** [comment]
Great thanks for your Suggestion.
