### ISSUE TITLE
Tabs on hover

### ISSUE THREAD

**Issue by filipcamachoc** [facultyai/dash-bootstrap-components#475]
Hello,
This is a small issue on the Tabs component. When hovering on any of the tabs the mouse pointer should behave as if it were a link but currently the pointer is just a cursor. It's a small detail but it should indicate to the end user that the tab can be clicked. Thank you and please let me know if this has a solution.
Regards,
Phil

**Comment by tcbegley** [comment]
Hi @filipcamachoc 

Thanks for raising this. Looks like a bug which we should definitely fix in the next release. In the meantime you can work around that using the `tab_style` argument of the `Tab`

```python
dbc.Tab(..., tab_style={"cursor": "pointer"})
```

**Comment by filipcamachoc** [comment]
Thank you Tom!

**Comment by tcbegley** [comment]
Just pushed a fix, the above workaround should no longer be necessary after the next release (hopefully next few weeks, definitely before the end of the year).
