### ISSUE TITLE
Dash bootstrap dbc.CardImg doesn’t work after embedding Dash app into a Flask app

### ISSUE THREAD

**Issue by MilicaMedic** [facultyai/dash-bootstrap-components#477]
Hi,

I have first created cards with images which worked great, using the following example:

```
card = dbc.Card(
    [
        dbc.CardImg("src=app.get_asset_url('image.png')", top=True),
        dbc.CardBody(
            [
                html.H4("Card title", className="card-title"),
                html.P(
                    "Some quick example text to build on the card title and "
                    "make up the bulk of the card's content.",
                    className="card-text",
                ),
                dbc.Button("Go somewhere", color="primary"),
            ]
        ),
    ],
    style={"width": "18rem"},
)
```
After embedding the dash app within the flask app all dash bootstrap components are working except the dbc.CardImg is not loading.

I have changed the part

`dbc.CardImg("src=app.get_asset_url('image.png')", top=True)`
into

`dbc.CardImg(src="app/assets/image.png", top=True)`
but that doesn’t load the picture either (it finds the picture but cannot load it)

Is there anything I should have done when the app is embedded?

Thanks

**Comment by tcbegley** [comment]
Hi @MilicaMedic 

How are you running / deploying the Flask app?

I've seen something similar to this before and the solution was to make sure `__name__` was being passed to the Flask server, either

```python
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])
```

or if creating Flask server manually

```python
server = flask.Flask(__name__)
app = dash.Dash(server=server, external_stylesheets=[dbc.themes.BOOTSTRAP])
```

are you already doing this? I think it's necessary to let Flask find the `assets/` folder when deploying and might be what's wrong here?

**Comment by MilicaMedic** [comment]
I'm using following functions in the __init__ file:

```
def create_app():
    server = Flask(__name__)
    server.config.from_object(BaseConfig)
    bootstrap = Bootstrap(server)
     ........

   return server
```
and:

```
def register_dashapp(app, title, base_pathname, layout, register_callbacks_fun):
    # Meta tags for viewport responsiveness
    meta_viewport = {"name": "viewport", "content": "width=device-width, initial-scale=1, shrink-to-fit=no"}

    my_dashapp = dash.Dash(__name__,
                           server=app,
                           url_base_pathname=f'/{base_pathname}/',
                           assets_folder=get_root_path(__name__) + '/index/assets/',
                           external_stylesheets=[dbc.themes.SUPERHERO, FA],
                           meta_tags=[meta_viewport])
                           
    my_dashapp.config.suppress_callback_exceptions = True

    with app.app_context():
        my_dashapp.title = title
        my_dashapp.layout = layout
        register_callbacks_fun(my_dashapp)
    _protect_dashviews(my_dashapp)

```

**Comment by MilicaMedic** [comment]
Found the issue, I have changed:

`dbc.CardImg(src="app/assets/image.png", top=True)`

into

`dbc.CardImg(src="/assets/image.png", top=True)` 

but figured that the absolute path doesn't work correctly. So then I've changed into:

`dbc.CardImg(src="assets/image.png", top=True)`

Now  it displays.

Thanks,
Milica

**Comment by tcbegley** [comment]
Ah great! Glad you resolved it, sorry I didn't manage to get back to you quicker.
