### ISSUE TITLE
dbc.NavLink in Simple Sidebar example only works with external_link=True

### ISSUE THREAD

**Issue by Coder129542** [facultyai/dash-bootstrap-components#505]
When I run the simple sidebar example code provided at the location below and run it, the app is created just like in the example however, the page does not dynamically update. The only work around I was able to find was to set external_link = True, however, then it reloads the page each time I click on a new sidebar item.

https://dash-bootstrap-components.opensource.faculty.ai/examples/simple-sidebar/

code i'm running : https://github.com/facultyai/dash-bootstrap-components/blob/master/examples/multi-page-apps/simple_sidebar.py

Thanks!

**Comment by tcbegley** [comment]
Hi @Coder129542 

Can you check which version of Dash / dash-bootstrap-components / dash-core-components you have?

You can either do something like 

```
pip list | grep dash
```

or in Python something like

```
from dash import __version__ as dash_version
from dash_bootstrap_components import __version__ as dbc_version
from dash_core_components import __version__ as dcc_version

print("Dash", dash_version)
print("dash-bootstrap-components", dbc_version)
print("dash-core-components", dcc_version)
```

**Comment by Coder129542** [comment]
Hello,

Thank you for the quick reply! Here are the versions i'm running:

Dash 1.17.0
dash-bootstrap-components 0.11.1
dash-core-components 1.3.1

Thank you!

**Comment by tcbegley** [comment]
Your version of `dash-core-components` is quite old and out of sync with the version of Dash you have. The way internal links work changed in Dash 1.9.0 (dash-core-components 1.8.0).

You should be able to fix it by just updating everything

```
pip install -U dash dash-bootstrap-components
```

**Comment by Coder129542** [comment]
Thank you! That worked great. Anaconda didn't keep up with the latest revs it seems.

**Comment by tcbegley** [comment]
Great, glad I could help!
