### ISSUE TITLE
using dash_bootstrap_components, Firefox loads  slowly

### ISSUE THREAD

**Issue by limmyforget** [facultyai/dash-bootstrap-components#508]
After using dash_bootstrap_components, Firefox loads very slowly, always turning around, Google Chrome loads faster, and it is fast without dash_bootstrap_components

**Comment by tcbegley** [comment]
Hi @limmyforget 

Could you share some more details about the app you are running and the nature of the delay? If you can share code that would be ideal. Is the initial load of the app slow, or is the app slow in general?

**Comment by limmyforget** [comment]
> Hi @limmyforget
> 
> Could you share some more details about the app you are running and the nature of the delay? If you can share code that would be ideal. Is the initial load of the app slow, or is the app slow in general?
Thank you very much. It was my own network problem. I was confused yesterday and didn't even find out the reason. Excuse me.

**Comment by tcbegley** [comment]
No problem, glad it's resolved 🙂
