### ISSUE TITLE
Multi-Value Select

### ISSUE THREAD

**Issue by YukunYangNPF** [facultyai/dash-bootstrap-components#510]
Hello,

Is it possible for dbc.Select to support multi-value?

In my best knowledge, there is no parameters like multi=True to make it happen

Thanks in advance.

**Comment by tcbegley** [comment]
Hi @YukunYangNPF 

Unfortunately it's not really possible. The component, unlike `dash_core_components.Dropdown` is simply rendering a HTML `<select>` element, which does have a multiple selection option but it renders items inside a scrollable list box and doesn't look quite like you might be expecting. See the example [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#advanced_select_with_multiple_features)

I suggest instead you use `dash_core_components.Dropdown` with `multi=True`. You could also check out my [dash-bootstrap-css repo](https://github.com/tcbegley/dash-bootstrap-css) which will make the Drodown look a bit more Bootstrappy
