### ISSUE TITLE
Standalone RadioButtons don't change checked state correctly when name is defined

### ISSUE THREAD

**Issue by amarvin** [facultyai/dash-bootstrap-components#516]
- dash version: `1.19.0`
- dash-bootstrap-components version: `0.11.1`
- components affected by bug: `RadioButton`

### What is happening?

Standalone radio buttons with matching `name` attribute should work like `RadioItems` whereby only one can be checked at a time, but they aren't working correctly. There is unexpected states with all radio buttons unchecked, including the one that was just clicked.

I couldn't use `RadioItems` in my case, as I needed the `RadioButton` separated in rows of a table.

### What should be happening?

Standalone radio buttons with matching `name` attribute should work like `RadioItems` whereby only one can be checked at a time. Clicking a currently checked radio button should do nothing. Clicking a currently unchecked radio button should check it and uncheck the others.

### Code

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html

app = dash.Dash()

app.layout = html.Div(
    [
        dbc.FormGroup(
            [
                dbc.RadioButton(
                    className="form-check-input",
                    id=f"standalone-radio{i}",
                    name="standalone-radio-form",
                ),
                dbc.Label(
                    f"This is a radio button {i}",
                    className="form-check-label",
                    html_for=f"standalone-radio{i}",
                ),
            ],
            check=True,
        )
        for i in range(3)
    ],
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

### Error messages

No error message from Dash or in the web browser console.

**Comment by tcbegley** [comment]
Hi @amarvin 

Thanks for raising this and for providing a clear example, very helpful 🙂 

Off the top of my head I'm not sure how we can support this. The challenge is making this integrate with dash-renderer's state management. I'll have a play around though and see if I can come up with anything.

**Comment by amarvin** [comment]
Thanks for the fast response!

**Comment by amarvin** [comment]
This is my workaround:

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html

app = dash.Dash()

app.layout = html.Div(
    [
        dbc.FormGroup(
            [
                dbc.Input(
                    className="form-check-input",
                    id=f"standalone-radio{i}",
                    name="standalone-radio-form",
                    type="radio",
                    value=i,
                ),
                dbc.Label(
                    f"This is a radio button {i}",
                    html_for=f"standalone-radio{i}",
                    className="form-check-label",
                ),
            ],
            check=True,
        )
        for i in range(3)
    ],
)

if __name__ == "__main__":
    app.run_server(debug=True)
```
