### ISSUE TITLE
FR: Styling for Dash DataTable

### ISSUE THREAD

**Issue by Peter-Pasta** [facultyai/dash-bootstrap-components#527]
Hi everyone, would it be possible for you to provide styling for Dash DataTable? You already have a HTML Table component that looks great. Maybe you could apply this to Dash DataTable (https://dash.plotly.com/datatable).
Thank you!

**Comment by tcbegley** [comment]
Hi @Peter-Pasta 

This is something I would like to do, but it's kind of complicated and haven't had time to dedicate to it yet. If I do work on it, it will likely appear at [my dash-bootstrap-css repo](https://github.com/tcbegley/dash-bootstrap-css)

**Comment by Peter-Pasta** [comment]
Ok cool. I am looking forward to it. 👍
