### ISSUE TITLE
Elements in Fade still respond to mouse events

### ISSUE THREAD

**Issue by amarvin** [facultyai/dash-bootstrap-components#532]
- dash version: `1.19.0`
- dash-bootstrap-components version: `0.11.1`
- components affected by bug: `Fade`

### What is happening?

`Fade` has `opacity` that transitions from 1 to 0. When faded (`opacity=0`), you cannot see the children elements, but they still respond to mouse events. This is a problem for things like tooltips where the tooltip then can still be opened for an element that is faded.

### What should be happening?

`Fade` should also have `visibility:hidden` when fully faded to avoid mouse events (see https://stackoverflow.com/a/21335440/6068036).

### Code

```python
import dash
import dash_bootstrap_components as dbc

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])
app.layout = dbc.Fade(
    [
        dbc.Row(
            "Some text",
            id="tooltip-target",
        ),
        dbc.Tooltip(
            "Tooltip still appears",
            target="tooltip-target",
        ),
    ],
    is_in=False,
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

### Error messages

No errors, but you can still hover over the faded row and see the tooltip:

![image](https://user-images.githubusercontent.com/10762127/110361018-73c2ab80-800d-11eb-8bc0-cd8c63b58e1a.png)

**Comment by tcbegley** [comment]
Thanks @amarvin,

I think this one will require checking whether the issue is one with Reactstrap or our usage of their components then possible submitting a fix upstream. Will look into it.

**Comment by tcbegley** [comment]
Turns out it's easy enough to fix this in the component itself, so have done so in #535

**Comment by amarvin** [comment]
Wow, thanks for merging a fix so quickly! Are you sure that the fade animation will still occur with your fix though? Looks like `visibility:hidden` takes effect immediately.

**Comment by tcbegley** [comment]
Hey @amarvin 

Sorry for being a bit slow to get back to you. I think you're right, let me look into that a bit more carefully.

**Comment by tcbegley** [comment]
I think this is all resolved now. Thanks for your attention to detail! I've made a pre-release with which you can try out the changes

```
pip install dash-bootstrap-components==0.11.4rc3
```

And here's a minimal example showing the changes

```python
import dash
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output, State

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Button("Toggle", id="button"),
        dbc.Fade(
            [
                html.P("Some text", id="tooltip-target"),
                dbc.Tooltip(
                    "Tooltip doesn't appear when faded",
                    target="tooltip-target",
                ),
            ],
            id="fade",
            is_in=False,
            # slow transition soo we can see the fade animation
            style={"transition": "opacity 1000ms ease-in-out"},
            timeout=1000,
        ),
    ]
)


@app.callback(
    Output("fade", "is_in"),
    [Input("button", "n_clicks")],
    [State("fade", "is_in")],
)
def toggle(n, is_in):
    if n:
        return not is_in
    return is_in


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by amarvin** [comment]
You're amazingly fast! No need to appologize. Thanks for the pre-release! It works perfectly.
