### ISSUE TITLE
No "required" attribute for Input?

### ISSUE THREAD

**Issue by youyanggu** [facultyai/dash-bootstrap-components#551]
In the [documentation](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/input/) for dbc.Form, there is no "required" attribute, making it difficult to use in practice. Using minLength doesn't work because the form is still valid if minLength=0. For example, dcc.Form supports the "required" attribute. Any workaround would be appreciated - thanks!

**Comment by tcbegley** [comment]
Hey @youyanggu 

I've added this in #552 and made a pre-release with the change. Once merged it will make it into the next full release.

```
pip install dash-bootstrap-components==0.12.1a1
```

Does it do what you want?

Do you have some code that you can share to help me better understand how you would use this?

**Comment by youyanggu** [comment]
Wow - thank you for your super quick response! Yes, this looks exactly like what I am looking for. I have a contact form that requires a name, email and message so this would be very helpful.

See code below. I would be able to replace "dcc.Input" with "dbc.Input". Thank you!

```python
html.Form([
    dbc.FormGroup([
        dbc.Label('Name'),
        dcc.Input(type='text', name='name', required=True),
    ]),
    dbc.FormGroup([
        dbc.Label('Email'),
        dcc.Input(type='text', name='email', required=True),
    ]),
    dbc.FormGroup([
        dbc.Label('Message'),
        dbc.Textarea(name='message', rows=5, cols=50, required=True),
    ]),
    dbc.Button('Submit', type='submit'),
], action='url', method='POST')
```

**Comment by tcbegley** [comment]
This is now available in the latest version

```
pip install -U dash-bootstrap-components
```
