### ISSUE TITLE
Value property for dbc.Button

### ISSUE THREAD

**Issue by klaska-lukas** [facultyai/dash-bootstrap-components#553]
Is it possible to add "value" property/keyword argument for dbc.Button? It is available in Dash html component html.Button. I use it for storing variables to trigger specific action based on context. Thank you.

_value (string; optional): Defines a default value which will be displayed in the element on page load._

**Comment by tcbegley** [comment]
Hey! Sorry for being slow to respond here, I've started working on this and I think we'll be able to add support in the next release.

**Comment by tcbegley** [comment]
This is now available in the latest version

```
pip install -U dash-bootstrap-components
```

**Comment by klaska-lukas** [comment]
Thank you. I'll give it a try

út 4. 5. 2021 v 9:56 odesílatel Tom Begley ***@***.***>
napsal:
