### ISSUE TITLE
Bootstrap v5 support

### ISSUE THREAD

**Issue by nirvana-msu** [facultyai/dash-bootstrap-components#559]
Any plans / timelines for supporting Bootstrap v5? Their final beta, `v5.0.0-beta3` was released [a month ago](https://blog.getbootstrap.com/2021/03/23/bootstrap-5-beta-3/), and there'd be no more breaking changes for sure. They'll likely release stable version very soon as well.

**Comment by tcbegley** [comment]
Hey,

Yes, the plan is to support it, but it very likely won't be as soon as it's released, basically for two reasons:
- This library is built on top of `reactstrap`, so we are blocked by them supporting v5 (this is [being worked on though](https://github.com/reactstrap/reactstrap/tree/bootstrap5)). We would also probably want to wait for Bootswatch to support v5 too.
- There are a small number of breaking changes in v5, such as the removal of the jumbotron component. I don't want to rush a release out that will break people's apps. We'll likely use Bootstrap 5 as an excuse to release v1 of dash-bootstrap-components, which will include creating a migration guide (which I don't think will be too complicated) and a public beta that I'll advertise on the forum and in the docs.

Not sure I want to put a timeline on all that. Probably it would happen this year? But I don't want to promise anything.

If you really want to use v5 immediately, you might be able to get reasonable results by simply linking a v5 stylesheet and using the existing library. While there are changes, a lot of the class names are remaining the same.

**Comment by nirvana-msu** [comment]
Thanks for a detailed response, I'll try out simply swapping bootstrap for v5.

**Comment by tcbegley** [comment]
Full support for Bootstrap 5 is available in the first v1 beta

```
pip install dash-bootstrap-components==1.0.0b1
```
