### ISSUE TITLE
dbc.Spinner debounce rendering

### ISSUE THREAD

**Issue by pmkroeker** [facultyai/dash-bootstrap-components#560]
It would be nice to add some form of debounce to the rendering of the spinner. When the spinner is used on top of a large set of components (ie total page view), every time anything is updated the loading spinner appears. On initial page load this can cause the spinner the appear and disappear many times, which is not a great user experience for a dashboard. Adding some form of either configurable debounce duration, or max call number would help reduce the flickering.

**Comment by tcbegley** [comment]
Hey @pmkroeker 

I will take a look into this, but most of the loading functionality is actually handled by Dash, not us. See [this line](https://github.com/facultyai/dash-bootstrap-components/blob/416f13054f2ef4263c66aa78a4871a6f2c96fbd0/src/components/Spinner.js#L106) that declares the spinner as a loading component. As you suggest though it might be possible for us to add a short delay in responding to the loading status of the children.

**Comment by tcbegley** [comment]
Hey again @pmkroeker 

I had a look into this and I've had a go at implementing the requesting debounce functionality in #561. It adds a `debounce` prop which accepts a time (in ms) which is used to delay the dismissal of the spinner.

I've made a pre-release containing the changes. It would be great to know if it resolves your problem, I only mocked up a fairly simple test app while developing.

You can install with 

```
pip install dash-bootstrap-components==0.12.1a2
```

For reference, here is the simple app I tested with

```python
import dash
import dash_bootstrap_components as dbc
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Spinner(dbc.Card(id="card", body=True), debounce=1000),
        dbc.Button("Trigger", id="trigger"),
    ],
    className="p-5",
)


@app.callback(Output("card", "children"), Input("trigger", "n_clicks"))
def callback(n):
    return "Card contents!"


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by pmkroeker** [comment]
Cool! I'll take a look! Thanks for the quick response!

**Comment by tcbegley** [comment]
Ah interesting, that wasn't something I noticed in my simple example. I think I was trying to avoid the spinner appearing if it wasn't necessary. I'll take another pass at it in the next few days.

**Comment by tcbegley** [comment]
Actually, @pmkroeker if you are able to share some version of your code or an example that reproduces the issue you were having that would be very helpful for me when testing potential fixes.

**Comment by pmkroeker** [comment]
I can't share our existing application, but I may be able to create an example. We have a number of charts that are all generated at the start which is likely causing the delays.

**Comment by pmkroeker** [comment]
I created a small example [here](https://github.com/pmkroeker/dbc-spinner-debounce), that unfortunately (for me) was unable to replicate the problem. I believe the delayed rendering of the Spinner in our app is due to a large number of callbacks that are being triggered when the app is loading.

Might be a bit tricky to reproduce the issue without making a large scale application.

**Comment by tcbegley** [comment]
> Might be a bit tricky to reproduce the issue without making a large scale application.

Yeah I had the same concern. If you don't mind then I might try a couple different things, make pre-releases for each of them and ask you to test on your big app?

**Comment by pmkroeker** [comment]
Sounds good to me!

**Comment by tcbegley** [comment]
Hey @pmkroeker 

I've made some further changes:
- Previously the debounce timer wasn't cleared if the loading state changed, which means the spinner might have been cleared early if the loading state was changing a lot
- The default is now to show the spinner initially before the loading state has been determined
- ... but that can be changed by setting `show_initially=False` in the `Spinner`. Default is `True`.

You can try it out with

```
pip install dash-bootstrap-components==0.12.1a4
```

Please do let me know if it helps with your app, seems to be working well on my simple examples.

```python
import dash
import dash_bootstrap_components as dbc
from dash.dependencies import Input, Output

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Spinner(
            dbc.Card(id="card", body=True), debounce=1000, show_initially=True  # show_initially is True by default
        ),
        dbc.Button("Trigger", id="trigger"),
    ],
    className="p-5",
)


@app.callback(Output("card", "children"), Input("trigger", "n_clicks"))
def callback(n):
    return "Card contents!"


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by pmkroeker** [comment]
Awesome! Sounds like it should, I'll take a look when I can.

**Comment by pmkroeker** [comment]
Just tried it out! Works super well now! Thanks!

**Comment by tcbegley** [comment]
Thanks for your help testing! The changes are now available in the latest release

```
pip install -U dash-bootstrap-components
```
