### ISSUE TITLE
dbc.Button defaults to type='submit'

### ISSUE THREAD

**Issue by jarvas24** [facultyai/dash-bootstrap-components#562]
- dash version: `1.20.0`
- dash-bootstrap-components version: `0.12.0`
- components affected by bug: `dbc.Button`

### What is happening?
dbc.Button components appear to set `type='submit'` by default

### What should be happening?
Documentation for dbc.Button does not specify a default type; My assumption is that `type='button'` is the intended default

### Minimal Example
Without setting the button's `type` argument in this example, pressing enter while the `dbc.Input` component is in focus triggers a button click. This behavior would be unexpected in most scenarios, and is avoided by explicitly setting `type='button'`

```python
import dash
from dash.dependencies import Input, Output
import dash_html_components as html
import dash_bootstrap_components as dbc

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    dbc.Alert("Hello Bootstrap!", color="success"),
    className="p-5",
)

app.layout = html.Div(
    [
        dbc.Form(
            [
                dbc.Input(id='input'),
                dbc.Button('Click Me', id='button')
            ],
            inline=True, className='my-3'
        ),
        html.Div(id='output_div')
    ],
    className='mx-4'
)

@app.callback(
    Output('output_div', 'children'),
    [Input('button', 'n_clicks')]
)
def handle_click(n_clicks):
    return f"button has been clicked {n_clicks or 0} times"


app.run_server(debug=True)
```

**Comment by tcbegley** [comment]
Hey, thanks for reporting this. I agree default type of "button" would make more sense. Will look into it and make a fix in the next release.

**Comment by tcbegley** [comment]
Hey @jarvas24 

I looked into this a bit more and it seems that `type="submit"` is actually the default in HTML, see [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) for example. For that reason I think I'd prefer to stick with convention, even if this is unexpected behaviour for some. As you point out, you can still manually override this behaviour if you wish.

If you find yourself writing `type="button"` a lot you could always write your own class to change the default, something like (untested):

```python
class MyButton(dbc.Button):
    def __init__(self, children=None, type="button", **kwargs):
        super().__init__(children, type=type, **kwargs)
```

**Comment by jarvas24** [comment]
Hi @tcbegley, thanks for looking into this. Given that this is default HTML behavior, I agree with you that no change to dbc.Button's behavior is necessary.

However, it might be worth updating the docs for dbc.Button? The current description of the `type` kwarg doesn't specify a default:
> `type (a value equal to: 'button', 'reset', 'submit', optional): The default behavior of the button. Possible values are: button, reset, submit`

I think something like this would be helpful: 
`type (a value equal to: 'button', 'reset', 'submit', optional): The default behavior of the button. Possible values are: button, reset, submit. Default: 'submit' if in a dbc.Form, else 'button' `

**Comment by tcbegley** [comment]
Great suggestion, will add that now.

**Comment by tcbegley** [comment]
This is now updated in version `0.12.1`

```
pip install -U dash-bootstrap-components
```
