### ISSUE TITLE
Multi-progress bar not displaying. 

### ISSUE THREAD

**Issue by anaisrv** [facultyai/dash-bootstrap-components#571]
Before opening:

- [Search for duplicate or closed issues](https://github.com/facultyai/dash-bootstrap-components/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/facultyai/dash-bootstrap-components/blob/main/.github/CONTRIBUTING.md)

Please fill out the below information as much as possible.

- dash version: `#1.19.0`
- dash-bootstrap-components version: `#0.12.0`
- components affected by bug: Progress

### What is happening?

Empty progress bar displaying when multi-bar sample code is used, other Bootstrap elements load in a working app without issues. 
![image](https://user-images.githubusercontent.com/32648183/117050664-d74a1c00-acd2-11eb-8bf0-6cfab7969510.png)
This is also apparent in the documentation. 
![image](https://user-images.githubusercontent.com/32648183/117050715-eb8e1900-acd2-11eb-91b6-6375385e3b90.png)

### What should be happening?

Progress bar should be tiered with three different progress bar colors ("success", "warning", "danger"), all at values greater than or equal to 20. 

### Code

```python
import dash_bootstrap_components as dbc

"""Insert necessary imports"""
progress = dbc.Progress(
    [
        dbc.Progress(value=20, color="success", bar=True),
        dbc.Progress(value=30, color="warning", bar=True),
        dbc.Progress(value=20, color="danger", bar=True),
    ],
    multi=True,
)
"""Load app here"""
```

### Error messages

```bash
paste any error messages here
```

**Comment by tcbegley** [comment]
Thanks for raising this. A combination of our tests having a gap in them and CI / CD not installing precise versions of dependencies when building the package seem to be the reason this was missed. Working on a fix and will likely make a patch release.

**Comment by tcbegley** [comment]
Just pushed a new release that resolves this, just update dash-bootstrap-components and everything should work again.

```
pip install -U dash-bootstrap-components
```
