### ISSUE TITLE
Dash dev tools and Dash bootstrap dark themes

### ISSUE THREAD

**Issue by vikigenius** [facultyai/dash-bootstrap-components#583]
Please fill out the below information as much as possible.

- dash version: `#1.20.0`
- dash-bootstrap-components version: `#0.12.2`
- components affected by bug: Dev Tools

### What is happening?

When using a Dark theme such as DARKLY or by following https://github.com/facultyai/dash-bootstrap-components/pull/147 and using the custom style sheets provided in https://github.com/tcbegley/dash-bootstrap-css the DEV tools for example when showing errors has very poor contrast.

![scrot_20210516_142357](https://user-images.githubusercontent.com/12724810/118408180-600d7400-b652-11eb-85f8-568c5779be01.png)

### What should be happening?

DEV tools should have better contrast.

How do I fix this ?

**Comment by tcbegley** [comment]
Hey, thanks for raising this. I think this will be a problem more broadly with any dark theme that globally sets the font color to white or something light. I think the best thing would be to raise an issue / submit a fix to Dash itself. It looks like they set the background color of the debug menu but aren't seeing the text color. I'm happy to do that but it will probably be a couple of days before I have a chance to do so.

**Comment by vikigenius** [comment]
Done: https://github.com/plotly/dash/issues/1649

**Comment by AnnMarieW** [comment]
FYI - This will be fixed in the next release of Dash 
https://github.com/plotly/dash/pull/1664 was just merged. :confetti_ball:

**Comment by tcbegley** [comment]
Closing this as it will be resolved by the next version of Dash.
