### ISSUE TITLE
dbc.input on Firefox 88.0.1 (64-bit)

### ISSUE THREAD

**Issue by jeremyfox36** [facultyai/dash-bootstrap-components#586]
Please fill out the below information as much as possible.

- dash version: `1.20.0`
- dash-bootstrap-components version: `0.12.2`
- components affected by bug: input(type="number"

### What is happening?

The up down arrows aren't clickable on Firefox - the pointer changes to a text selector.  I can still type in the input box though and the arrows work fine in Chrome.

### What should be happening?

Hovering over the up/down arrows should change the pointer to an arrow and clicking should result in incrementing the input box value.

### Code

```python
import dash
import dash_html_components as html
import dash_bootstrap_components as dbc

app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div(
    [
        dbc.Input(type="number"),
    ],
    className="container",
)


if __name__ == "__main__":
    app.run_server()
`

**Comment by AnnMarieW** [comment]
Quick follow-up:  I could reproduce the problem.  The arrow keys work in Chrome but not in Firefox.  

I also noticed that with Firefox, the number increments if you use keyboard arrow keys (but not if you click on the arrow keys in the input box).

Also, if you set the `step` it works in Firefox, for example:
    `dbc.Input(type="number", step=1),`
This could be a work-around until a better solution is found

**Comment by jeremyfox36** [comment]
Thanks for the quick reply 👍 
The keyboard arrow keys work for me in FF, but even when I set the step size the input box arrow buttons don't respond. 
I accidentally discovered that if I click the far right hand side of the buttons, they work.  The sweet spot seems to be from the right hand button border to about 2 or 3 pixels inside the button.  This works with or without setting the step size.

Seems like it might be something to do with the size of the inner text box.

**Comment by AnnMarieW** [comment]
Right - I saw this as a solution and when I tried it, my aim must have been better!  It would have been a nice workaround.

**Comment by jeremyfox36** [comment]
Seems like the recent Firefox update has fixed this issue.  All works fine on version 89.0 (64bit)
