### ISSUE TITLE
Missing styling for DatePickerSingle and DatePickerRange

### ISSUE THREAD

**Issue by stlehmann** [facultyai/dash-bootstrap-components#590]
- dash version: `1.20.0`
- dash-bootstrap-components version: `0.12.2`
- components affected by bug: DatePickerSingle, DatePickerRange

### What is happening?

DatePickerSingle and DatePickerRange objects don't seem to get styled by dbc themes anymore as stated in #43. 

### What should be happening?

The DatePickerSingle object should be styled according to the used theme as stated in #43. As I read it the DatePickerSingle and DatePickerRange components were removed from the dbc package. But the stylesheets are meant to support these components.

### Code
```python
from dash import Dash
import dash_bootstrap_components as dbc
import dash_core_components as dcc
import dash_html_components as html


app = Dash(__name__, external_stylesheets=[dbc.themes.DARKLY])

app.layout = dbc.Container([
    dbc.Form([
        dbc.FormGroup([
            dbc.Label("Datum:"),
            dcc.DatePickerSingle(),
        ]),
    ]),
])

app.run_server(debug=True)

```

The result looks like this:

![grafik](https://user-images.githubusercontent.com/4641542/120435998-ab2bc480-c37e-11eb-8fe6-a0965327f3cd.png)

According to #43 it should actually look like this:

![grafik](https://user-images.githubusercontent.com/4641542/120436094-c8609300-c37e-11eb-9111-126354cf4db3.png)

**Comment by tcbegley** [comment]
Hey @stlehmann 

We removed the date picker components from the library as they were duplicating functionality in dash-core-components, and also represented about 2/3 of the JS bundle size for dash-bootstrap-components.

Bootstrap CSS itself won't restyle the date picker components, but you can try out tcbegley/dash-bootstrap-css which contains extended stylesheets that _do_ restyle the DatePicker components.

**Comment by stlehmann** [comment]
@tcbegley thanks for coming back to me. I just tried dash-bootstrap-css and it works like a charm.
As a suggestion: Maybe we could add a section in the FAQ to point people struggling with the same thing.

**Comment by tcbegley** [comment]
Good idea, I thought it was mentioned on the themes documentation but it appears not. Will add a link.

**Comment by stlehmann** [comment]
Great 👍, thanks again for the intel. I'll close the issue.

**Comment by supernyv** [comment]
> Hey @stlehmann
> 
> We removed the date picker components from the library as they were duplicating functionality in dash-core-components, and also represented about 2/3 of the JS bundle size for dash-bootstrap-components.
> 
> Bootstrap CSS itself won't restyle the date picker components, but you can try out [dash-bootstrap-css](https://github.com/tcbegley/dash-bootstrap-css) which contains extended stylesheets that _do_ restyle the DatePicker components.

Hi @tcbegley ,

Any plan to bring a date picker component back in dbc? 
I have been working on dash apps for a long time and always use dbc, but the date picker is an important feature I think is missing from this major dash library

**Comment by tcbegley** [comment]
Hey @supernyv, 

Unlikely to add something I'm afraid, basically because

- There is no official bootstrap DatePicker that I am aware of, so creating a component that is compatible with all bootstrap stylesheets is hard
- The previous DatePicker we had was based on the dcc one and increased the bundle size quite significantly but with no additional features other than some styling
