### ISSUE TITLE
Collapse always open

### ISSUE THREAD

**Issue by dhetting** [facultyai/dash-bootstrap-components#592]
- dash version: `1.20.0`
- dash-bootstrap-components version: `#0.12.2`
- chrome version: `91.0.4472.77`
- OSX version: `10.15.7`
- components affected by bug: Collapse

### What is happening?

Collapse is always open.

### What should be happening?

Collapse should close.

### Code

```python
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output, State
from dash import Dash

app = Dash(prevent_initial_callbacks=True)
app.layout = html.Div(
    [
        dbc.Button(
            "Open collapse",
            id="collapse-button",
            className="mb-3",
            color="primary",
        ),
        dbc.Collapse(
            dbc.Card(dbc.CardBody("This content is hidden in the collapse")),
            id="collapse",
            is_open=False
        ),
    ]
)


@app.callback(
    Output("collapse", "is_open"),
    [Input("collapse-button", "n_clicks"),
    State("collapse", "is_open")]
)
def toggle_collapse(n, is_open):
    if n:
        return not is_open
    return is_open


if __name__ == '__main__':
    app.run_server(port=8042, debug=True)

```

The live example is working just fine, but I can't reproduce it locally. The content is never hidden, before or after clicking the button: 
![image](https://user-images.githubusercontent.com/89405/121233225-a91aa780-c84f-11eb-9652-1852e25ce5b8.png)

**Comment by AnnMarieW** [comment]
Hi @dhetting 

Be sure to include a Bootstrap stylesheet, for example:

```

app = Dash(__name__, prevent_initial_callbacks=True, external_stylesheets=[dbc.themes.BOOTSTRAP])


```

**Comment by tcbegley** [comment]
Thanks @AnnMarieW!
