### ISSUE TITLE
Reduce the bundle size

### ISSUE THREAD

**Issue by pbugnion** [facultyai/dash-bootstrap-components#60]
The generated bundle is fairly big. I think this is because we include parts of modules that we don't need.

I don't think this is urgent at all, but if we can, it might be worth spending some time understanding how to reduce the bundle size.

**Comment by tcbegley** [comment]
I believe #148 should help with this.

**Comment by pbugnion** [comment]
Definitely. I haven't tested this, but I have a hunch that we can also reduce the bundle size considerably by replacing blanket imports of *ramda* with more targeted imports.

See e.g. https://github.com/ramda/ramda#usage.

**Comment by tcbegley** [comment]
#159 reduced the bundle size to about a third of what it was. At 268KB it's still slightly above the recommended limit of 244KB, but perhaps that's fine? There may be some scope to reduce a bit further.

**Comment by pbugnion** [comment]
I think the current bundle is fine. I think there's still some value in reading around how to manage the bundle size, but it's probably OK for now.

Happy to close this if you want.

**Comment by tcbegley** [comment]
Agreed, happy for you to close this
