### ISSUE TITLE
Fix README for GitHub dark mode

### ISSUE THREAD

**Issue by tcbegley** [facultyai/dash-bootstrap-components#600]
Logo is hard to see properly and screenshots don't look great.

**Comment by lucasilvalves** [comment]
This issue is 2 years old and the readme still looks the same... 😮‍💨

**Comment by tcbegley** [comment]
Yeah, unfortunately haven't had the time to sort this out and it's low priority since I don't think it prevents you reading anything, it just doesn't look super pretty.

Contributions welcome if you want to take a stab at it 😁
