### ISSUE TITLE
Add multi select option for dbc.Select similar to dcc.Dropdown multi = True

### ISSUE THREAD

**Issue by imsinger** [facultyai/dash-bootstrap-components#603]
It would be great to have a multi select version of the Select component similar to what is available for the dcc.Dropdown.

Dash components dont act that well with InputGroups in bootstrap but multi select requirements force you to use the dash core component option.

**Comment by tcbegley** [comment]
Unfortunately this isn't really possible, see #510 

You could try the CSS in [this repo](https://github.com/tcbegley/dash-bootstrap-css) which might make the multi dropdown work a bit better inside the `InputGroup`? Not sure how well that will work though.
