### ISSUE TITLE
Button: add support for defining `title` property at creation time

### ISSUE THREAD

**Issue by jouvin** [facultyai/dash-bootstrap-components#610]
I have an application where I defined the button `title` property (text displayed when hovering over the button) in a callback and it works well. Would it be possible to add support for defining it at creation time with a `title` argument?

```
dash                      1.20.0             pyhd8ed1ab_0    conda-forge
dash-bootstrap-components 0.12.0             pyhd8ed1ab_0    conda-forge
```

**Comment by tcbegley** [comment]
Hey @jouvin 

Sure, that would be pretty simple to add, it's just a matter of exposing the `title` prop in the implementation of `dbc.Button`. In the meantime you can either continue to use your workaround or perhaps try `dbc.Tooltip` as an alternative?

Btw, the fact that you can update properties that aren't exposed by the Dash components using a callback seems pretty surprising to me. Not sure if that's a bug in Dash.

**Comment by jouvin** [comment]
Thanks @tcbegley ! You are right, I could have used a `dbc.Tooltip`, forgot about it (despite I used it other part of the app), but found handy that it was just an additional property for the button.

**Comment by jouvin** [comment]
I read quiclly https://github.com/plotly/dash/issues/1673 and I am not sure if it has an impact but the `title` property is exposed by the `dcc.Button` (it is where I found information about it!). So may be the `dbc.Button` is based on it and no error is raised as it is a valid keyword for it. Even though the check you did demonstrates that it would also work with any keyword if you are not running in debug mode (which is not my case as I always develop in debug mode).

**Comment by tcbegley** [comment]
This is now resolved in the latest version of dash-bootstrap-components
