### ISSUE TITLE
Adding how to sort a table in the documentation

### ISSUE THREAD

**Issue by jouvin** [facultyai/dash-bootstrap-components#611]
I use the `dbc.Table` in an application where I need to build complex tables, with components like switches and accordions in some cells making `dash-table` not usable. I wanted to implement the possibility to sort the table by different columns, clicking on the column header as it is implemented in `dash-table`. Digging to find a solution, I found the `sorttable` JS small library dedicated to this and easy to integrate into a Dash application. If you consider that it could be useful, I'm happy to document it somewhere in the DBC documentation... just tell me where and how to proceed (a PR?).

**Comment by tcbegley** [comment]
Sounds interesting, perhaps it would be a good candidate for an example in `examples/advanced-component-usage`? Would be interested to take a look and see how it works in any case.

**Comment by jouvin** [comment]
Ok, I have an example that I used to get it working, I'll add it.
