### ISSUE TITLE
where is dash_bootstrap_components._components.py

### ISSUE THREAD

**Issue by oegedijk** [facultyai/dash-bootstrap-components#613]
Hi there,

Short stupid question: I'm going through the source code and notice that in `dash_bootstrap_components/__init__.py` you
import a module called `_components`:

```python
from dash_bootstrap_components import _components
from dash_bootstrap_components._components import *  # noqa
```
 
However I don't see this module anywhere in the repo? Does it somehow magically get inserted somewhere?

**Comment by tcbegley** [comment]
Hey @oegedijk 

Good question. These files are automatically generated from the JS files in `src/`, and hence we do not keep them under version control (to avoid large diffs and keep the repo size smaller, but also to make sure nobody tried to edit files that would be automatically overidden).

If you want to generate them yourself and take a look you can follow the instructions [here](https://github.com/facultyai/dash-bootstrap-components/blob/main/.github/CONTRIBUTING.md#building-dash-bootstrap-components-locally). Alternatively download [a tarball from PyPI](https://pypi.org/project/dash-bootstrap-components/#files) and extract it to see the source that gets installed when you install with `pip`.

**Comment by oegedijk** [comment]
Ah, cheers! So it was generated automagically! Thanks a lot!
