### ISSUE TITLE
NavbarSimple - how to push nav-items to the left? 

### ISSUE THREAD

**Issue by lambdamusic** [facultyai/dash-bootstrap-components#615]
Hey there. I'm trying to get the Nav-Items in the NavbarSimple component to align on the left hand side, but can't get it to work. Wonder if anyone had the same issue.

By default, Nav-Items elements all stick to the right. E.g. using the code from `the docs`: 

```
import dash_bootstrap_components as dbc

navbar = dbc.NavbarSimple(
    children=[
        dbc.NavItem(dbc.NavLink("Page 1", href="#")),
        dbc.DropdownMenu(
            children=[
                dbc.DropdownMenuItem("More pages", header=True),
                dbc.DropdownMenuItem("Page 2", href="#"),
                dbc.DropdownMenuItem("Page 3", href="#"),
            ],
            nav=True,
            in_navbar=True,
            label="More",
        ),
    ],
    brand="NavbarSimple",
    brand_href="#",
    color="primary",
    dark=True,
)
```

Looking at the rendered HTML, I can see that removing the `ml-auto` class from the `ul` element achieves what I want.. however, I can't figure out how to express that in Python Dash... 

![image](https://user-images.githubusercontent.com/3493663/123783094-e7930780-d8cd-11eb-957d-5a2759f3d98c.png)

**Comment by tcbegley** [comment]
Hey @lambdamusic 

Thanks for raising this, there's a property `links_left` that looks like it was never exposed to the user that was meant to allow you to configure this. Should be a relatively easy fix.

In the meantime, you can use a regular `Navbar` for this, which is a bit more manual but should get you what you want.

```python
import dash
import dash_bootstrap_components as dbc

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Navbar(
    dbc.Container(
        [
            dbc.NavbarBrand("Navbar", href="#"),
            dbc.Nav(
                [
                    dbc.NavItem(dbc.NavLink("Page 1", href="#")),
                    dbc.DropdownMenu(
                        children=[
                            dbc.DropdownMenuItem("More pages", header=True),
                            dbc.DropdownMenuItem("Page 2", href="#"),
                            dbc.DropdownMenuItem("Page 3", href="#"),
                        ],
                        nav=True,
                        in_navbar=True,
                        label="More",
                    ),
                ],
                className="mr-auto",
                navbar=True,
            ),
        ]
    ),
    color="primary",
    dark=True,
)


if __name__ == "__main__":
    app.run_server(debug=True)
```

Check out the other examples [here](https://github.com/facultyai/dash-bootstrap-components/blob/fc8603271b03ee54b97750d645ecf56a01c24ee0/examples/advanced-component-usage/Navbars.py) for more advanced behaviour.

**Comment by lambdamusic** [comment]
Thanks @tcbegley and sorry for the late reply. The solution works just fine!
