### ISSUE TITLE
Want to add a function to add hyperlinks to elements in a column of the table

### ISSUE THREAD

**Issue by limmyforget** [facultyai/dash-bootstrap-components#623]
Want to add a function to add hyperlinks to elements in a column of the table

**Comment by tcbegley** [comment]
Not really sure what you're asking. If you can give some more information / clarify your question I'll do my best to help.

**Comment by astrowonk** [comment]
@limmyforget I think you mean wrapping a link around the text inside a table cell. I've just released/generalized some code that does this by grabbing the url from another matched column. see [https://github.com/astrowonk/dash_dataframe_table](my github repo) or a [live demo](https://marcoshuerta.com/dash/table_example/).

Right now I subclass `dbc.Table` which may not be the best idea, I have a branch where a patch another class method onto dbc.Table which gets the same effect.
