### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by balodja** [facultyai/dash-bootstrap-components#624]
- dash version: `#1.19.0`
- dash-bootstrap-components version: `#0.12.2`
- components affected by bug: all

### What is happening?

I'm trying to pack `dash-bootsrap-components` for NixOS, but I definitely don't understand what's going on with the main module. Unable to import `dash_bootstrap_components`.

### What should be happening?

Obviously, it should be importable.

### Code

```python
$ python
Python 3.8.9 (default, Apr  2 2021, 11:20:07) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dash_bootstrap_components
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/1qmbzcl52zql8iilzn4x9qjhzwjgkwv3-python3-3.8.9-env/lib/python3.8/site-packages/dash_bootstrap_components/__init__.py", line 6, in <module>
    from dash_bootstrap_components import _components
ImportError: cannot import name '_components' from partially initialized module 'dash_bootstrap_components' (most likely due to a circular import) (/nix/store/1qmbzcl52zql8iilzn4x9qjhzwjgkwv3-python3-3.8.9-env/lib/python3.8/site-packages/dash_bootstrap_components/__init__.py)
```

### System information
```
 > nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.48, NixOS, 21.05.1493.1f4e50f03c5 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.05.1493.1f4e50f03c5"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by balodja** [comment]
Looking at the [code](https://github.com/facultyai/dash-bootstrap-components/blob/541f9c86556551dcde6e7362ec5cedb211023704/dash_bootstrap_components/__init__.py#L6) I don't understand why in the world there should not be circular dependencies.

**Comment by balodja** [comment]
I see the problem now. Before doing `setup.py` building and installation we should generate components with `invoke setup-py`. There should be a paragraph in README with instructions for installation from sources.

**Comment by tcbegley** [comment]
Hey! Thanks for raising this. 

You're right the issue is that generated files are not kept under version control. There are some instructions in [CONTRIBUTING.md](https://github.com/facultyai/dash-bootstrap-components/blob/main/.github/CONTRIBUTING.md#building-dash-bootstrap-components-locally), but I think I agree that it would make sense to link to this from the main README.md
