### ISSUE TITLE
Input masking for dbc.Input

### ISSUE THREAD

**Issue by tmcf2775** [facultyai/dash-bootstrap-components#637]
Hi All,

Would like to request that input masking be made available for dbc.Input. I am building a dash for financial data, where millions and billions are usual numbers to enter. However, in the input box it is very hard to discern the size. If possible, would like to make use of the underlying masking capabilities of HTML, as shown here. Please let me know if this is possible?

https://css-tricks.com/input-masking/

**Comment by tcbegley** [comment]
Hi @tmcf2775 

Thanks for the suggestion. I think it would be a great addition, but unfortunately it seems it's a hard problem to solve with the way Dash works. This has actually been a [long standing issue](https://github.com/plotly/dash-core-components/issues/670) on the dash-core-components repo. If there's a way to do it then I'd be happy to add it, but it's not clear to me at the moment how we would do it.

**Comment by tmcf2775** [comment]
Hi @tcbegley 
Thanks for the reply. Hopefully one day it can be solved !

**Comment by tcbegley** [comment]
Closing this for now. If dash-core-components solves the problem in the future we'll work on keeping feature parity, but unless that happens we don't really have the resources to investigate a fix here. Sorry, it would be a cool feature.
