### ISSUE TITLE
Carousel don't work

### ISSUE THREAD

**Issue by AY-TRAD** [facultyai/dash-bootstrap-components#639]
Before opening:

- [Search for duplicate or closed issues](https://github.com/facultyai/dash-bootstrap-components/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/facultyai/dash-bootstrap-components/blob/main/.github/CONTRIBUTING.md)

Please fill out the below information as much as possible.

- dash version: `#x.x.x`
- dash-bootstrap-components version: `#x.x.x`
- components affected by bug:

### What is happening?

AttributeError: module 'dash_bootstrap_components' has no attribute 'Carousel'

### What should be happening?

dbc.Carousel(
                items=[
                    {"key": "1", "src": "/static/images/slide1.svg"},
                    {"key": "2", "src": "/static/images/slide2.svg"},
                    {"key": "3", "src": "/static/images/slide3.svg"},
                ],
                className="carousel-fade",
            )

```python
# your code here
```

### Error messages

```bash
paste any error messages here
```

**Comment by AnnMarieW** [comment]
Hi @AY-TRAD Try upgrading to the latest version of dash-bootstrap-components V 0.13.0

**Comment by AY-TRAD** [comment]
Thanks, but wish command I can use ?

**Comment by AY-TRAD** [comment]
it's working, Thanks
