### ISSUE TITLE
Brocken link on the Navbar docs

### ISSUE THREAD

**Issue by SamEdwardes** [facultyai/dash-bootstrap-components#641]
### What is happening?

The link to the `examples/` directory is broken in the Navbar docs page: https://dash-bootstrap-components.opensource.faculty.ai/docs/components/navbar/

![Screen Shot 2021-08-12 at 8 28 31 PM](https://user-images.githubusercontent.com/18248949/129300999-f2dd69ef-b664-4015-8c1f-8f45d8b3034b.png)

### What should be happening?

The current link is:

https://github.com/facultyai/dash-bootstrap-components/blob/main/examples/advanced-component-usage/Navbars.py

I think the correct link is: 

https://github.com/facultyai/dash-bootstrap-components/blob/main/examples/python/advanced-component-usage/navbars.py

**Comment by tcbegley** [comment]
Thanks! This had been updated in the source but I hadn't redeployed the docs 😖 

Should be fixed now.
