### ISSUE TITLE
Re-enable direction=up on dropdowns

### ISSUE THREAD

**Issue by pbugnion** [facultyai/dash-bootstrap-components#65]
In issue #62 and PR #64 , we decided to disable opening dropdowns with `direction="up"` until Dash renderer supports React 16.

**Comment by tcbegley** [comment]
Closing this as it's being tracked by #142.

**Comment by tcbegley** [comment]
Reopening this, as with the release of Dash 0.41.0, individual issues for outstanding changes for React 16 make more sense than tracking everything through #142

**Comment by tcbegley** [comment]
Closed by #196
