### ISSUE TITLE
Migration Guide

### ISSUE THREAD

**Issue by AnnMarieW** [facultyai/dash-bootstrap-components#670]
> **This draft copy of the Migration  Guide is posted here to make it easier to update as we make progress on V1.**
--------

# Dash Bootstrap Components V1 Migration Guide

_dash-bootstrap-components_ v1.0 adds full compatibility with Bootstrap 5. Since Bootstrap 5 is a major rewrite, there are significant breaking changes when migrating from _dash-bootstrap-components_ v0.13.0 to v1.0.

For more information about the changes in Bootstrap 5, see the upstream [Bootstrap migration guide.](https://v5.getbootstrap.com/docs/5.0/migration) and the [Bootstrap 5 Documentation](https://getbootstrap.com/docs/5.0/layout/grid/).

## Dependencies

 _dash-bootstrap-components_ v1.0 requires Dash 2.0.0 or greater.  See the [Dash 2.0 migration guide](https://dash.plotly.com/dash-2-0-migration) for more details. 

## New Themes

Check out the three new themes: `Morph`, `Vapor` and `Zephyr`  in the [Theme Explorer](https://dash-bootstrap-components.opensource.faculty.ai/docs/themes/explorer/)

## Icons

Include Bootstrap and Font Awesome icons to your app as easily as adding a Bootstrap Theme.  There are two new links: `dbc.icons.BOOTSTRAP` and `dbc.icons.FONTAWESOME`.  See more information in the [Icons]() section of the docs and see an example in the [alerts]() section.

## Documentation Changes

The documentation has been updated to include the new components, new examples and is updated throughout to use the new Bootstrap 5 classes. Here are some of the highlights:
 - New Icons section to describe use of Bootstrap and Fontawesome icons in your app.
 - Added a new Component landing page to explain how to use the example code snippets. 
 - New components:
   - `Accordion`
   - `Breadcrumb`
   - `Offcanvas`
   - `Pagination`
   - `FloatingForm` - to create labels that floats over the form fields
   -  `Switch` - standalone toggle switch
 - New examples:
   - Alerts with Bootstrap icons
   - Badge text colors
   - Badge positioning relative to a button
   - Button: block size, responsive and flex layout, download
   - ButtonGroup mixed styles and outline
   - Card image overlay and horizontal style
   - DropdownMenu - added Dark example
   - Form added floating labels example
   - InputGroup multiple addons example
   - ListGroups flush and horizontal example
   - Jumbotron recreate this dropped component with Bootstrap utilities
   - Modal closing modal by pressing `esc` key
   - Modal with full screen display and toggling between Modals
   - Table colors
   - Table from Multi-index data frame   
   
 - The new default color for the Buttons is now `primary` rather than `secondary`.  This affects multiple examples in the documentation.

 - The Bootstrap 5 links are now underlined by default.  This was removed in several examples with `style={"textDecoration": "none"}` or `className="text-decoration-none"`   
   
## Accordion
 - Added new accordion component. 

## Badge
- **Breaking** The `color` property now only sets the background color.  Use the new `text_color` prop to change the color of the text. You’ll likely need to set a dark text color when using `color="light"`.
 
## Breadcrumb
 - Added new Breadcrumb component.

## Buttons
- **Breaking** The default color for the buttons is now `primary` rather than `secondary`.  This change was made to match the Bootstrap convention.

- **Breaking** Dropped `block` property.  Instead, wrap the buttons in a `html.Div` and use the Bootstrap utilities classes such as `"d-grid"` and a `"gap-*"` in the `className` to space the buttons as needed.  See the docs for examples.
- Disabled buttons now have `pointer-events: none` as a default.

## ButtonGroup
- **Breaking** The default color for the buttons is now `primary` rather than `secondary`.  This change was made to match the Bootstrap convention.

## Card
- **Breaking** Dropped `CardDeck` component. Use the Bootstrap grid classes to arrange the cards like a card deck.  See
the [Bootstrap grid docs](https://getbootstrap.com/docs/5.0/layout/grid/#row-columns) for more information.

- **Breaking** Dropped CardColumns component. CardColumns had many [issues in Bootstrap 4](https://github.com/twbs/bootstrap/pull/28922) and was dropped in Bootstrap 5.

## Carousel
- Added `dark` property for dark text, controls, and indicators. This is great for lighter backgrounds.
- Replaced chevron icons for carousel controls with new SVGs from Bootstrap Icons.

## Collapse
 - Removed the Accordion example since we now have a new Accordion component.
 - Dropped the `tag` property.

## DropdownMenu
- **Breaking** The default color for the buttons is now `primary` rather than `secondary`.  This change was made to match the Bootstrap convention.
- **Breaking** Changed the `direction` prop options from right and left to start and end to match the Bootstrap 5 convention.
- **Breaking** Changed the name of the `right` prop to `align_end`.
- **Breaking** Changed the name of the  `bs_size` property to  `size`. 
- Added `menu_variant` prop to make the dropdown menu a dark color scheme.

## Fade
 - **Breaking** Dropped `base_class` property.
 - **Breaking** Dropped `base_class_active` property.

## Form
  - **Breaking** Dropped FormGroup.  It is no longer necessary to use `FormGroup` to align components in a form.  Use `Row` `Col` and gutter modifier classes and spacing utilities instead.
  - Added `FormFloating` component to create a label that floats over the form field.   

### Input
 - **Breaking** Dropped `bs_size` property.  Use `size` instead. 
 - Added `html_size` property for the initial size of the control.

### TextArea
 - **Breaking** Dropped `bs_size` property.  Use `size` instead.
 
### Select
- **Breaking** Dropped `bs_size` property.  Use `size` instead.

### Standalone checkboxes and radio buttons
- **Breaking**  All new version of `Checkbox` and  `RadioButton`,  plus added new  `Switch` component. The new api makes it easier to create standalone versions of the checkboxes, radio buttons and toggle switches. See the documentation for more details and examples.

## InputGroup
 - **Breaking** Dropped `InputGroupAddon` component. It's not necessary to use `InputGroupAddon` because things like `Button`s and `InputGroupText` can be added to `InputGroup` as direct children.

## Jumbotron
 - **Breaking** Dropped the Jumbotron component.  The docs have an example of how to replicate it with Bootstrap utilities.

## Layout
- **Breaking** Dropped `no_gutters` prop.  Use gutter modifier classes instead.
- **Breaking**  When specifying the `order` of the columns, it accepts the integers 1,...,5,  only rather than integers 1,...,12.  

## ListGroup
- **Breaking** Dropped `ListGroupHeading` component.
- **Breaking** Dropped `ListGroupItemText` component.  
The `ListGroupHeading` and `ListGroupItemText` are unnecessary since you can pass any Dash components to the children of `ListGroupItem`.  See the updated code snippet "Custom Content" for an example. 
 

## Modal
- Added `fullscreen` property
- Added `keyboard` property to close model when escape key is pressed.  

## Nav
 - **Breaking** - Dropped `active` property in `NavItem` 
 - Added `navbar_scroll` Enable vertical scrolling within the toggleable contents of a collapsed Navbar.

## Navbar
 - **Breaking** - Navbars now require a container within. This simplifies spacing requirements and CSS required.

## Offcanvas
- Added the new offcanvas component.

## Pagination
- Added a new Pagination component

## Progress
 - **Breaking** Dropped `barClassName` property.  Use `className`
 - **Breaking** Dropped  `bar_style` property. Use `style`
 - **Breaking** Dropped `tag` property.
 - added a `label` property
 - added a `hide_label` property.

## Table
 - **Breaking** Dropped `tag` property.
 - Added `color` property.
 

## Tabs 
 - **Breaking** Dropped `card` property.  It's no longer necessary to set `card=True` to put tabs in a `Card`.

## Toast
- added `color` property to set the background color.
- **Breaking** Dropped `fade` property.

## Tooltip
- **Breaking** Dropped `arrowClassName`
- **Breaking** Dropped `autohide`
- **Breaking** Dropped `boundaries_element`
- **Breaking** Dropped `container`
- **Breaking** Dropped `hide_arrow`
- **Breaking** Dropped `innerClassName`
- **Breaking** Dropped `offset`

---------------------------
--------------------------
>
> **Question for Tom: Everything below is a summary of info from the Bootstrap Migration Guide that I think might be useful.  Should this section be dropped or moved somewhere else?  Or perhaps just link to the Bootstrap docs?**
> 
> 
## Bootstrap 5 Utilities

For your convenience, here is the summary of changes to the utility classes from the Boostrap 5 Migration docs. 
These can be used in the `className` property.  For example `className = "border-end"`

- **Breaking** Renamed several utilities to use logical property names instead of directional names with the addition of RTL support:

  - Renamed .left-* and .right-* to .start-* and .end-*.
  - Renamed .float-left and .float-right to .float-start and .float-end.
  - Renamed .border-left and .border-right to .border-start and .border-end.
  - Renamed .rounded-left and .rounded-right to .rounded-start and .rounded-end.
  - Renamed .ml-* and .mr-* to .ms-* and .me-*.
  - Renamed .pl-* and .pr-* to .ps-* and .pe-*.
  - Renamed .text-left and .text-right to .text-start and .text-end.

- **Breaking** Disabled negative margins by default.

- Added new .bg-body class for quickly setting the <body>’s background to additional elements.

- Added new position utilities for top, right, bottom, and left. Values include 0, 50%, and 100% for each property.

- Added new .translate-middle-x & .translate-middle-y utilities to horizontally or vertically center absolute/fixed positioned elements.

- Added new border-width utilities.

- **Breaking** Renamed .text-monospace to .font-monospace.

- **Breaking** Removed .text-hide as it’s an antiquated method for hiding text that shouldn’t be used anymore.

- Added .fs-* utilities for font-size utilities (with RFS enabled). These use the same scale as HTML’s default headings (1-6, large to small), and can be modified via Sass map.

- **Breaking** Renamed .font-weight-* utilities as .fw-* for brevity and consistency.

- **Breaking** Renamed .font-style-* utilities as .fst-* for brevity and consistency.

- Added .d-grid to display utilities and new gap utilities (.gap) for CSS Grid and flexbox layouts.

- **Breaking** Removed .rounded-sm and rounded-lg, and introduced a new scale of classes, .rounded-0 to .rounded-3. See #31687.

- Added new line-height utilities: .lh-1, .lh-sm, .lh-base and .lh-lg. See here.

- Moved the .d-none utility in our CSS to give it more weight over other display utilities.

- Extended the .visually-hidden-focusable helper to also work on containers, using :focus-within.

## Components
- Bootstrap changes: Unified padding values for alerts, breadcrumbs, cards, dropdowns, list groups, modals, popovers, and tooltips. This gives your components a more consistent look.

## Grid updates
 - **New breakpoint!**  Added new xxl breakpoint for 1400px and up. No changes to all other breakpoints.

 - **Improved gutters** Gutters are now set in rems, and are narrower than v4 (1.5rem, or about 24px, down from 30px). This aligns our grid system’s gutters with our spacing utilities.

   - Added new gutter class (.g-*, .gx-*, and .gy-*) to control horizontal/vertical gutters, horizontal gutters, and vertical gutters.
   - **Breaking** Renamed .no-gutters to .g-0 to match new gutter utilities.
 - Columns no longer have position: relative applied, so you may have to add .position-relative to some elements to restore that behavior.

 - **Breaking** Dropped several .order-* classes that often went unused. We now only provide .order-1 to .order-5 out of the box.

 - **Breaking** Dropped the .media component as it can be easily replicated with utilities. See #28265 and the flex utilities page for an example.

 - **Breaking** `bootstrap-grid.css` now only applies box-sizing: border-box to the column instead of resetting the global box-sizing. This way, our grid styles can be used in more places without interference.

 - `$enable-grid-classes` no longer disables the generation of container classes anymore. See #29146.

 - Updated the make-col mixin to default to equal columns without a specified size.

## Content, Reboot, etc
 - RFS is now enabled by default. Headings using the font-size() mixin will automatically adjust their font-size to scale with the viewport. This feature was previously opt-in with v4.

 - **Breaking** Overhauled our display typography to replace our $display-* variables and with a $display-font-sizes Sass map. Also removed the individual $display-*-weight variables for a single $display-font-weight and adjusted font-sizes.

 - Added two new .display-* heading sizes, .display-5 and .display-6.

 - Links are underlined by default (not just on hover), unless they’re part of specific components.

 - Redesigned tables to refresh their styles and rebuild them with CSS variables for more control over styling.

 - **Breaking** Nested tables do not inherit styles anymore.

 - **Breaking** .thead-light and .thead-dark are dropped in favor of the .table-* variant classes which can be used for all table elements (thead, tbody, tfoot, tr, th and td).

 - **Breaking** The table-row-variant() mixin is renamed to table-variant() and accepts only 2 parameters: $color (color name) and $value (color code). The border color and accent colors are automatically calculated based on the table factor variables.

 - Split table cell padding variables into -y and -x.

 - **Breaking** Dropped .pre-scrollable class. See #29135

 - **Breaking** .text-* utilities do not add hover and focus states to links anymore. .link-* helper classes can be used instead. See #29267

 - **Breaking** Dropped .text-justify class. See #29793

 - Reset default horizontal padding-left on `<ul>` and `<ol>` elements from browser default 40px to 2rem.

 - Added $enable-smooth-scroll, which applies scroll-behavior: smooth globally—except for users asking for reduced motion through prefers-reduced-motion media query. See #31877

## RTL
 - Horizontal direction specific variables, utilities, and mixins have all been renamed to use logical properties like those found in flexbox layouts—e.g., start and end in lieu of left and right.

## Helpers
 - **Breaking** Responsive embed helpers have been renamed to ratio helpers with new class names and improved behaviors, as well as a helpful CSS variable.
   - Classes have been renamed to change by to x in the aspect ratio. For example, .ratio-16by9 is now .ratio-16x9.
   - We’ve dropped the .embed-responsive-item and element group selector in favor of a simpler .ratio > * selector. No more class is needed, and the ratio helper now works with any HTML element.
   - The $embed-responsive-aspect-ratios Sass map has been renamed to $aspect-ratios and its values have been simplified to include the class name and the percentage as the key: value pair.
   - CSS variables are now generated and included for each value in the Sass map. Modify the --bs-aspect-ratio variable on the .ratio to create any custom aspect ratio.      
   
 - **Breaking** “Screen reader” classes are now “visually hidden” classes.
   - Changed the Sass file from scss/helpers/_screenreaders.scss to scss/helpers/_visually-hidden.scss
   - Renamed .sr-only and .sr-only-focusable to .visually-hidden and .visually-hidden-focusable
   - Renamed sr-only() and sr-only-focusable() mixins to visually-hidden() and visually-hidden-focusable().  

 - bootstrap-utilities.css now also includes our helpers. Helpers don’t need to be imported in custom builds anymore.

**Comment by tcbegley** [comment]
Thanks for this! Have incorporated into the docs.
