### ISSUE TITLE
V1 Standalone Toggle switch

### ISSUE THREAD

**Issue by AnnMarieW** [facultyai/dash-bootstrap-components#679]
Currently there is a standalone `Checkbox` and `RadioButton` and I think it would be great to add a toggle switch. I'd like to offer two solutions:

**Option 1**
- Add example to the docs (no changes to components)

I saw that it's pretty easy to make a standalone toggle switch in Bootstrap 5 by adding the `"form-switch"` class to the `Div` that wraps the  `Checkbox` .

Here is the code for the toggle switch that could be added to the "Standalone checkboxes and radio buttons" snippet in the docs:

```python
html.Div(
    [
        dbc.Checkbox(id="standalone-switch", checked=False),
        dbc.Label(
            "This is a toggle switch",
            html_for="standalone-switch",
            check=True,
        ),
    ],
    className="form-check form-switch",
),


```
The new snippet example would look like:
![image](https://user-images.githubusercontent.com/72614349/132112386-59ec2d3b-fe3c-4121-9c13-a1656f849dbf.png)

**Option 2**
- Drop the `Checkbox` and `RadioButton` components
- Drop the `check` prop in `Label` (since it's no longer needed if `Checkbox` and `RadioButton` are dropped)
- Use the new `Toggle` component

I created a `Toggle` component that makes it possible to add a standalone radio, switch or checkbox to the layout with one line of code.  (Just change the `type` prop). 

Here is the code for adding the three components in the image above with only 3 lines of code rather than 33.

```python
dbc.Toggle(id="checkbox", label="This is a checkbox", value=True),
dbc.Toggle(id="switch", type="switch", label="This is a toggle switch", value=False),
dbc.Toggle(id="radio", type="radio", label="This is a radio button", value=False)


```

If you would this added, please let me know and I'd be happy to do a PR for either option 1 or options 2.

**Comment by tcbegley** [comment]
I think I prefer option 2, but am a little concerned about the breaking change. Also while `Toggle` works well as a name for the switch style, I don't know if it's that discoverable for checkbox or radio?

What about adding a `switch` prop to both `Checkbox` to mimic behaviour of `Checklist`?

**Comment by AnnMarieW** [comment]
Yeah, I'm concerned about breaking changes too.   I started with adding a `switch` prop to `Checkbox`  (let's call that "Option 0") but was having trouble getting the labels to align correctly.  I think it's because the `"form-switch"` class needs to be on the wrapping `Div` rather than a prop of `Checkbox`.   "Option 1" solves that problem.


With Option 2, I think it actually helps manage breaking changes.   Take for example this v0.13.0 check box:


```python
    dbc.FormGroup(
            [
                dbc.Checkbox( id="standalone-checkbox", className="form-check-input" ),
                dbc.Label( "This is a checkbox",
                    html_for="standalone-checkbox",
                    className="form-check-label",
                ),
            ],
            check=True,
        ),
```


Lots of breaking changes in V1:  `FormGroup` is dropped and `Label` has changed to include a `check` prop and the Bootstrap 5 class names have changed.  So it needs to be updated to look like:


```python
html.Div(
    [
        dbc.Checkbox(id="standalone-checkbox", checked=False),
        dbc.Label(
            "This is a checkbox",
            html_for="standalone-checkbox",
            check=True,
        ),
    ],
    className="form-check",
),




```


I think it would be easier to use the "option 2" component: 


```python
dbc.Toggle(id="checkbox", label="This is a checkbox", value=False),
```


However, I agree that `Toggle` is not the best name.  Which brings me to "Option 3" :  Turn `Toggle` into 3 components and remove the `type` prop.  So the example in the image would look like:


```python
dbc.Checkbox(id="checkbox", label="This is a checkbox", value=True),
dbc.Switch(id="switch",  label="This is a toggle switch", value=False),
dbc.RadioButton(id="radio", label="This is a radio button", value=False)
```

I think "option 3" is now my favorite, but I'm happy to go back and see if I can make "option 0" work too if you prefer.  I see the advantages of that since the methods are similar to current version.

**Comment by tcbegley** [comment]
Option 3 looks very clean in your example there, my main concern is whether it would break the `InputGroup` [example](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/input_group/) where a checkbox / radio is put inside the input group?

If it does break I think I know how we can work around it by modifying the `InputGroup` component itself.
