### ISSUE TITLE
New Feature: dcc.Upload 

### ISSUE THREAD

**Issue by LukasKaspras** [facultyai/dash-bootstrap-components#681]
**It would be great to have the upload widget from [dash core components](https://dash.plotly.com/dash-core-components/upload)!**

**Comment by tcbegley** [comment]
Why not use `dcc.Upload` itself? Or do you mean you want the styling to be different?

**Comment by LukasKaspras** [comment]
Yes, I was talking about the styling!

**Comment by tcbegley** [comment]
Can you open an issue on [tcbegley/dash-bootstrap-css](https://github.com/tcbegley/dash-bootstrap-css)? I think this would be better addressed over there. I can't promise I'll get to it in the near future though.
