### ISSUE TITLE
Input validation for number type does not consider valid below max

### ISSUE THREAD

**Issue by D3V4N5H** [facultyai/dash-bootstrap-components#682]
Please fill out the below information as much as possible.

- dash version: `1.20.0`
- dash-bootstrap-components version: `0.13.0`
- components affected by bug: dbc.Input

### What is happening?

When I put `459,568,060` in the input field, it is red. When I reduce it by `1` number to `459,568,059` it is still red. Even when I reduce it to a couple thousand numbers, the input field is red. However, the input field border stays blue for `321,697,642` and many numbers after that.

### What should be happening?

The input field should be blue and consider `459,568,060` as valid input. It should at least consider `459,568,059` as valid.

### Code

```python
import dash_bootstrap_components as dbc
dbc.Input(id="target-cost", type="number", min=321697642, max=459568060, step=1000000)
```

**Comment by AnnMarieW** [comment]
Hi @D3V4N5H 

The `Input` appears to be working correctly based on how it is defined.  Note that the valid numbers are limited by the `step`.

This is from the from the documentation:

>**step** (string | number; default 'any'): Works with the min and max attributes to limit the increments at which a numeric or date-time value can be set. It can be the string any or a positive floating point number. **If this attribute is not set to any, the control accepts only values at multiples of the step value greater than the minimum.**


So according to the code snippet provided, the valid numbers would be 231697642,  232697642,  233697642...
and the largest valid number would be  458697642

For the `Input` field to validate the number according to your description in the "What should be happening" section, try changing the `step` to 1.

**Comment by D3V4N5H** [comment]
You are right. I changed the step size to 1, and now it works as intended. However, I don't think step size should determine the validity of the input, rather it should be for convenience. The only constraints I want are minimum and maximum values. I don't need them to be the sum of minimum and a multiple of the step size. Is this an issue with the implementation of the Bootstrap library for Dash? Or is it something decided by Bootstrap core CSS? Or does this go down all the way to the basic native element of HTML inputs? Also, how can I get the desired effect? Do I need to modify the python module or make an app.css? Please guide me, I am clearly out of my depth here.

**Comment by AnnMarieW** [comment]
Dash works the same way, and yes, it's based on the HTML input.  See more at:  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number.

I'm not sure how to modify this behavior, but since it's a standard web interface, I'm not sure that would be recommended.

**Comment by tcbegley** [comment]
Thanks for raising this @D3V4N5H, but since we are consistent with behaviour in both the HTML standard and Dash itself I don't think we'll change anything here.
