### ISSUE TITLE
Cursor jumps to the end of line when you edit a text from the middle in dbc.Input

### ISSUE THREAD

**Issue by csonday** [facultyai/dash-bootstrap-components#694]
- dash version: `#1.19.0`
- dash-bootstrap-components version: `#0.13.0`
- components affected by bug: dbc.Input

### What is happening?

When user attempts to add/edit a character in the middle of a string in a dbc.Input element, the text cursor automatically jumps to the end of the line. This is affecting my current project. You can also observe the bug in the [documentation](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/input/).

Example: 
I type a string.
![image](https://user-images.githubusercontent.com/55682386/133052234-6a0ea5a2-4e18-4f7b-89aa-c16a9164fc57.png)
I place the cursor to delete the hyphen.
![image](https://user-images.githubusercontent.com/55682386/133052259-e982e5f7-25de-4c06-b62d-6a4d861048ce.png)
When I press backspace, the cursor jumps to the end.
![image](https://user-images.githubusercontent.com/55682386/133052289-fd92ea78-c9aa-4ba5-bac5-51618c46b883.png)

It should be noted that this behavior is not exhibited when input type is set to number. 

### What should be happening?

The cursor must stay in the middle of the string when an edit is made from the middle. 

### Code

Just copy-pasting the code from the documentation. 

```python
import dash_bootstrap_components as dbc
import dash_html_components as html
from dash.dependencies import Input, Output

text_input = html.Div(
    [
        dbc.Input(id="input", placeholder="Type something...", type="text"),
        html.Br(),
        html.P(id="output"),
    ]
)


@app.callback(Output("output", "children"), [Input("input", "value")])
def output_text(value):
    return value
```

### Error messages

No error message.

**Comment by tcbegley** [comment]
Thanks for raising this @csonday. Will take a look and try to make a fix for the upcoming v1.

**Comment by tcbegley** [comment]
Hi @csonday 

This has been fixed in the latest beta of dash-bootstrap-components v1.

```sh
pip install -U --pre dash-bootstrap-components
```

Will work on a patch release of v0 also in the coming days.

**Comment by tcbegley** [comment]
I've now also made a patch release, so if you're not ready to migrate to v1 yet you can simply update

```sh
pip install -U dash-bootstrap-components
```

Let me know if you have any more issues.
