### ISSUE TITLE
`dbc.FormGroup` disappeared in 1.0.0b1

### ISSUE THREAD

**Issue by xhlulu** [facultyai/dash-bootstrap-components#695]
Before opening:

- [Search for duplicate or closed issues](https://github.com/facultyai/dash-bootstrap-components/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the [contributing guidelines](https://github.com/facultyai/dash-bootstrap-components/blob/main/.github/CONTRIBUTING.md)

Please fill out the below information as much as possible.

- dash version: `#2.0.0`
- dash-bootstrap-components version: `#1.0.0b1`
- components affected by bug: `dbc.FormGroup`

### What is happening?

When trying to use Form groups, I get the following error:

```
AttributeError: module 'dash_bootstrap_components' has no attribute 'FormGroup'
```

### What should be happening?

Deprecation warning if `FormGroup` will be removed

### Code

https://dash-bootstrap-components.opensource.faculty.ai/docs/components/form/

### Error messages

```
Traceback (most recent call last):
  File "app/index.py", line 37, in <module>
    conversation_type_form = dbc.FormGroup(
AttributeError: module 'dash_bootstrap_components' has no attribute 'FormGroup'
```

**Comment by AnnMarieW** [comment]
Hi @xhlulu 

I agree it would have been better to have a deprecation warning for FormGroup and the other breaking changes in V1.   However, this new version uses Bootstrap V5 --and FormGroup, along with several other components -- were dropped in V5: https://getbootstrap.com/docs/5.1/migration/#forms

There are lots of cool new features in `dash-bootstrap-components` v1.0, so hopefully it will be worth the effort to upgrade existing apps.

See more info in the [migration guide](https://dbc-v1.herokuapp.com/migration-guide/)

**Comment by tcbegley** [comment]
I think we should put in a more informative error if the user tries to use `FormGroup`, directing them to the above migration guide etc. and informing them that this has happened because they're using v1. There will be people who inadvertently upgrade just because they do a clean install or something and might be confused about why their app suddenly stopped working.

**Comment by AnnMarieW** [comment]
Good idea - and include not only FormGroup but all the dropped components -- and props.   There should also be a an alert on the current version of the docs directing people to the new docs if they are using V1

**Comment by tcbegley** [comment]
Added deprecation warnings in the second beta

```sh
pip install -U --pre dash-bootstrap-components
```
