### ISSUE TITLE
Add delay to Spinner

### ISSUE THREAD

**Issue by harisbal** [facultyai/dash-bootstrap-components#696]
Hello and thanks for this awesome library!

I wanted to suggest introducing a `delay` parameter (in ms) before the appearance of a spinner. This could improve the user experience in cases where the loading time is very small.
Cheers

**Comment by tcbegley** [comment]
Hi @harisbal 

I've added this in the latest beta. The component now has two props: `show_delay` (which does what you suggested) and `hide_delay` (which we already had previously under the name `debounce`). 

Please try it out and let us know if it works for you

```sh
pip install -U --pre dash-bootstrap-components
```

**Comment by harisbal** [comment]
Seems to be working like a charm but I'll come back if I notice anything weird. As a suggestion I would: 
- rename the attributes to `delay_show` and `delay_hide` so they appear close in documentation.
- or move them in a dictionary `delay` with keys `'show'` and `'hide'`

Thank you so much for this.

v1 is full of useful features!

**Comment by tcbegley** [comment]
Nice, I agree either option is better, will make a call and change for the next beta / release candidate

**Comment by tcbegley** [comment]
Changed to `delay_show` and `delay_hide` in latest beta.
