### ISSUE TITLE
BUG: dash-leaflet map inside Modal issue

### ISSUE THREAD

**Issue by harisbal** [facultyai/dash-bootstrap-components#704]
Prior to dbc v1 I could render a dash-leaflet map inside a modal with no problem. After the upgrade the map behaves weirdly (large grey area and weird behavior of controls).
![image](https://user-images.githubusercontent.com/6556306/133930850-229fcbd7-b7ef-4950-b591-bafc8a7cdd2c.png)

I am using:
- dash version: `2.0.0`
- dash-bootstrap-components version: `1.0.0b2`
- dash-leaflet: `0.1.18`
- components affected by bug: `Modal`

and you can replicate with this:

```python
import dash_bootstrap_components as dbc
import dash_leaflet as dl

from dash import Dash, html, Output, Input, State

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

modal = html.Div(
    [
        dbc.Button("Open modal", id="open", n_clicks=0),
        dbc.Modal(
            [
                dbc.ModalHeader("Header"),
                dbc.ModalBody(
                    [
                        dl.Map(
                            [dl.TileLayer(id="tiles")],
                            style={"width": "100%", "height": "50vh"},
                            id="modal-map",
                        ),
                    ]
                ),
                dbc.ModalFooter(
                    dbc.Button("Close", id="close", className="ml-auto", n_clicks=0)
                ),
            ],
            id="modal",
            is_open=False,
        ),
    ]
)

app.layout = dbc.Container(modal)


@app.callback(
    Output("modal", "is_open"),
    [Input("open", "n_clicks"), Input("close", "n_clicks")],
    [State("modal", "is_open")],
)
def toggle_modal(n1, n2, is_open):
    if n1 or n2:
        return not is_open
    return is_open


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by tcbegley** [comment]
Hi @harisbal 

The reason for the grayed out tiles is because Leaflet doesn't know how big the size of its container is when it's first rendered because of the modal being hidden. You'll see if you resize the browser window after the map is displayed it fixes the rendering issues, because Leaflet recalculates its size and now has access to the size of the parent container.

I'm not really sure to be honest why this wasn't an issue before when we were using reactstrap (we've since migrated to react-bootstrap), I'll need to investigate this a bit further.

In the meantime though, it is possible to make a small modification to your Python code that resolves the issue. Basically we just need to find a way to make Leaflet recalculate its size once the modal is showing, so we can write a callback that drops the leaflet map into the modal body once the modal is open like this

```python
import dash_bootstrap_components as dbc
import dash_leaflet as dl
from dash import Dash, Input, Output, State, html

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

map_layout = dl.Map(
    [dl.TileLayer(id="tiles")],
    style={"width": "100%", "height": "50vh"},
    id="modal-map",
)

modal = html.Div(
    [
        dbc.Button("Open modal", id="open", n_clicks=0),
        dbc.Modal(
            [
                dbc.ModalHeader(dbc.ModalTitle("Header"), close_button=True),
                dbc.ModalBody(id="modal-body"),
                dbc.ModalFooter(
                    dbc.Button(
                        "Close", id="close", className="ml-auto", n_clicks=0
                    )
                ),
            ],
            id="modal",
            is_open=False,
        ),
    ]
)

app.layout = dbc.Container(modal)


@app.callback(
    Output("modal", "is_open"),
    [Input("open", "n_clicks"), Input("close", "n_clicks")],
    [State("modal", "is_open")],
)
def toggle_modal(n1, n2, is_open):
    if n1 or n2:
        return not is_open
    return is_open


@app.callback(Output("modal-body", "children"), Input("modal", "is_open"))
def set_map(is_open):
    """
    This callback dynamically inserts the map into the layout as the modal
    opens, ensuring it is sized correctly
    """
    if is_open:
        return map_layout
    return ""


if __name__ == "__main__":
    app.run_server(debug=True)
```

This now seems to be working for me

![image](https://user-images.githubusercontent.com/15220906/133968541-16600205-d521-4d6b-b850-9a85efc9aa03.png)

PS - btw note the use of `ModalTitle` which differs to dbc<1.

**Comment by harisbal** [comment]
Thank you very much @tcbegley, it is working fine now.
It would be very interesting to see how <v1 dealt with the problem so we can avoid the additional callback.
Cheers!

**Comment by AnnMarieW** [comment]
Hey @harisbal   I ran this with V0.13.0 with the same result.  In which version of this library did it work correctly without an additional callback?

**Comment by harisbal** [comment]
Hello @AnnMarieW 
I have the impression that I was using V0.13.0 but is quite difficult to reproduce now.
I'll report more if I manage to revert to the old version.

**Comment by tcbegley** [comment]
Is it possible there was an update in Leaflet itself that could have changed the behaviour?

**Comment by harisbal** [comment]
Sorry for the confusion but there is high chance that this behavior is not due to the update but due to a callback that does not exist anymore in my code and which probably invoking a redraw (as @tcbegley suggested in his answer).

Showing a map inside a bootstrap modal seems like a long-lasting [issue](https://stackoverflow.com/questions/20400713/leaflet-map-not-showing-properly-in-bootstrap-3-0-modal).

In JS world the solution seems to be `map.invalidateSize()` but could that be that be transferable in dbc ?

**Comment by tcbegley** [comment]
Pretty sure any call to something like `map.invalidateSize()` would have to happen on the dash-leaflet side, as the `Modal` has no knowledge of what its children are. Though you'd have the opposite problem on that end where the map would have to detect that it's in the modal and detect when the status of the modal changes...

Perhaps there's something you could do with a clientside callback? A javascript snippet that finds the map and invalidates it when the status of the modal changes? At least that would avoid a round-trip to the server. Unfortunately I don't know Leaflet well enough to know if that's going to be possible.

**Comment by harisbal** [comment]
I probably spoke too soon.

Fiddling a bit with the code, I realized that a quick solution is to include `display:block` attribute in the style of the modal.

For some reason this seems to work now (pay attentions to the `style` attributes of both `Modal` and `Map`):

```python
import dash_bootstrap_components as dbc
import dash_leaflet as dl

from dash import Dash, html, Output, Input, State

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

modal = dbc.Container(
    [
        dbc.Button("Open modal", id="open", n_clicks=0),
        dbc.Modal(
            [
                dbc.ModalHeader("Header"),
                dbc.ModalBody(
                    [
                        dl.Map(
                            [dl.TileLayer(id="tiles")],
                            style={"width": "100%", "height": "40vh",},
                            id="modal-map",
                        ),
                    ]
                ),
                dbc.ModalFooter(
                    dbc.Button("Close", id="close", className="ml-auto", n_clicks=0)
                ),
            ],
            id="modal",
            is_open=False,
            style={"width": "100%", "height": "60vh", "display": "block"},
        ),
    ]
)

app.layout = dbc.Container(modal)


@app.callback(
    Output("modal", "is_open"),
    [Input("open", "n_clicks"), Input("close", "n_clicks")],
    [State("modal", "is_open")],
)
def toggle_modal(n1, n2, is_open):
    if n1 or n2:
        return not is_open
    return is_open


if __name__ == "__main__":
    app.run_server(debug=True)
```
