### ISSUE TITLE
Dash 2.0.0 structure change affecting dbc table

### ISSUE THREAD

**Issue by slyin87** [facultyai/dash-bootstrap-components#715]
- dash version: `#2.0.0`
- dash-bootstrap-components version: `#0.13.1`
- components affected by bug: _table.py

### What is happening?

C:\Python386\lib\site-packages\dash_bootstrap_components\_table.py:5: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html

### What should be happening?

should have no warning

**Comment by tcbegley** [comment]
Duplicate of #692 

This will be resolved in v1 of dash-bootstrap-components. You can already install the beta if you like

```sh
pip install -U --pre dash-bootstrap-components
```

Until we finalise the full release your options are

- Use the beta
- Pin dash<2
- Ignore the warnings
