### ISSUE TITLE
Tooltips stay open

### ISSUE THREAD

**Issue by AnnMarieW** [facultyai/dash-bootstrap-components#719]
In V1 sometimes Tooltips stay open.  It's noticeable when there are several Tooltips in a list.   
Setting the delay higher than zero, makes it worse.  

![tooltip_v1](https://user-images.githubusercontent.com/72614349/135721015-93ffc476-4a1b-4bb4-a173-fd121b2cbb44.gif)

In V0 there was a delay - even if you set delay to 0, and this may be why it worked?

![tooltip_v0](https://user-images.githubusercontent.com/72614349/135721025-d7e7efa3-a913-46e7-b7eb-3dfe20835747.gif)

Here's a MWE:

```python
from dash import Dash, html
import dash_bootstrap_components as dbc

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])


def make_items(idx, tooltip):
    return html.Div(
        [
            dbc.ListGroupItem(
                idx,
                id=idx,
                n_clicks=0,
                className="border-0 text-nowrap",
                style={"width": 100},
            ),
            dbc.Tooltip(
                tooltip, id="tooltip" + idx, target=idx, delay={"show": 0, "hide": 50}
            ),
        ]
    )


app.layout = dbc.Container(
    dbc.ListGroup([make_items(f"item-{i}", f"item-{i}") for i in range(20)])
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by tcbegley** [comment]
Sorry for the delay getting back to you on this, was trying to get #724 over the line first. Will take a look into it!

**Comment by tcbegley** [comment]
I think I managed to resolve this in #788 ... 🤞 

If you have time to test on your end @AnnMarieW I would be interested to hear how you get on!

**Comment by AnnMarieW** [comment]
Looks like it work.  Thanks! :partying_face:

**Comment by tcbegley** [comment]
New version with fix has been released

```sh
pip install -U dash-bootstrap-components
```
