### ISSUE TITLE
modalHeader font style changed in v1.0

### ISSUE THREAD

**Issue by aGitForEveryone** [facultyai/dash-bootstrap-components#720]
- dash version: `v2.0.0`
- dash-bootstrap-components version: `v1.0.0b3`
- components affected by bug: dbc.ModalHeader

### What is happening?

The font style of the ModalHeader has changed in the new version. It used to be bold + larger font size however now it is just regular text. 

### What should be happening?

I was expecting the old modal header style. 

### Code

```
dbc.Modal(
    [
        dbc.ModalHeader('Modal header is just regular text'),
        dbc.ModalBody('Just some filler text'),
        dbc.ModalFooter(dbc.Button('Click me')
    ],
    id='modal_test'
)
```

**Comment by tcbegley** [comment]
That's very helpful feedback, thanks! I think we can definitely improve the wording to make that clearer.

**Comment by tcbegley** [comment]
Alert and migration guide updated, thanks again for raising this.
