### ISSUE TITLE
V1 Themes Documentation includes reference to Bootstrap V4

### ISSUE THREAD

**Issue by glsdown** [facultyai/dash-bootstrap-components#730]
Currently the v1 documentation states:

> _dash-bootstrap-components_ doesn't come with CSS included. This is to give you the freedom to use any Bootstrap v4 stylesheet of your choice, so you can achieve the look you want in your app.

As v1 is using Bootstrap 5, this should be updated.

**Comment by AnnMarieW** [comment]
While someone is in the neighborhood, here are a couple more minor docs updates:

In the Icons section, we should make it really clear which version is used.  I've noticed that there are many changes between FontAwesome versions -- and the icons just don't appear if the syntax isn't correct, or certain icons from a different version are used. 

In the first paragraph in the layout section it says:
>The Bootstrap grid has twelve columns, and five responsive tiers (allowing you to specify different behaviours on different screen sizes, see below).  

But there are six responsive tiers now with the new XXL tier

**Comment by glsdown** [comment]
@tcbegley I think that people wouldn't really know to do that though - I certainly wouldn't. Also, including in the docs makes it something people think about rather than spending ages on debugging why it isn't working.

**Comment by tcbegley** [comment]
Icons page has snake_case `class_name` for HTML components which obviously won't work... 

https://dash-bootstrap-components.opensource.faculty.ai/docs/icons/
