### ISSUE TITLE
Provided Examples in docs only include Python source code

### ISSUE THREAD

**Issue by glsdown** [facultyai/dash-bootstrap-components#735]
- [ ] All examples only have python source code available in the documentation, although the source code exists for other languages. These should also be included. 

_Originally posted by @glsdown in https://github.com/facultyai/dash-bootstrap-components/issues/730#issuecomment-940498946_

**Comment by tcbegley** [comment]
Development on Dash for R / Julia appears to have stalled so I suggest we deprioritise this for now.
