### ISSUE TITLE
Migrating to v1

### ISSUE THREAD

**Issue by tcbegley** [facultyai/dash-bootstrap-components#741]
We recently released dash-bootstrap-components v1. This has loads of new features and improvements but also some breaking changes. If updating to v1 broke your app you have two options:

- Update your code to remove references to any deprecated components / keyword arguments.
- Continue to use version 0.

There are full details of all the changes in our [migration guide](https://dash-bootstrap-components.opensource.faculty.ai/migration-guide/), including instructions for installing earlier versions of dash-bootstrap-comopnents if you're not yet ready to upgrade.

You can also find documentation for legacy versions of dash-bootstrap-components [here](https://dbc-v0.herokuapp.com/)

**Comment by chase-jones** [comment]
There might be a breaking change missing in the migration guide above. I had a breaking change issue with dbc.RadioItems no longer taking the "custom" argument, and I don't see a note about it in the migration guide.

**Comment by tcbegley** [comment]
Ah yes, you're right. As of Bootstrap 5 custom styles are the only option which means that particular argument is obsolete. Will update the guide!

**Comment by tcbegley** [comment]
Since it's been over a year since v1 release, will close this now.
