### ISSUE TITLE
Update Project.toml to use Dash for Julia 1.0

### ISSUE THREAD

**Issue by grahamstark** [facultyai/dash-bootstrap-components#748]
Hi,

would it be possible to change the  Dash version in the compat section of the Julia `Project.toml` file, so loading DashBootstrapComponents.jl doesn't cause a Dash.jl downgrade? So, change:

    [compat]
    Dash = "0.1.3"
to:

    Dash = "1"

Playing around informally with Dash.jl 1.0 and a manually changed DashBootstrapComponents.jl suggests that there are no compatibility problems. 

I'm afraid I can't offer a patch for this as I don't understand the build process here :(

thanks! This is great work,

Graham

**Comment by espintos** [comment]
I'm having this problem as well, adding DashBootStratComponents downgrades Dash and other packages:

```
pkg> add DashBootstrapComponents
  Resolving package versions...
Updating `C:\Users\Home\...\Project.toml`
  [1b08a953] ↓ Dash v1.0.0 ⇒ v0.1.6
  [1b08a953] + DashBootstrapComponents v1.0.0
Updating `C:\Users\Home\...\Manifest.toml`
  [1b08a953] ↓ Dash v1.0.0 ⇒ v0.1.6
  [1b08a953] + DashBootstrapComponents v1.0.0
  [1b08a953] ↓ DashCoreComponents v2.0.0 ⇒ v1.17.1
  [1b08a953] ↓ DashHtmlComponents v2.0.0 ⇒ v1.1.4
  [1b08a953] ↓ DashTable v5.0.0 ⇒ v4.12.0
  [94ce4f54] - Libiconv_jll v1.16.0+8
  [69024149] - StringEncodings v0.3.5
  [ddb6d928] - YAML v0.4.7
```
Is there a workaround until the version conflicts are resolved?

**Comment by grahamstark** [comment]
> Is there a workaround until the version conflicts are resolved?

* clone  DashBootstrapComponents into some local directory;
* manually alter the Dash version number in DashBootstrapComponents' `Project.toml`;
* in your project, do ]develop (path to the local DashBootstrapComponents).

**Comment by tcbegley** [comment]
This should now be resolved in the latest release. Thanks again for raising!

```
pkg> update DashBootstrapComponents
```

**Comment by grahamstark** [comment]
Brilliant, thanks.
