### ISSUE TITLE
Popover and DropdownMenu dismissal

### ISSUE THREAD

**Issue by tcbegley** [facultyai/dash-bootstrap-components#750]
Reported on the [Plotly forum](https://community.plotly.com/t/dash-bootstrap-components-v1-beta-release-available/56526/13)

- [x] With the popover with “legacy” trigger, clicking the popover itself dismisses it which is not what it was supposed to do (dismiss when clicking outside).
- [x] It looks like the hide_arrow does not work on the Popover?
- [x] It looks like offset does not work on the Popover?
- [x] With the DropdownMenu, clicking outside of the menu used to close it but it doesn’t anymore and it looks like we now either have to click the button or a DropdownItem. Maybe adding support for Escape to close the menu would make sens too?

**Comment by RenaudLN** [comment]
Another issue with v1 Popovers is with `hover` trigger. Hovering on the target does open the popover but moving the mouse to the Popover closes it whereas it used to stay open before v1.

**Comment by tcbegley** [comment]
The original issue has been resolved in the latest version of dash-bootstrap-components

```
pip install -U dash-bootstrap-components
```

@RenaudLN apologies I missed your comment when doing bug fixes for the latest release, I have opened #785 to track this.
