### ISSUE TITLE
FormFeedback not working with dbc.Select component

### ISSUE THREAD

**Issue by Joakimden4** [facultyai/dash-bootstrap-components#753]
- dash version: `2.0.0`
- dash-bootstrap-components version: `1.0.0`
- components affected by bug: dbc.Select & dbc.FormFeedback

### What is happening?
The dbc.Select component does not react when the valid or invalid property is set through a callback function.

### What should be happening?
The dbc.Select component should receive a green border like the dbc.Input component does, whenever the valid property is set to True.

### Code ###

```python
html.Div(
    dbc.FormFloating([
        dbc.Select(
            id='select_test', 
            placeholder='Test', 
            options=[{"label": "Option 1", "value": "1"}, {"label": "Option 2", "value": "2"}],
            style={'color':'white'}
        ),
        dbc.Label('Test'),
        dbc.FormFeedback(type='invalid'),
        dbc.FormFeedback(type='valid')
    ])
)

@app.callback(
    [Output('select_test', 'valid'),
     Output('select_test', 'invalid'),
    ],
    [Input('select_test', 'value')
    ]
)
def check_validity(select_test_value):
    return True, False
```

I get no error messages - the component borders simply just don't change color.
The code works as intended if you replace the dbc.Select component with a dbc.Input component
I have no custom CSS or anything that should overrule the bootstrap theme

**Comment by Joakimden4** [comment]
@glsdown I have updated my library, but it still doesn't seem to work.
Any idea why? :)

**Comment by glsdown** [comment]
Hi @Joakimden4 

I believe @tcbegley was working on approving and merging the pull requests into this repository, but not sure he’s yet done a new release, so it may not be available quite yet. Hopefully he can confirm though.

**Comment by tcbegley** [comment]
Hi @Joakimden4 

Sorry for the delay, I'm working on clearing a backlog of changes / bugfixes before making a full release. I have made a [prerelease](https://pypi.org/project/dash-bootstrap-components/1.0.1rc2/) that fixes this issue that you can start using until the full release is ready.

```
pip install dash-bootstrap-components==1.0.1rc2
```

**Comment by Joakimden4** [comment]
@tcbegley @glsdown 
Thanks guys and no worries - I was just under the impression that you had already made a release, so I thought the problem was on my end :)

**Comment by tcbegley** [comment]
This has been resolved in the latest version of dash-bootstrap-components

```
pip install -U dash-bootstrap-components
```
