### ISSUE TITLE
OffCanvas toggled by target click/hover

### ISSUE THREAD

**Issue by luiztauffer** [facultyai/dash-bootstrap-components#754]
It would be great to have the possibility of toggling `Offcanvas` and `Modal` the same way we toggle `Popover`, that is, based on click/hover of any target element.
Is this a possible extension?

That would be great to interact with some Dash components which create elements with known ids (to use as targets), but for which we cannot use their ids to trigger dash callbacks. Examples are Pro components Gantt Chart and FlowChart.
See an example of what we are doing right now, using `Popovers`, doing that with an `OffCanvas` would be ideal:

![Peek 2021-10-27 15-23](https://user-images.githubusercontent.com/24541631/139074487-683716c4-691a-4feb-ba17-61b1ef54ad93.gif)

**Comment by tcbegley** [comment]
Cool gif!

I'll have a think about it, but the way that the underlying component works in `react-bootstrap` is quite different to how popovers and tooltips work so it wouldn't be a simple change. Unfortunately I probably don't have the capacity to prioritise this at the moment, but I'd happily review any proposals if you want to look into how this could work yourself.

**Comment by tcbegley** [comment]
I think unfortunately this isn't really feasible without major architectural changes. Going to close. Open to proposals from anyone in future if you have ideas for how this could work.
