### ISSUE TITLE
Checkbox 1.0 checked property removed but not documented as a breaking change?

### ISSUE THREAD

**Issue by jouvin** [facultyai/dash-bootstrap-components#761]
I have an application written with DBC 0.13 and making an extensive use of `dbc.Checkbox`. After upgrading to DBC v1, I realized that the associated callbacks were no longer working and looking at the documentation, that the `checked` property used as a callback input was no longer exising and that `value` was used instead. I have the feeling that it is a breaking change (introduced by https://github.com/facultyai/dash-bootstrap-components/pull/689?) but didn't find it listed in the v1 breaking change section.

**Comment by tcbegley** [comment]
Ah, good spot. This was a late change made for consistency with dash-core-components which we neglected to include in the migration guide. Will add!
