### ISSUE TITLE
dbc.Button not working with dash's ConfirmDialogProvider

### ISSUE THREAD

**Issue by RafaelWO** [facultyai/dash-bootstrap-components#762]
Please fill out the below information as much as possible.

- dash version: `2.0.0`
- dash-bootstrap-components version: `1.0.0`
- components affected by bug: `dbc.Button`

### What is happening?

When using the `dbc.Button` within a `ConfirmDialogProvider` from dash as described in the [docs](https://dash.plotly.com/dash-core-components/confirmdialogprovider), the confirm dialog is not opened if the button is clicked.

If you replace the `dbc.Button` with `html.Button` it works! 

### What should be happening?

The confirm dialog is opened if the button is clicked

### Code

```python
import dash
import dash_bootstrap_components as dbc
from dash import html, dcc, Input, Output, no_update


external_stylesheets = [
    dbc.themes.BOOTSTRAP,
    dbc.icons.FONT_AWESOME
]

app = dash.Dash(external_stylesheets=external_stylesheets)

app.layout = html.Div([
    dcc.ConfirmDialogProvider(
        dbc.Button(
            html.I(className="fas fa-trash-alt fa-sm"),
            id='btn-delete'
        ),
        id='confirm-delete',
        message='Danger danger! Are you sure you want to continue?'
    ),
    html.Small(id='log')
])


@app.callback(
    Output('log', 'children'),
    Input('confirm-delete', 'submit_n_clicks')
)
def do_delete(submit_clicks):
    if not submit_clicks:
        return no_update

    return "You confirmed the deletion!"


if __name__ == '__main__':
    app.run_server(debug=True)
```

### Error messages

None

**Comment by tcbegley** [comment]
Hey @RafaelWO 

Thanks for raising this. I'm not totally sure why this isn't working, but looking at [the implementation of `ConfirmDialogProvider`]() it seems it's trying to clone the child element and overwrite some props which seems a little hacky to me and apparently doesn't work well with `dbc.Button`.

I suggest that you use `html.Button` but manually add the relevant Bootstrap classes to make it look like a Bootstrap button, e.g.

```python
dcc.ConfirmDialogProvider(
    html.Button(
        html.I(className="fas fa-trash-alt fa-sm"),
        id="btn-delete",
        className="btn btn-primary",
    ),
    id="confirm-delete",
    message="Danger danger! Are you sure you want to continue?",
)
```

**Comment by RafaelWO** [comment]
Thanks for your answer, @tcbegley!

I'll try your workaround using the `html.Button` with the Bootstrap classes :)

So if this is due to the implementation of the `ConfirmDialogProvider`, this issue cannot be solved within `dbc`, right?

**Comment by tcbegley** [comment]
> So if this is due to the implementation of the `ConfirmDialogProvider`, this issue cannot be solved within `dbc`, right?

Possibly... though it's not actually super clear to me. I would need to understand a bit better the details of `React.cloneElement`. If it is possible for us to make a change there might be other trade-offs or side-effects.

> Your link to the implementation of the ConfirmDialogProvider links to this very issue ;)

Oops, I didn't actually put a link in the Markdown and apparently the default is just the current page / issue. Have updated.

**Comment by RafaelWO** [comment]
> I suggest that you use `html.Button` but manually add the relevant Bootstrap classes to make it look like a Bootstrap button

@tcbegley, I just tried your suggestion and it works perfectly :tada:, thanks again!

**Comment by tcbegley** [comment]
Hey @RafaelWO , I think I managed to fix this in dash-bootstrap-components. Actually wasn't too hard in the end, just need to make sure parent components can supply their own `onClick` handler. I made a pre-release you can test with

```
pip install dash-bootstrap-components==1.0.1rc3
```

**Comment by RafaelWO** [comment]
@tcbegley I tested the code above with the pre-release and can confirm that it's working. :partying_face: 

Looking forward to the next release!

**Comment by manu418** [comment]
Hi, I encountered the exact same issue with the following versions:
* `dash==3.0.1`
* `dash-bootstrap-components==2.0.0`

When running this code as taken from the dash-docs (https://dash.plotly.com/dash-core-components/confirmdialogprovider), but with a `dbc.Button`:
```python
from dash import Dash, Input, Output, html, dcc, callback
import dash_bootstrap_components as dbc

app = Dash()

app.layout = html.Div([
    dcc.ConfirmDialogProvider(
        children=dbc.Button('Click Me', ),
        id='danger-danger-provider',
        message='Danger danger! Are you sure you want to continue?'
    ),
    html.Div(id='output-provider')
])


@callback(Output('output-provider', 'children'),
          Input('danger-danger-provider', 'submit_n_clicks'))
def update_output(submit_n_clicks):
    if not submit_n_clicks:
        return ''
    return """
        It was dangerous but we did it!
        Submitted {} times
    """.format(submit_n_clicks)


if __name__ == '__main__':
    app.run(debug=True)
```
The ConfirmDialog does not show up. When using a `html.Button` or a `dmc.Button`, it is working as intended.  
Please reopen if I did not mix something up here :-)
