### ISSUE TITLE
The link in navbarsimple is not on the right. How can I set it to be on the right.

### ISSUE THREAD

**Issue by limmyforget** [facultyai/dash-bootstrap-components#764]
The link in navbarsimple is not on the right. How can I set it to be on the right.
dash-bootstrap-components 1.0.0
bootstrap-5.1.3-dist

**Comment by tcbegley** [comment]
Hi, sorry for slow reply. Which link do you mean? The `brand`? If you want to customise the layout of the navbar more than `NavbarSimple` allows you can use `Navbar`. There's some examples [here](https://github.com/facultyai/dash-bootstrap-components/blob/main/examples/python/advanced-component-usage/navbars.py)

**Comment by tcbegley** [comment]
Closing due to no response. Please reopen if you're still having trouble.
