### ISSUE TITLE
Form inline property removed in v1 but not documented in migration guide

### ISSUE THREAD

**Issue by DrGFreeman** [facultyai/dash-bootstrap-components#775]
- dash version: `2.0.0`
- dash-bootstrap-components version: `1.0.0`.
- components affected by bug: `dbc.Form`

### What is happening?

Version 1 dropped the `inline` property of `dbc.Form`.  This is however not documented as a breaking change in the [migration guide](https://dash-bootstrap-components.opensource.faculty.ai/migration-guide/).

### What should be happening?

The migration guide should include a mention of the breaking change with indications to use the grid utilities in stead (as in the [Boostrap 5 migration guide](https://getbootstrap.com/docs/5.1/migration/#forms)).

Note that the inline form example in the [docs](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/form/) shows how to use the grid. Only the mention in the migration guide is missing.

### Error messages

```
TypeError: The `dash_bootstrap_components.Form` component (version 1.0.0) with the ID "xyz" received an unexpected keyword argument: `inline`
Allowed arguments: action, children, className, class_name, id, key, loading_state, method, n_submit, n_submit_timestamp, prevent_default_on_submit, style
```
<hr>
P.S. Kudos @tcbegley & contributors for the release of version 1!

**Comment by DrGFreeman** [comment]
If it's OK, I can submit a PR that adds the missing mention in the migration guide.

**Comment by tcbegley** [comment]
> If it's OK, I can submit a PR that adds the missing mention in the migration guide.

Thanks for raising this issue and spotting the oversight. A PR adding a mention of `inline` to the migration guide would be very welcome!
