### ISSUE TITLE
OffCanvas Error

### ISSUE THREAD

**Issue by wweber-edz** [facultyai/dash-bootstrap-components#778]
- dash version: 2.0.0
- dash-bootstrap-components version: 1.0.0
- components affected by bug: Offcanvas

When building a layout with the Offcanvas element i got this error from Firefox console :
Error: The children property of a component is a list of lists, instead of just a list. Check the component that has the following contents, and remove one of the levels of nesting: 
[
  {
    "props": {
      "children": "AAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "id": "offcanvas-placement",
      "backdrop": true,
      "close_button": true,
      "is_open": false,
      "placement": "end",
      "title": "Placement"
    },
    "type": "Offcanvas",
    "namespace": "dash_bootstrap_components"
  }

and the rest of the elements do not load

### Code

In code i,ve created wrapper for dash_core_components and html_components

    def get_FKH_layout(self):
        session_store = Store(app_name, ly, fieldId='session_store', storageType='session')
        general_data_form_panel = self.bulid_general_data_form_panel()
        contact_details_form_panel = self.build_contact_details_form_panel()
        contact_correspondence_form_panel = self.build_contact_correspondence_form_panel()
        contract_panel = self.build_contract_form_panel()
        contractor_modal = self.build_contractor_register_modal()
        ceidg_modal = self.build_ceidg_contractor_modal()
        contract_table_panel = Panel(app_name, ly, fieldId='contract_table_panel', width='100%', layout='column', title='Ostatnie Aktywności',
                                     children=self.build_contracts_table_panel())

        contractor_id = Store(app_name, ly, fieldId='contractor_id', data=-1)
        object_id = Store(app_name, ly, fieldId='object_id', data=-1)
        dirty_section_primary_data = Store(app_name, ly, fieldId='dirty_section_primary_data', data=False)
        dirty_section_secondary_data = Store(app_name, ly, fieldId='dirty_section_secondary_data', data=False)
        dirty_section_order = Store(app_name, ly, fieldId='dirty_section_order', data=False)
        contractor_data_store = Store(app_name, ly, fieldId='contractor_data_store', data=[])
        ceidg_data_store = Store(app_name, ly, fieldId='ceidg_data_store', data=[])

        offcanvas = dbc.Offcanvas(

            children='AAAAAAAAAAAAAAAAAAAAAAAAAAA',
            id="offcanvas-placement",
            title="Placement",
            is_open=False,
            backdrop=True,
            close_button=True,
            placement='end'
        ),

        forms_panel = Panel(app_name, ly, fieldId='forms_panel', width='100%', height='33%', layout='column',
                            children=[general_data_form_panel.getHtml(),
                                      contact_details_form_panel.getHtml(),
                                      contact_correspondence_form_panel.getHtml()])

        tables_panel = Panel(app_name, ly, fieldId='tables_panel', width='70%', height='70%', layout='column', title='Dostępne obiekty',
                             customStyle={
                                 'margin': '5px'}, children=[self.build_adresses_table_panel(),
                                                             contract_panel.getHtml(),
                                                             contract_table_panel.getHtml()])
        save_alert = dbc.Alert(id='FKH_save_alert', is_open=False, duration=4000, children="Zapisano pomyślnie!", fade=True,
                               color='success',
                               style={'top': '50px', 'width': '99%', 'left': '10px', 'height': '30px',
                                      'padding-bottom': '25px',
                                      'z-index': '1000',
                                      'position': 'absolute'})

        general_panel = Panel(app_name, ly, fieldId='general_panel',
                              title=f"Aplikacja Handlowca",
                              width="100%", layout='column', height='100%', titleAlign='center', titleSize='large',
                              children=[session_store.getHtml(),
                                        forms_panel.getHtml(),
                                        tables_panel.getHtml(),
                                        contractor_modal,
                                        ceidg_modal,
                                        contractor_id.getHtml(),
                                        object_id.getHtml(),
                                        dirty_section_primary_data.getHtml(),
                                        dirty_section_secondary_data.getHtml(),
                                        dirty_section_order.getHtml(),
                                        contractor_data_store.getHtml(),
                                        ceidg_data_store.getHtml(),
                                        save_alert,
                                        offcanvas
                                        ]).getHtml()

        return MainPanel(app_name, ly,
                         applicationHeader='Użytkownik: %s' % self.__my_sess['usrName'], sectionHeight='110%',
                         applicationLayout=general_panel,
                         ).getHtml(),  #

**Comment by AnnMarieW** [comment]
HI @wweber-edz 

Try removing this trailing comma from the offcanvas component:

![image](https://user-images.githubusercontent.com/72614349/143019275-8a9cf28f-117b-4dfc-a0de-2b7e6adc05ca.png)

**Comment by wweber-edz** [comment]
> HI @wweber-edz
> 
> Try removing this trailing comma from the offcanvas component:
> 
> ![image](https://user-images.githubusercontent.com/72614349/143019275-8a9cf28f-117b-4dfc-a0de-2b7e6adc05ca.png)
> 
> More info about this type of error [here](https://community.plotly.com/t/must-be-a-list-not-a-list-of-lists/56394)

OMG, i didn't catch that ... , thank  you

**Comment by AnnMarieW** [comment]
Happy to help :slightly_smiling_face: 
That can  be a tricky one to debug the first time - it really needs a better error message.
