### ISSUE TITLE
Way to Implement Horizontal Accordions

### ISSUE THREAD

**Issue by trevor-pope** [facultyai/dash-bootstrap-components#787]
Is there an example for making horizontal accordions? I know the Accordion component is new in v1.0 and likely doesn't not have this functionality built in, but in earlier versions was there an easy way to implement horizontal accordions?

**Comment by tcbegley** [comment]
Hi @trevor-pope 

I don't believe that this is natively supported by Bootstrap. Your best bet might be to find an example online such as [this one](https://www.cssscript.com/pure-css-responsive-horizontal-accordion/) and try to port that to Dash.

**Comment by trevor-pope** [comment]
Thanks!

**Comment by GitHunter0** [comment]
Hey @trevor-pope , did you manage to port to Dash? I'm looking for this feature too...
