### ISSUE TITLE
dropdownmenu caret=False has no effect

### ISSUE THREAD

**Issue by hobob0t** [facultyai/dash-bootstrap-components#792]
- dash version: `#2.0.0`
- dash-bootstrap-components version: `#1.0.2`
- components affected by bug: dropdownmenu

### What is happening?

Setting dbc.DropdownMenu(caret=False) has no effect. Caret still displays

### What should be happening?

Setting dbc.DropdownMenu(caret=False) should remove the small down arrow. 

### Code

```python
menu = dbc.DropdownMenu(caret=False,
    label="≡",
    children=[
        dbc.DropdownMenuItem("Item 1"),
        dbc.DropdownMenuItem("Item 2"),
        dbc.DropdownMenuItem("Item 3"),
    ], toggle_style={'font-size':"2rem"}
)
```

### Error messages

```bash
None
```

### Additional info

Tried setting caret = "false", "False", None, and "please just work". No change or error was displayed so I think it's just not parsing that kwarg at all? 

Same result in firefox and chrome.

**Comment by tcbegley** [comment]
Hi @hobob0t 

Thanks for reporting this and sorry for the slow reply. This is likely a bug that crept in when we migrated to React-Bootstrap for v1. We'll work on a fix.

**Comment by tcbegley** [comment]
Hi @hobob0t 

This should be fixed in the latest prerelease. If you get a chance to try it out, let me know how you get on!

```
pip install dash-bootstrap-components==1.0.3rc2
```

**Comment by tcbegley** [comment]
This is now fixed in the latest release. Please reopen if you're still having problems after updating.

```
pip install -U dash-bootstrap-components
```
