### ISSUE TITLE
className should not be deprecated

### ISSUE THREAD

**Issue by jblang** [facultyai/dash-bootstrap-components#795]
- dash version: `2.0.0`
- dash-bootstrap-components version: `1.0.2`

### What is happening?

All the docs say that className is deprecated in favor of class_name.  I realize camelCase is not the Python convention, but Dash Core Components and Dash HTML Components (even 2.0) don't support class_name so this creates an inconsistency.

### What should be happening?

Don't deprecate and **definitely** don't remove the className parameter when Dash is still using it.

**Comment by jblang** [comment]
Thank you for the clarification.

**Comment by alexcjohnson** [comment]
Yes, still on our roadmap although it continues to get pushed farther out so I can't comment on when we might get to it - PRs welcome if anyone wants to help us along. My apologies @tcbegley for leaving DBC out ahead on this for such a long time!
