### ISSUE TITLE
No "pointing finger" cursor over tabs in dbc v1

### ISSUE THREAD

**Issue by sergiykhan** [facultyai/dash-bootstrap-components#796]
If the mouse cursor is moved over a dbc.tab component in dbc v1, it does not turn into a "pointing finger", but rather into a "text selection" tool.

It can be seen on the help page https://dash-bootstrap-components.opensource.faculty.ai/docs/components/tabs/

It was not the case in version 0.13.1.

**Comment by sergiykhan** [comment]
The workaround is either

1. supply `cursor: pointer;` in the theme CSS
2. add `label_style={'cursor': 'pointer'},` to `dbc.Tab`

**Comment by tcbegley** [comment]
Hi @sergiykhan 

Thanks for reporting, this should be fixed in the latest prerelease, if you get a chance to try it let me know how you get on!

```
pip install dash-bootstrap-components==1.0.3rc1
```

**Comment by tcbegley** [comment]
This is now fixed in the latest release. Pleaase reopen if you continue to have problems after updating.

```
pip install -U dash-bootstrap-components
```

**Comment by sergiykhan** [comment]
Thank you. Yes, it does work! I have removed my workaround now.
