### ISSUE TITLE
html linebreak (<br>) tag not rendered in dcc.Markdown in dbc.ModalBody 

### ISSUE THREAD

**Issue by aGitForEveryone** [facultyai/dash-bootstrap-components#797]
- dash version: 1.20.0
- dash-bootstrap-components version: 0.12.2
- components affected by bug: dbc.ModalBody

### What is happening?

When passing dcc.Markdown as child of the dbc.ModalBody, (all html tags?) the `<br>` or `<br/>` tag is not rendered properly. The tag is converted to a string and then displayed as text just like the regular text.

### What should be happening?

I would be expecting the tags to work as expected. Or at least an alternative for a linebreak, but I can't seem to find one. 

### Code

```python
import dash
import dash_core_components as dcc
import dash_bootstrap_components as dbc

app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = html.Div(
    dbc.Modal([dbc.ModalBody(dcc.Markdown("""This is a <br> tag, and we can also try the <br/> tag"""))])
)
```

**Comment by AnnMarieW** [comment]
Hi @aGitForEveryone 

Try adding this prop to dcc.Markdown:



`dangerously_allow_html ` (boolean; default False): A boolean to control raw HTML escaping. Setting HTML from code is risky because it's easy to inadvertently expose your users to a cross-site scripting (XSS) (https://en.wikipedia.org/wiki/Cross-site_scripting) attack.


```
                   dcc.Markdown(
                        """This is a <br> tag, and we can also try the <br/> tag""",
                        dangerously_allow_html=True,
                    )
```

**Comment by aGitForEveryone** [comment]
Thanks, the `dangerously_allow_html` does work indeed. The space option doesn't really work as I need to implement line breaks in a cell in a markdown table to display text on two line. Is there any alternative for that? Also I noticed that the default vertical white space between paragraphs is a bit short, so the line break widens the gap a little more, something I didn't find an alternative for either.

**Comment by AnnMarieW** [comment]
Well, I'm no security expert, but I think if you are just using `<br>` tags, there may not be much of a security issue with `dangerously_allow_html`?

Other options could be a DataTable (but that seems like overkill) or maybe an html table insteadof dcc.Markdown

**Comment by aGitForEveryone** [comment]
Thanks for the reply. I am not much of a security expert myself, so I wouldn't know either. But I guess you have a point. 

Thanks for pointing me to the other table options. My current use case is a very simple table, so I don't know if a DataTable is necessary now, maybe an html table would be the more proper way to go. I'll think about it.
