### ISSUE TITLE
Layout docs misleading

### ISSUE THREAD

**Issue by NathanCummings** [facultyai/dash-bootstrap-components#798]
Trying to understand why my columns were padded horizontally, but not vertically, I spent a long time trying to replicate this simple example in the layout docs:

 
![image](https://user-images.githubusercontent.com/29842194/152212952-8593e694-30c1-42e3-b0ae-4fa16605a3a8.png)

This is the code I used:

```python
import dash
import dash_bootstrap_components as dbc
from dash import html


app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    html.Div(
        [
            dbc.Row(
                dbc.Col(
                    html.Div(
                        "A single column",
                        style={"background": "purple"},
                    ),
                ),
            ),
            dbc.Row(
                [
                    dbc.Col(
                        html.Div(
                            "One of three columns",
                            style={"background": "purple"},
                        ),
                    ),
                    dbc.Col(
                        html.Div(
                            "One of three columns",
                            style={"background": "purple"},
                        ),
                    ),
                    dbc.Col(
                        html.Div(
                            "One of three columns",
                            style={"background": "purple"},
                        ),
                    ),
                ],
            ),
        ]
    ),
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

Which produced the following result:
![image](https://user-images.githubusercontent.com/29842194/152213263-0969a516-b039-44a3-9e52-68de8de26776.png)

It was only after using 'inspect element' on both my app and your documentation page that I realised that it was because you use a modified 'row' class that has the attribute `margin-bottom=10px`.

Could this be better explained in the documentation please? I spent a long time trying to figure this out and I'd be surprised if I were the only one.

Many thanks.

**Comment by NathanCummings** [comment]
That's great, and I appreciate you responding so quickly!

**Comment by tcbegley** [comment]
Added a note, thanks again for flagging.
