### ISSUE TITLE
dbc spinner debounce

### ISSUE THREAD

**Issue by VassuRaw** [facultyai/dash-bootstrap-components#799]
I cannot find debounce attribute in dbc spinner in latest release of dbc.
My spinner is flickering when used in chained callback.

**Comment by tcbegley** [comment]
Hi @VassuRaw 

The `debounce` prop was renamed in #696 to `delay_hide` since we added a new prop `delay_show`. `delay_hide` should work the same way as `debounce`, let me know if you have any issues.
