### ISSUE TITLE
`readonly` attribute for `Input`.

### ISSUE THREAD

**Issue by Jerry-Ma** [facultyai/dash-bootstrap-components#816]
- dash version: `2.0.0`
- dash-bootstrap-components version: `1.0.2`
- components affected by bug: `Input`
### What is happening?

* `Input` does not have `readonly` boolean attribute like `Textarea`
* `Input` has `plaintext` boolean attribute which is stated to make the input readonly but not.

### What should be happening?

* `Input` provides `readonly` kwarg to make it readonly if set to True.
* Revise the documentation to show the use of `plaintext` and `readonly`

**Comment by tcbegley** [comment]
Hi @Jerry-Ma 

Sorry for the slow response, I just opened #833 to add this, will be available in the next release.

**Comment by tcbegley** [comment]
This is currently available in the latest beta

```
pip install dash-bootstrap-components==1.1.0b1
```

Let me know how you get on if you try it.

**Comment by Jerry-Ma** [comment]
Just gave it a try. It works! Thank you for the fix. I'll leave it to you to close the issue now or later, in case you wanna keep it open until the release of 1.1.0.

**Comment by tcbegley** [comment]
Great, thanks for confirming! Working on a few other changes for 1.1.0 but hopefully we can make a full release soon.
