### ISSUE TITLE
Support for wildcard data-* attribute

### ISSUE THREAD

**Issue by vogloblinsky** [facultyai/dash-bootstrap-components#817]
Like in Dash (https://github.com/plotly/dash/pull/237), it could be nice to implement this feature.

I need to include special attribute for E2E tests, like `data-cy="home-card"`

Thanks

**Comment by tcbegley** [comment]
Hi @vogloblinsky 

Thanks for raising this. The reason this hasn't been added (as is the case for dash-core-components) is that the `data-*` and `aria-*` attributes need to be attached to a specific element in HTML, and for higher-level components such as those in dash-bootstrap-components and dash-core-components it's not always obvious which element to choose as a single component is composed of many HTML elements. The root might be a sensible default, but I can certainly think of cases where that is not obviously the right answer.

Very happy to have my thinking on this challenged if you disagree!

As a potential workaround, have you considered using a `html.Div` or `html.Span` to wrap the component of interest and then targetting that with your Cypress tests? Might not work in all cases, but it might get you some of the way there.

**Comment by nirvana-msu** [comment]
This is rather frustrating as many, if not most, componenets actually *do* map one-to-one to an HTML tag (i.e. they just wrap a tag with the right bootstrap classes), or at least there is a tag that is most obviously associated with a component.
