### ISSUE TITLE
Add a 'clear' function for dbc.Select

### ISSUE THREAD

**Issue by aboyher** [facultyai/dash-bootstrap-components#820]
As far as I can tell, there is no way to clear a selected option from dbc.Select. While I prefer it's aesthetic to dcc.Dropdown and can overlook it's slight lag in performance, not being able to clear a selection makes the component unusable for me. It would make this component much better if this functionality were added.

**Comment by tcbegley** [comment]
Hi @aboyher 

Do you mean you would like to be able to clear it with a callback (e.g. by setting `value=None`) or that there should be an icon the user can use to clear it from the UI?

If the former, I thought this should be possible, if it isn't then it's a bug we should fix.

If the latter, it's probably not something we can fix. The `Select` component is just rendering a stylised HTML `<select>` element, which [doesn't have the capability](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) of being cleared from the UI. 

Anyway, let me know which of these you mean, and if you can share screen shots or code snippets demonstrating the issue that would be helpful.

**Comment by tcbegley** [comment]
The latest version of dash-bootstrap-components lets you clear a `Select` component by returning `None` from a callback. See #829 for some more details.

As discussed above, the underlying `<select>` element doesn't support anything more complicated unfortunately.
