### ISSUE TITLE
content_class_name attribute doesn't work for dbc.Modal

### ISSUE THREAD

**Issue by ethanbeaupre** [facultyai/dash-bootstrap-components#821]
- dash version: `#2.0.0`
- dash-bootstrap-components version: `#1.0.0`
- components affected by bug: dbc.Modal()

### What is happening?

content_class_name="custom-modal-content" does not update any styling to modal-content

### What should be happening?

content_class_name="custom-modal-content" should update modal-content styling based off of the custom-modal-content class

### Code
```python
dbc.Modal(id="custom-modal",
    is_open=False,
    content_class_name="custom-modal-content"
),
```
.css
.custom-modal-content {
  width: 60%;
  border-radius: 5px;
}

**Comment by tcbegley** [comment]
This has been fixed in the latest version of dash-bootstrap-components

```
pip install -U dash-bootstrap-components
```
