### ISSUE TITLE
Little issue with "inverse" parameters on dbc.Card

### ISSUE THREAD

**Issue by rtadewald** [facultyai/dash-bootstrap-components#823]
- dash version: `#2.0.0`
- dash-bootstrap-components version: `#1.0.2`
- components affected by bug: Card Component

### What is happening?

Hello, guys. First of all, thank you all for the great job. I simply love the library.

With that being said, I'm facing a small issue related to use of the `inverse` parameter in the Card component. It's not changing the color the way it should.

Here's my code:
[Captura de Tela 2022-03-14 às 13 54 42](https://user-images.githubusercontent.com/22618324/158221920-d826b9e4-a268-4b8c-8227-516ef967fce1.png)

And here's what I'm getting:
![Captura de Tela 2022-03-14 às 13 55 42](https://user-images.githubusercontent.com/22618324/158222083-915d5355-b298-4e25-80fd-7a230aebffd1.png)

Even if I try to write "inverse=False", "inverse=True" or change the Bootswatch theme in the app section, I keep seeing a white Card.

Thank you so much.

**Comment by tcbegley** [comment]
That's very odd... I have installed exact same versions of dash packages as you and am not seeing it this end.

Could you look at the text in the inspector / developer tools and see if you can find out where the text color styles are coming from?

**Comment by rtadewald** [comment]
Ah, I see. That's my fault, I'm sorry. I had an old style.css inside my assets, and he's the one replacing the code. I'm so sorry.
Thanks for your help!
