### ISSUE TITLE
Some inputs not styled correctly when using dark theme

### ISSUE THREAD

**Issue by kasuteru** [facultyai/dash-bootstrap-components#827]
- dash version: `#2.0.0`
- dash-bootstrap-components version: `#1.0.1`
- components affected by bug:
  - Input
  - Select

### What is happening?

When selecting dark theme (Cyborg, Darkly) these components are not styled correctly.

### What should be happening?

White background, black text.

### Code

```python
import dash
import dash_html_components as html
import dash_bootstrap_components as dbc

app = dash.Dash()
app.config.external_stylesheets = [dbc.themes.DARKLY]

app.layout = html.Div(children=[
    html.H1(children='Hello Dash'),
    html.Br(),
    dbc.Input(id="run-namefield", type="text", placeholder="Run Name"),
    html.Br(),
    dbc.Select(id='run-relpath-y', placeholder="Select y file")
])

app.run_server(debug=True)
```

Stackoverflow thread: https://stackoverflow.com/questions/71500789/dash-bootstrap-components-some-inputs-not-styled-correctly-when-using-dark-them

![image](https://user-images.githubusercontent.com/16296708/158642462-12dec6e3-95d6-4b25-9a8e-e1c9c49449e8.png)

**Comment by kasuteru** [comment]
Thank you for your answer. I can indeed confirm that this seems to be fixed in the newest version, therefore I will close this thread.

Side-note: I was using a company environment where versions are fixed. After updating DBC, it looks good, but I am now getting lots of other errors. So I will have to see what I actually use in the end :-)

**Comment by zndr27** [comment]
This issue is occurring in the current release: 1.4.1

**Comment by algotr34** [comment]
occurs also in the latest version: dash-bootstrap-components 1.5.0, but only when running it inside VS Code Jupyter notebook.
the dcc.Dropdown and dbc.Select are not dark mode, even if i add a dark theme:
app = Dash(__name__, external_stylesheets=[dbc.themes.DARKLY])

When I run the same code as a standalone .py file, it works and shows dark mode. so the issue is only inside Jupyter.

**Comment by zndr27** [comment]
Still occurring in 1.6.0

**Comment by AnnMarieW** [comment]
Hi @zndr27 
Looks fine to me.  Check it out here:
https://py.cafe/amward/dash-input-selector

**Comment by zndr27** [comment]
I am running Dash in Jupyter rather than a stand-alone script. Could you see if you can recreate the issue in jupyter with the Darkly theme?

**Comment by AnnMarieW** [comment]
can you check your dependencies? 
```
print(dbc.themes.DARKLY)
```

should show:

https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/darkly/bootstrap.min.css
