### ISSUE TITLE
Select.placeholder not updating despite being defined

### ISSUE THREAD

**Issue by aiqc** [facultyai/dash-bootstrap-components#829]
As shown in the callback screenshots below, a callback updates the Select.value to None and there is a Select.placeholder defined. However, the placeholder is not displayed.

The placeholder does show initially, but does not update if the value later becomes None.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/74990642/159497257-6a93389a-4caf-4b48-b44a-4278e24890ff.png">

<img width="737" alt="image" src="https://user-images.githubusercontent.com/74990642/159497316-d4b43492-1339-4c41-a519-ff6076aa7a95.png">

^ the bottom left dropdown is not showing the placeholder

---

```
dash: 2.2.0
dash-bootstrap-components: 1.0.3
```

### Code

```python
# your code here
```

### Error messages

No errors.

**Comment by tcbegley** [comment]
Hey @aiqc

Thanks for raising this. It is currently possible to clear the select / revert to the placeholder by returning an empty string from the callback, see the below example. I agree it would make sense for `None` to also clear the select. Let me think about whether it would be possible to change that behaviour. We are slightly constrained by the fact that `<select>` elements in HTML are somewhat limited anyway.

```python
import dash_bootstrap_components as dbc
from dash import Dash, html, Input, Output, no_update

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Select(
            id="select",
            options=[
                {"label": f"Item {i}", "value": str(i)} for i in range(1, 11)
            ],
        ),
        dbc.Button("Reset", id="button"),
        html.P(id="output"),
    ],
    className="p-5",
)


@app.callback(Output("output", "children"), Input("select", "value"))
def return_value(value):
    return value


@app.callback(Output("select", "value"), Input("button", "n_clicks"))
def reset(n):
    if n:
        return ""
    return no_update


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by aiqc** [comment]
Thank you so much for the clue about the empty string. Even updating the documentation about `placeholder` would be a win

"""
placeholder (string | number; optional): A hint to the user of what can be entered in the control . The placeholder text must not contain carriage returns or line-feeds. Note: Do not use the placeholder attribute instead of a <label> element, their purposes are different. The <label> attribute describes the role of the form element (i.e. it indicates what kind of information is expected), and the placeholder attribute is a hint about the format that the content should take. There are cases in which the placeholder attribute is never displayed to the user, so the form must be understandable without it.
"""

**Comment by tcbegley** [comment]
The latest version of dash-bootstrap-components allows you to clear the `Select` by returning `None` from the callback.

```
pip install -U dash-bootstrap-components
```
