### ISSUE TITLE
Cursor jumps to end of input when edited

### ISSUE THREAD

**Issue by ln-P** [facultyai/dash-bootstrap-components#830]
Please fill out the below information as much as possible.

- dash version: `1.21.0`
- dash-bootstrap-components version: `0.13.0`
- components affected by bug: `Input`

### What is happening?
Cursor jumps to the end of the text when input is edited.
![screen-capture (1)](https://user-images.githubusercontent.com/8012343/159531423-5c4b6c8a-b4ec-4edd-9dab-4462e6c0ba0e.gif)

### What should be happening?
Cursor should stay in the place where text is edited.

### Code

```python
import dash
import dash_html_components as html
import dash_bootstrap_components as dbc

import flask
import os

server = flask.Flask('app')
server.secret_key = os.environ.get('secret_key', 'secret')

app = dash.Dash('app', server=server)

app.layout = html.Div([
    html.H1('Simple input box'),
                    dbc.Input(
                        id="keyword-entry",
                        placeholder="Enter search term here",
                        type="text",
                        value="",
                        n_submit = 0
                    ),
], className="container")

if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by tcbegley** [comment]
Hi @ln-P 

This bug has been fixed in newer versions of dash-bootstrap-components. You can either update to the latest version

```sh
pip install -U dash-bootstrap-components
```

or, if you're not ready to upgrade to v1 yet, you can do 

```sh
pip install -U "dash-bootstrap-components<1"
```

(version 0.13.1 doesn't have this issue)

**Comment by tcbegley** [comment]
No apology needed, thanks for reporting!
