### ISSUE TITLE
Accordion items always open

### ISSUE THREAD

**Issue by VictorLFandino** [facultyai/dash-bootstrap-components#834]
Hello

I wonder if its possible to implement an accordion where items do not close when others are opened. The idea is here:
[https://getbootstrap.com/docs/5.0/components/accordion/#always-open](https://getbootstrap.com/docs/5.0/components/accordion/#always-open)

Thank you very much

**Comment by tcbegley** [comment]
Hi @VictorLFandino 

Great suggestion, was unaware of this functionality in Bootstrap. I can see it's supported in `react-bootstrap` (on which this library is built) so it should be possible to add.
