### ISSUE TITLE
Add newer features supported by React-Bootstrap

### ISSUE THREAD

**Issue by glsdown** [facultyai/dash-bootstrap-components#844]
React Bootstrap have a number of features that we don't currently include. It would be good to add them:

#### Features
- [x] [Numbered List Groups](https://react-bootstrap.github.io/components/list-group/#numbered) (#895 )
- [x] [Stacks](https://react-bootstrap.netlify.app/layout/stack/#stacks) (#897 )
- [x] [Horizontal Collapse Animation](https://react-bootstrap.netlify.app/utilities/transitions/#horizontal) (#896 )
- [ ] [Custom Accordion Toggles](https://react-bootstrap.github.io/components/accordion/#custom-accordions)
- [x] [Placeholder](https://react-bootstrap.github.io/components/placeholder/) (#899)

#### Examples
- [ ] Combining the Navbar and Offcanvas components to make a [navigation system](https://react-bootstrap.github.io/components/navbar/#offcanvas).

**Comment by tcbegley** [comment]
Nice. I don't know if the custom toggles will be possible as it seems it requires you pass in a function (which we can't replicate with Dash). Also not so sure about stacks. Feels like deviation from core Bootstrap functionality?

**Comment by glsdown** [comment]
That might be why I originally left the custom toggles out of the Accordion.

Stacks are in Bootstrap v5: https://getbootstrap.com/docs/5.1/helpers/stacks/

**Comment by tcbegley** [comment]
I stand corrected! Ok, let's put them in.
