### ISSUE TITLE
Behaviour of `dbc.Input` with `debounce=True` differs in Chrome and Firefox

### ISSUE THREAD

**Issue by vsisl** [facultyai/dash-bootstrap-components#855]
### What is happening?
I noticed that when using 

```python
dcc.Input(
  debounce=True,
  type='number',
)
```

the component behaves differently in Chrome and in Firefox. See the recordings below. 

#### Chrome:

https://user-images.githubusercontent.com/28457179/168772810-926820af-e519-4679-b89d-72dcf65f862d.mov

#### Firefox:

https://user-images.githubusercontent.com/28457179/168772853-913d60ac-220b-48b2-bcfc-4b36f8125f3a.mov

### What should be happening?
I would expect the same behaviour in all browsers.

### MWE:
```python
from dash import Dash, Input, Output, State
import dash_bootstrap_components as dbc

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container([
    dbc.Row([
        dbc.Col([
            dbc.Input(
                id='input',
                debounce=True,
                type='number',
                value=1,
                min=1,
                max=10,
                step=1
            )
        ]),

        dbc.Col([
            dbc.Button(
                children='Read Input Value',
                id='button',
            )
        ]),

        dbc.Col(id='output')
    ]),
])


@app.callback(
    Output('output', 'children'),
    Input('button', 'n_clicks'),
    State('input', 'value'))
def read_input_value(n_clicks, input_value):
    return input_value


if __name__ == '__main__':
    app.run_server()
```

### Environment:
platform: macOS, linux
browsers: Chrome, Firefox
package versions:

```
dash                      2.3.1                    pypi_0    pypi
dash-bootstrap-components 1.1.0                    pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
```

### Solution for my particular use-case:
Since I use `dbc.Input()` components only as `State`s for my callbacks and not as `Input`s. The solution for my case was as simple as setting `debounce=False`.

### NOTES:
1) `dcc.Input` behaves exactly the same as `dbc.Input`. 
2) This is issue related to #430

**Comment by tcbegley** [comment]
Hey @vsisl 

Thanks for the report and sorry for the slow response. I finally had a chance to look into this and it seems that the reason for the discrepancy is that Firefox does not give focus to the numeric input when the user clicks on the spin buttons (up / down arrows). This appears to be [a long standing issue with firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1012818).

I think unfortunately there's little we can do about this here, it's not specific to our code, just a slightly odd difference in behaviour between the two browsers.
