### ISSUE TITLE
Tooltip: Adding more properties

### ISSUE THREAD

**Issue by daviddavo** [facultyai/dash-bootstrap-components#857]
There are some properties not available when creating a component, like `animation` or `trigger`. It would be useful to make a tooltip with manual trigger, and then showing/hiding it using callbacks.

https://getbootstrap.com/docs/5.0/components/tooltips/

It would be more or less like using a [Popover](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/popover/)

**Comment by tcbegley** [comment]
Hi @daviddavo 

Thanks for the suggestion. It's certainly something we can look into. We'll just have to make sure whatever we do is backwards compatible with how the `Tooltip` currently works.

The `animation` prop should be easier to add I think, I'll investigate!

**Comment by tcbegley** [comment]
Hi again @daviddavo 

Turns out that adding both of these features is relatively straight forward, and I'm happy that we can do it without breaking existing apps.

Check out the pre-release for yourself

```sh
pip install dash-bootstrap-components==1.2.0rc1
```

And here's a simple example showing the new behaviour

```python
import dash_bootstrap_components as dbc
from dash import Dash, Input, Output, State

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Button("Tooltip with fade", id="fade-target", className="m-1"),
        dbc.Button(
            "Tooltip without fade", id="no-fade-target", className="m-1"
        ),
        dbc.Tooltip(
            "This is some content", id="tooltip", target="fade-target"
        ),
        dbc.Tooltip(
            "This is some content",
            id="no-fade-tooltip",
            target="no-fade-target",
            fade=False,
        ),
        dbc.Button(
            "Open tooltips", id="button", color="success", className="m-1"
        ),
    ],
    className="p-5",
)


@app.callback(
    [Output("tooltip", "is_open"), Output("no-fade-tooltip", "is_open")],
    Input("button", "n_clicks"),
    [State("tooltip", "is_open"), State("no-fade-tooltip", "is_open")],
)
def open_tooltips(n, is_open, no_fade_is_open):
    if n:
        return not is_open, not no_fade_is_open
    return is_open, no_fade_is_open


if __name__ == "__main__":
    app.run_server(debug=True)
```
