### ISSUE TITLE
Modal component does not apply zindex argument 

### ISSUE THREAD

**Issue by IanMichaelAsh** [facultyai/dash-bootstrap-components#865]
dash version 2.3.1
dash-bootstrap-components version: 1.1.0 (and 1.0.0)
Modal component

### What is happening?

Passing either a zindex or zIndex to dbc.Modal does not adjust the z-index of either the backdrop or the modal dialog itself.

There is also a minor documentation bug where the default z-index is stated as 1050, however the component is being rendered with a z-index of 1055.

### What should be happening?

The zindex argument should override the default z-index on the component for both the backdrop and dialog.

### Code

The example below based on the DBC docs renders the modal with a z-index of 1055 instead of 60000:
```
modal = html.Div(
    [
        dbc.Modal(
            [
                dbc.ModalHeader(dbc.ModalTitle("Header")),
                dbc.ModalBody("This is the content of the modal"),
                dbc.ModalFooter(
                    dbc.Button(
                        "Close", id="close", className="ms-auto", n_clicks=0
                    )
                ),
            ],
            id="modal",
            is_open=False,
            zindex="60000",
        ),
    ]
)
```

**Comment by glsdown** [comment]
Thanks for raising this @IanMichaelAsh . We'll take a look and let you know when a fix has been released.

**Comment by tcbegley** [comment]
Hey @IanMichaelAsh 

You can try the latest pre-release, it should resolve the issue:

```
pip install dash-bootstrap-components==1.2.0rc2
```

Here's a simple test app that worked for me

```python
import dash_bootstrap_components as dbc
from dash import Dash, Input, Output, State

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Button("Open Modal", id="button"),
        dbc.Modal(
            [
                dbc.ModalHeader("Modal", close_button=True),
                dbc.ModalBody("Some modal content"),
            ],
            id="modal",
            zindex=-1,
        ),
    ],
    className="p-5",
)


@app.callback(
    Output("modal", "is_open"),
    Input("button", "n_clicks"),
    State("modal", "is_open"),
)
def toggle(n, is_open):
    if n:
        return not is_open
    return is_open


if __name__ == "__main__":
    app.run_server(debug=True)
```

Let me know how you get on!

**Comment by IanMichaelAsh** [comment]
Hi @tcbegley,

Tested in my project and agree the issue is resolved in rc2.

Thanks
Ian
