### ISSUE TITLE
Create new Dash Bootstrap Component within a Clientside Callback

### ISSUE THREAD

**Issue by janbieck** [facultyai/dash-bootstrap-components#867]
Hi,

How can I create a Dash Bootstrap Component in a clientside callback? I haven't found anything in the documention regarding this issue. 

Best,

Jan

**Comment by tcbegley** [comment]
Hi @janbieck 

I've never seen people do this before, couldn't see anything on the Dash documentation, nor the Plotly forum.

That said, I tried returning components from a regular callback and then spying on the response in the network tab of my browser's developer tools. It seems you can simply return an object describing the components to be rendered and Dash will render them for you.

Check out this example:

```python
import dash_bootstrap_components as dbc
from dash import Dash, Input, Output, html

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Button("Click", id="button"),
        html.Div(id="output", className="mt-3"),
    ],
    className="p-5",
)

app.clientside_callback(
    """
    function(n) {
        if (n) {
            return {
                props: {children: "This is an alert", color: "success"},
                type: "Alert",
                namespace: "dash_bootstrap_components"
            };
        }
        return {};
    }
    """,
    Output("output", "children"),
    Input("button", "n_clicks"),
)


if __name__ == "__main__":
    app.run_server(debug=True)
```

Definitely recommend prototyping anything more complicated with a regular callback, looking at the response to calls to `_dash-update-component` using the developer tools.

**Comment by janbieck** [comment]
Thank you @tcbegley, that's an awesome idea, I haven't thought of that approach.
