### ISSUE TITLE
dbc.Select searchable property

### ISSUE THREAD

**Issue by aGitForEveryone** [facultyai/dash-bootstrap-components#875]
dcc.Dropdown offers the searchable property. Can that also be added to dbc.Select? That would allow us to have searchable dropdowns that play nicely in the dbc landscape. For example, dcc.Dropdown doesn't play nicely with dbc.InputGroup.

**Comment by tcbegley** [comment]
Hey @aGitForEveryone 

Unfortunately `dbc.Select` is based on a simple HTML select element and does not support this functionality. `dcc.Dropdown` is based on a far more complicated React component that supports the extra features like searching.

My [dash-bootstrap-css project](https://github.com/tcbegley/dash-bootstrap-css) might help with using a `Dropdown` in an `InputGroup`

**Comment by aGitForEveryone** [comment]
Indeed I found the dash-bootstrap-css project and that did work for my dashboard. The only problem being that it is a bit more cumbersome to set up. First you have to set up the css files, and then you have to wrap the `dcc.Dropdown` in an `html.Div` element with the correct class set up, and then I had to fix the scaling of the dropdown. Because under the default setting the dropdown was squashed horizontally. In the end I found that this worked:
```
my_input_group_dropdown = html.Div(my_dcc_dropdown, className='dash-bootstrap', style={'flex': 9999})
```
And in the end the dropdown is displayed with rounded egdes instead of the square edges that the `dbc.Select` has in the inputgroup. And of course, the `dcc.Dropdown` doesn't have the invalid/valid property that works with the `dbc.FormFeedback`.

Finally, I understand your point and I fully accept that this is just what it is. And above settings make it work at least in some way, so I am happy about that.
