### ISSUE TITLE
dbc.Accordion: Expose AccordionButton for CSS class_name redefinition

### ISSUE THREAD

**Issue by SterlingButters** [facultyai/dash-bootstrap-components#888]
I would like to individualize the styles for each button in the Accordion but it doesn't seem like I can without access to the button specifically.

**Comment by glsdown** [comment]
Hi @SterlingButters thanks for reaching out and apologies for how long it has taken to get back to you. I will be looking into this issue, but as was raised in #844 we have a suspicion that it may not be possible to implement this due to the way that dash allows us to interact with components.

**Comment by SterlingButters** [comment]
@glsdown No problem! Yeah I mean unfortunately I don't know basically anything about react but after I realized that the accordion items were just buttons with fancy styling, I thought for sure it would be possible to style them individually by exposing the styles as a component property
