### ISSUE TITLE
HTML in DropdownMenu label

### ISSUE THREAD

**Issue by jesse-r-s-hines** [facultyai/dash-bootstrap-components#890]
`DropdownMenu.label` is a string prop, and so prevents putting any HTML in the dropdown toggle. If `label` could accept a node array we'd be able to put things such as icons in the dropdown toggle, e.g.

```python
dbc.DropdownMenu(
    children=[
        dbc.DropdownMenuItem("Item 1", href="#"),
        dbc.DropdownMenuItem("Item 2", href="#"),
    ],
    label=[
        html.I(className="fa-solid fa-house"),
       "Home",
    ],
)
```

**Comment by tcbegley** [comment]
Hi! Sorry for slow response. This is now possible in the latest version of dash-bootstrap-components.

Let me know if you have any issues when you try it out.

```
pip install -U dash-bootstrap-components
```
