### ISSUE TITLE
dbc.Tabs does not have the expected behavior

### ISSUE THREAD

**Issue by nikky78** [facultyai/dash-bootstrap-components#893]
- dash version: `2.6.0`
- dash-bootstrap-components version: `1.2.1`

### What is happening?

![image](https://user-images.githubusercontent.com/29562101/194540253-40b194c7-7d2b-4ae8-a5ef-abc63bd101a6.png)

### What should be happening?

I was expecting the tabs to be horizontal, plus there is only 2 graphs per tabs. So the other graphs below, should only be displayed when the corresponding tab is open. All 6 graphs are displayed instead.

### Code

```
x=[1, 2, 3]
y=[4, 5, 6]
fig = make_subplots(
    subplot_titles=['Equity', 'Exposure'],
    rows=1, cols=2
)

fig.add_scatter(
    x=x, y=y,
    row=1, col=1
)

fig.add_scatter(
    x=x, y=y,
    row=1, col=2
)

fig.update_layout(
    title_text="Statistics",
    xaxis_title="Date",
    yaxis_title="Equity",
    xaxis2_title="Date",
    yaxis2_title="Exposure",
    showlegend=False
)
    
app.layout = dbc.Container(
    [
        html.H1("Strategy Dashboard"),
        
        dbc.Tabs(
            [
                dbc.Tab(
                    dbc.Card(
                        dbc.CardBody(
                            [
                                html.H2(strat),
                                dcc.Graph(id=f'graphs-{strat}', figure=fig)
                            ]
                        )
                    ), 
                    label=strat,
                    tab_id=strat,
                )
                for strat in strats
            ],
            id="tabs",
            active_tab=strats[0],
        ),
    ],
    fluid=True,
)
```

**Comment by tcbegley** [comment]
It looks to me like the Bootstrap CSS isn't getting linked properly. Are you doing something like

```python
app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])
```

when you instantiate the `app` object?

If you are but you're seeing the above, it's possible that external CSS is being blocked by a firewall, in which case you could try downloading Bootstrap CSS and placing it in your apps `assets/` folder to be linked locally.

**Comment by nikky78** [comment]
Indeed, it was the external_stylesheets that I forgot! Thank you!
