### ISSUE TITLE
How do you render Dash components inside of the Bootstrap components?

### ISSUE THREAD

**Issue by gaboc623** [facultyai/dash-bootstrap-components#901]
Hello!

I am porting over MUI's DataGrid to Dash and want to pass any kind component (ie dbc.Button, dbc.Input, etc) to fields in that table and then have access to them in Dash to wire callbacks to them. As of now, I am unpacking the object into its props using a function from the dash-extensions package (https://github.com/thedirtyfew/dash-extensions-js/blob/master/index.js), and then using DataGrid's renderCell (https://mui.com/x/react-data-grid/column-definition/#rendering-cells) call in the column to display those props as a React element; this works fine.

The issue comes when wiring a callback to the element in the table: Dash does not know about the element in the table and gives an "ID is not found" error. If I inspect the page the element is there and it has the correct ID. 

I was wondering if someone would be able to talk me through how you all unpack components passed to other components to see if there is something I am missing that would help me unlock that wiring component. Happy to share any code if that would help as well. 

Thank you!

**Comment by tcbegley** [comment]
Hi @gaboc623 

I'm not so familiar with unpacking components, but afaik it should work the same way for Bootstrap components as it does for other Dash components. I.e. if you can get it to work for `dcc.Button` and `dcc.Input` it should be the same for `dbc.Button` and `dbc.Input`. Have you tried with other components, is it specifically Bootstrap components that aren't working for you?

If the problem you have is not specific to Bootstrap components then I suggest asking a question on the dash-extensions repo, as they'll likely be much better placed to help you.

**Comment by gaboc623** [comment]
Thanks for the quick response! 

It is not isolated to dbc components, it also does not wire up with dcc or Dash HTML components though those do render fine. 

I will ask the question there, thanks!
