### ISSUE TITLE
Toast component breaks multi-page navigation

### ISSUE THREAD

**Issue by TomFraser** [facultyai/dash-bootstrap-components#903]
- dash version: `#2.6.0`
- dash-bootstrap-components version: `#1.2.1`
- components affected by bug: dbc.Toast

### What is happening?

If a Toast with a dismissal duration is open, and the user navigates to a new page, the user is redirected to the previous page. Reproduction of #850.

### What should be happening?

When the user navigates to a new page, the Toast component should be destroyed / dismissal timer ended

### Code

A reproduction repo can be found at: https://github.com/TomFraser/dbc-toast-reload

main.py
```python
app.layout = html.Div([
    dbc.NavbarSimple(
        children=[
            dbc.NavItem(dbc.NavLink("Page 1", href="/page1")),
            dbc.NavItem(dbc.NavLink("Page 2", href="/page2")),
        ], brand="Navbar"
    ),
    html.Div([
        dash.page_container
    ])
])

if __name__ == '__main__':
    app.run_server(debug=True, host="0.0.0.0")
```

page1.py
```python
dash.register_page(__name__, path="/page1")

layout = html.Div([
    html.P("Page 1"),
    html.H5("Steps to reproduce:"),
    html.P("1. Trigger Toast with below button"),
    html.P("2. Navigate to Page 2 before toast dismisses"),
    dbc.Button("Trigger Toast", id="toast_trigger", n_clicks=0),
    html.Div([
        dbc.Toast(f"Some words",
                  header=f"Header",
                  dismissable=True,
                  icon="success",
                  duration=4000,
                  is_open=False,
                  id="toast")
    ])
])


@callback(
    Output("toast", "is_open"),
    Input("toast_trigger", "n_clicks")
)
def trigger_toast(n_clicks):
    if n_clicks:
        return True
```

page2.py
```python
dash.register_page(__name__, path="/page2")

layout = html.Div([
    html.P("Page 2"),
    html.P("Wait for it...")
])
```

### Error messages

No error message is given in terminal.
`component is undefined` errors in dash debug ui

**Comment by tcbegley** [comment]
Thanks for raising this @TomFraser 

I think this is something to do with Dash Pages, which I'm not super familiar with, because the app below does not appear to have the same problem (please check your end also).

@AnnMarieW do you have any ideas what might be happening internally in Dash Pages that would cause the behaviour to be different to my example below?

```python
import dash_bootstrap_components as dbc
from dash import Dash, dcc, html, Output, Input

app = Dash(
    external_stylesheets=[dbc.themes.BOOTSTRAP], suppress_callback_exceptions=True
)

app.layout = html.Div(
    [
        dcc.Location(id="url", pathname="/page-1"),
        dbc.NavbarSimple(
            dbc.Nav(
                [
                    dbc.NavLink("Page 1", href="/page-1"),
                    dbc.NavLink("Page 2", href="/page-2"),
                ]
            )
        ),
        dbc.Container(id="layout", className="p-3"),
    ]
)


page_1_layout = html.Div(
    [
        dbc.Button("Launch Toast", id="button"),
        dbc.Toast(
            "Some words",
            header="Header",
            dismissable=True,
            icon="success",
            duration=4000,
            is_open=False,
            id="toast",
        ),
    ]
)

page_2_layout = html.Div([html.H2("This is the other page"), html.P("Wait for it...")])


@app.callback(Output("toast", "is_open"), Input("button", "n_clicks"))
def trigger_toast(n_clicks):
    if n_clicks:
        return True
    return False


@app.callback(Output("layout", "children"), [Input("url", "pathname")])
def set_layout(pathname):
    if pathname == "/page-1":
        return page_1_layout
    elif pathname == "/page-2":
        return page_2_layout
    return html.H2("404: not found")


if __name__ == "__main__":
    app.run_server(debug=True)
```

**Comment by AnnMarieW** [comment]
Hey @tcbegley,

I think it's true that this is a Dash issue and not a dbc bug.  But it's not just an issue with  Pages.  If you change your app to put the layout in different files, you will see the same error.  For example, here's the main app.py file:

```
import dash
from dash import dcc, html, Input, Output
import dash_bootstrap_components as dbc

from pages import page1, page2


app = dash.Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP], suppress_callback_exceptions=True,
                title="Toast Example", )

app.layout = html.Div([
    dcc.Location(id="url"),
    dbc.NavbarSimple(
        children=[
            dbc.NavItem(dbc.NavLink("Page 1", href="/page1")),
            dbc.NavItem(dbc.NavLink("Page 2", href="/page2")),
        ], brand="Navbar"
    ),
    html.Div(id="layout")
])

@app.callback(Output("layout", "children"), [Input("url", "pathname")])
def set_layout(pathname):
    if pathname == "/page1":
        return page1.layout
    elif pathname == "/page2":
        return page2.layout
    return html.H2("404: not found")


if __name__ == '__main__':
    app.run_server(debug=True, host="0.0.0.0")

```

The mystery is -- why does it work in your example when the whole app is in one file?  I would expect to see the same error since the Toast component is no longer in the layout. Any ideas?

**Comment by tcbegley** [comment]
Hmm, with your `app.py` and with the layouts in the other files I'm still not seeing the same issue. Is there anything else going on in your `page1.py` or `page2.py` not including the toast callback and the layout definition?

**Comment by AnnMarieW** [comment]
The page1.py and page2.py are the same except that it doesn't register the page.

I did a PR on @TomFraser 's github just to make it easier to check it out:

https://github.com/TomFraser/dbc-toast-reload/pull/1/files

**Comment by AnnMarieW** [comment]
I also ran into the same issue trying to use the new background callbacks in a multi-page app.  You can find details in this example:
https://github.com/AnnMarieW/dash-multi-page-app-demos/blob/main/multi_page_cache_background_callback/app.py

However, I'm not sure how this workaround would work with the Toast component.

**Comment by tcbegley** [comment]
Whatever is going on is super weird... If I change `page1.py` in your PR to the below code it works. Those changes to me seem entirely superficial, I've just reduced the complexity of the layout. The relevant components are there and the callback in unchanged.

Is Dash trying to do something smart like cache parts of the layout for snappier multi-page navigation? My best guess is that something is preventing the `Toast` from getting properly unmounted?


```python
import dash
import dash_bootstrap_components as dbc
from dash import html, Output, Input, callback


layout = html.Div(
    [
        dbc.Button("Trigger Toast", id="toast_trigger", n_clicks=0),
        dbc.Toast(
            f"Some words",
            header=f"Header",
            dismissable=True,
            icon="success",
            duration=4000,
            is_open=False,
            id="toast",
        ),
    ]
)


@callback(Output("toast", "is_open"), Input("toast_trigger", "n_clicks"))
def trigger_toast(n_clicks):
    if n_clicks:
        return True
```

**Comment by AnnMarieW** [comment]
Oh, that's so strange.  I added a page3 to the PR to make it easier to run.  I'll see if this is a know issue in Dash

**Comment by T4rk1n** [comment]
Most likely that bootstrap Toast are rendered outside the dash/react layout tree, the dismiss handler will still be called in onClose in that case when navigating with pages apps.

A possible solution would be to use the custom event on page navigation that dash sends to somehow invalidate the dismiss call. You can listen to the event like we do in dcc.Location: https://github.com/plotly/dash/blob/a834e5a52e083c90fff85dfc8d338bb4d8df3ba1/components/dash-core-components/src/components/Location.react.js#L111-L114

But it should be noted that the actual dbc component would actually be unmounted, so I am not sure you can use a state or ref to keep track.

The background callback is another issue that is fixable in the renderer.

**Comment by tcbegley** [comment]
Hi all, thanks for the discussion on this and sorry for going quiet for a few weeks. Happy to say this should be resolved in the latest version.

```
pip install -U dash-bootstrap-components
```
