### ISSUE TITLE
Example "Radioitems asButtongroups" doesn't work

### ISSUE THREAD

**Issue by Ento0n** [facultyai/dash-bootstrap-components#909]
Hello,

I tried recreating the example ["Radioitems as Buttongroups"](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/button_group/) and it simply doesn't work. I removed ".radio-items" in the css which changed a bit but doesn't give the wanted result.

As probably is clear now I know no css or js, which is why I will use something different instead. This is a simple reminder that the example of the wabpage doesn't work.

Greetings,
Toni

**Comment by tcbegley** [comment]
Hi @Ento0n,

Thanks for raising this. I just tried the example locally and it was working fine. Could you say a bit more about what you tried and what wasn't working?
