### ISSUE TITLE
DBC buttons do not properly work with outline styles

### ISSUE THREAD

**Issue by astrowonk** [facultyai/dash-bootstrap-components#911]
Before opening:

Please fill out the below information as much as possible.

dash==2.7.1
dash-bootstrap-components==1.2.1

`dbc.Button` is confounding me and not styling properly to outline.

### What is happening?

I create a button, and change className = `btn btn-outline-primary`. The button does not look like an outline. It looks like this:

![Screenshot 2022-12-21 at 3 33 35 PM](https://user-images.githubusercontent.com/13702392/208997957-b0e08135-e405-4b13-a4d0-a6cc4ab8144f.png).

Upon inspecting the HTML in Safari/Chrome, the style of the button is not `btn btn-outline-primary` but instead `btn btn-outline-primary btn btn-primary` adding on the superfluous `btn btn-primary` though I did not specify it. 

### What should be happening?

The button should look like an outline. If I use web browser dev tools to remove the extra class name text and set it to `btn btn-outline-primary`.

The example below is also [here on github](https://github.com/astrowonk/emoji_finder/blob/main/example_bug.py)

### Code

```python
import dash_bootstrap_components as dbc
from dash import html

table_header = [
    html.Thead(html.Tr([html.Th("First Name"),
                        html.Th("Last Name")]))
]

from dash import Dash, dcc, html
from dash.dependencies import Input, Output

app = Dash(
    __name__,
    external_stylesheets=[dbc.themes.BOOTSTRAP, dbc.icons.BOOTSTRAP],
)


button_class = 'btn btn-outline-primary'


def generate_row(k):
    return html.Tr([
        html.Td(
            dbc.Button(children=f"No Outline {i}_{k}",
                       id=f"{i}_{k}",
                       className=button_class)) for i in range(2)
    ])


table_body = [html.Tbody([generate_row(k) for k in range(2)])]

table = dbc.Table(table_header + table_body, bordered=True)

app.layout = dbc.Container(
    [table, dbc.Button("Not working", class_name=button_class)])

if __name__ == "__main__":
    app.run_server(debug=True)```

### Error messages

```bash
paste any error messages here
```

**Comment by tcbegley** [comment]
Hey @astrowonk 

Instead of setting the classnames manually, can you try setting `outline=True` in `dbc.Button`? That should give the desired effect.

**Comment by astrowonk** [comment]
@tcbegley If I turn off specifying a class name, and do `outline=True`, I get a style of ` btn btn-outline-undefined` which looks poor/wrong. Screenshot below:

![Screenshot 2022-12-28 at 4 00 32 PM](https://user-images.githubusercontent.com/13702392/209871438-ce4d9562-b2e6-4d56-aeea-47832f6c59ca.png)

I would like be able to define a size, class type (primary secondary etc) and outline (yes or no) in the classname to access the full range of button styles available in various bootstrap theme browsers, etc. Is that not possible?

**Comment by tcbegley** [comment]
Yes, you can specifying `color="success"` etc. for color, `outline=True` for outline styles, `size="sm"` for size. 

E.g. I get the following from the below code snippet

<img width="364" alt="image" src="https://user-images.githubusercontent.com/15220906/209873355-7bb83d21-0604-47ec-bc2d-d41fd97e0ba3.png">

```python
import dash_bootstrap_components as dbc
from dash import Dash

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Button("Default button", className="me-3"),
        dbc.Button(
            "Outline danger small",
            outline=True,
            color="danger",
            size="sm",
        ),
    ],
    className="p-5",
)

if __name__ == "__main__":
    app.run_server(debug=True)
```

There's loads more examples in the [documentation](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/button/)

**Comment by astrowonk** [comment]
😔 Wow, I am very sorry. I must have been looking at other examples from non-documentation sources. I don't know how I missed the keyword based colors/outline etc : I guess I skipped straight to bootstrap css class names and didn't look at the button documentation. The examples of course worked as one would expect. Thanks, and I'll close this issue.

**Comment by tcbegley** [comment]
No worries, glad you got it working 🙂
