### ISSUE TITLE
Dead simple-sidebar example link on website

### ISSUE THREAD

**Issue by grschneider-epam** [facultyai/dash-bootstrap-components#931]
### What is happening?

Webpage https://dash-bootstrap-components.opensource.faculty.ai/examples/simple-sidebar/ tries to link the example source code https://github.com/facultyai/dash-bootstrap-components/blob/main/examples/python/multi-page-apps/simple_sidebar.py - which is a 404.
### What should be happening?

Correct link would be https://github.com/facultyai/dash-bootstrap-components/blob/main/examples/python/templates/multi-page-apps/simple_sidebar.py - notice the "templates" folder compared to previous invalid link.

**Comment by tcbegley** [comment]
Thanks for reporting this @grschneider-epam. This is now fixed.
