### ISSUE TITLE
Accordion Item cannot render dynamic ID

### ISSUE THREAD

**Issue by slyin87** [facultyai/dash-bootstrap-components#935]
- dash version: `#2.8.1`
- dash-bootstrap-components version: `#1.3.1`
- components affected by bug: Accordion Item

### What is happening?

Accordion Item id not displaying when using MATCH PATTERN.

![image](https://user-images.githubusercontent.com/90740896/218358268-c22216ee-1534-4fdf-935a-0c43e3a4f711.png)

The id in html is [object Object]

### What should be happening?

The id should be something like id={"index":"some_index","type":"some_type"}

### Code

![image](https://user-images.githubusercontent.com/90740896/218358740-09ca63bd-d501-48da-abb1-2f3285704a65.png)

```python
dbc.AccordionItem(
            id = {
                'type': "the_type",
                'index': 'the_index'
            },
            title   = title,
            item_id = item_id,
        )
```

### Error messages

```bash
paste any error messages here
```

**Comment by tcbegley** [comment]
Hey @slyin87 

I just made a pre-release that should fix this issue. Please try it out and let me know if you have further issues.

```
pip install dash-bootstrap-components==1.3.2rc1
```

**Comment by slyin87** [comment]
Working per expected. Thank you
