### ISSUE TITLE
dbc.Select() not Displaying Options

### ISSUE THREAD

**Issue by pmartin3141** [facultyai/dash-bootstrap-components#956]
- dash version: `2.9.2`
- dash-bootstrap-components version: `1.4.1`
- components affected by bug: dbc.Select()

### What is happening?
Documentation for the dbc.Select component provides several input options for the "options" variable. See documentation for this variable below:

_options (list of dicts; optional): The options to display as items in the component. This can be an array or a dictionary as follows:_
_1. Array of options where the label and the value are the same thing - [string|number](https://dash-bootstrap-components.opensource.faculty.ai/docs/components/input/)_
_2. An array of options { "label": [string|number], "value": [string|number], "disabled": [bool] (Optional), "title": [string] (Optional) }_
_3. Simpler options representation in dictionary format. The order is not guaranteed. All values and labels will be treated as strings. {"value1": "label1", "value2": "label2", ... } which is equal to [ {"label": "label1", "value": "value1"}, {"label": "label2", "value": "value2"},... ]._

However, only one of these options seems to work which is the second, the "array of options" input.

When using the other input options, the select dropdown doesn't display any of the options, but is an empty dropdown.

### What should be happening?

The "options" variables of the dbc.Select() component should accept and displays inputs of lists of strings or integers.

### Code

This isn't a full code snippet, but it displays the case that works and doesn't.

```python
import dash_bootstrap_components as dbc
# This displays options in the Select dropdown component.
dbc.Select(options = [{'value': 0, 'label': 'option 1'}, {'value': 1, 'label': 'option 2'}, {'value': 2, 'label': 'option 3'}], id="display-select-partnum")
# This does not display any options but an empty component.
dbc.Select(options=['option 1' , 'options 2' , 'option 3'], id="display-select-partnum")

```

**Comment by tcbegley** [comment]
Hi @pmartin3141 

Apologies for the slow reply, I was on vacation for a couple weeks and then catching up with work.

I'm afraid I can't seem to reproduce the issue you report. Here's the code I tried and everything worked as expected. Could you run this and see what happens your end?

```python
import dash_bootstrap_components as dbc
from dash import Dash, Input, Output, html

app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    [
        dbc.Select(
            options=["option 1", "option 2", "option 3"],
            id="select",
        ),
        html.P(id="out", className="my-3"),
    ],
    className="p-5",
)


@app.callback(Output("out", "children"), Input("select", "value"))
def return_value(value):
    return value


if __name__ == "__main__":
    app.run_server(debug=True)
```

<img width="329" alt="image" src="https://user-images.githubusercontent.com/15220906/235311231-4676457d-60e2-4698-9707-2e86e7ea2557.png">

Here's the versions I ran with

```
dash                      2.9.3
dash-bootstrap-components 1.4.1
```

**Comment by tcbegley** [comment]
Closing due to lack of response, please re-open if you are still having issues.
