### ISSUE TITLE
dbc.Input no type = 'file'

### ISSUE THREAD

**Issue by slyin87** [facultyai/dash-bootstrap-components#965]
Hi,

Why is there no option to choose input type='file'?

HTML:
<input type = "file" name = "file" />

What is the alternative so that I can upload files to server besides using dcc.Upload and dash-uploader (too buggy).

**Comment by tcbegley** [comment]
Hi @slyin87 

The main reason this isn't supported is because there's no established pattern for doing this in Dash. 

`dcc.Upload` reads the file into memory on the client side and then exposes the data to callbacks that way. A conventional file upload via form submission will transmit the file to the server, but that requires writing an endpoint and handling things appropriately. Since this library is only front-end components it's not super clear how we can support it without causing confusion for people.

How would this feature ideally work in your opinion if it were implemented?

**Comment by slyin87** [comment]
@tcbegley thanks for replying. I want to upload huge files such as pptx or docx into a persistent volume and is kept in there for sometime. I tried using dcc.Upload but it has to translate into binary first. The dash-uploader is a component that directly stores those files into the server volume but the feature is limited and not flexible to edit.

**Comment by AnnMarieW** [comment]
Hi @slyin87 

This might be more of a general Dash question, and you could try searching the Dash forum for this topic.  Here's one post I found that might be helpful:  https://community.plotly.com/t/dcc-upload-to-handle-a-word-docx-file/72218

Here's more information about posting to the forum: https://community.plotly.com/t/how-to-get-your-questions-answered-on-the-plotly-forum/40551

**Comment by slyin87** [comment]
Hi @AnnMarieW yeah the thing is I don't want to read any doc. I just want to store it. Plus I want to avoid the html5 file api converting the file into bytes.

**Comment by tcbegley** [comment]
Have you considered writing a simple upload form outside of your Dash app that can handle the file uploads, and then having your Dash app itself just focus on processing / reading the data that has been uploaded?

Here's an example:

File structure:
```
.
├── app.py
└── templates
    └── upload.html
```

`app.py`

```python
from pathlib import Path

import dash_bootstrap_components as dbc
import flask
from dash import Dash, html
from werkzeug.utils import secure_filename

UPLOAD_FOLDER = Path(__file__).parent / "uploads"

server = flask.Flask(__name__)
app = Dash(external_stylesheets=[dbc.themes.BOOTSTRAP], server=server)

app.layout = html.Div(
    [
        dbc.NavbarSimple(
            [
                dbc.NavLink("Home", href="/", active=True),
                dbc.NavLink("Upload", href="/upload/", external_link=True),
            ],
            brand="Dashboard",
        ),
        dbc.Container(
            html.P("This is the Dash part of the app"),
            className="pt-3",
        ),
    ]
)


@server.route("/upload-file", methods=["POST"])
def handle_uploaded_file():
    if "file" in flask.request.files:
        file = flask.request.files["file"]
        filename = secure_filename(file.filename)
        file.save(UPLOAD_FOLDER / filename)
    return flask.redirect("/")


@server.route("/upload/")
def render_upload_page():
    return flask.render_template("upload.html")


if __name__ == "__main__":
    UPLOAD_FOLDER.mkdir(parents=True, exist_ok=True)
    app.run_server(debug=True)
```

`upload.html`

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous" />
    <title>Upload</title>
  </head>
  <body>
    <nav color="light" class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container">
        <span class="navbar-brand">Dashboard</span>
        <div class="ms-auto navbar-nav">
          <a href="/" class="nav-link">Home</a>
          <a href="/upload/" class="nav-link active">Upload</a>
        </div>
      </div>
    </nav>
    <div class="container pt-3">
      <form action="/upload-file" method="POST" enctype="multipart/form-data">
        <div class="mb-3">
          <label for="formFile" class="form-label">Upload a file to the server</label>
          <input class="form-control" type="file" name="file" id="formFile" />
        </div>
        <input type="submit" class="btn btn-primary" value="Upload" />
      </form>
    </div>
  </body>
</html>
```

**Comment by slyin87** [comment]
@tcbegley thanks for the suggestion. :) Will try it.
