### ISSUE TITLE
BUG: max doesn't work on nested progress bar

### ISSUE THREAD

**Issue by ezwc** [facultyai/dash-bootstrap-components#982]
- dash version: 2.13.0
- dash-bootstrap-components version: 1.5.0
- components affected by bug: dbc.Progress

### What is happening?

The width of the bar seems to remain at the default 100, showing a large light-brown "empty" area:
![image](https://github.com/facultyai/dash-bootstrap-components/assets/142219667/ac7d89c6-2363-4ea7-8745-72d17a33dd1e)

### What should be happening?

Bar should show only the 3 relevant colors, without the light brown area.

### Code
(values changed to constants)

    count_good = 20
    count_borderline = 10
    count_bad = 5
    count_total = count_good + count_borderline + count_bad
    progress = dbc.Progress([
        dbc.Progress(value=count_good, color='success',bar=True),
        dbc.Progress(value=count_borderline, color='warning', bar=True),
        dbc.Progress(value=count_bad, color='danger', bar=True),
    ], max=count_total, style={"width": "100%"})

**Comment by tcbegley** [comment]
Hi @ezwc 

A progress bar sets its width by comparing its value to its max. Currently the nested `Progress` components are not able to see the max from the parent `Progress` component which results in the widths being wrong. Clearly this would be the better user experience so I'll look into whether we can support that.

In the meantime, you can fix the above example by simply setting `max=count_total` on each of the nested bars.

**Comment by ezwc** [comment]
That worked, thank you!

**Comment by tcbegley** [comment]
I just merged a pull request that will pass the max from the parent `Progress` component to the children, so the workaround above will not be necessary as of the next release.
