### ISSUE TITLE
Allow icons and html in `dbc.AccordionItem()` title

### ISSUE THREAD

**Issue by GitHunter0** [facultyai/dash-bootstrap-components#985]
Hey folks,

`dbc.AccordionItem()` title only accepts a `string`. I'd like to use an `icon` instead of a `string`, is it possible?

Thank you

**Comment by tcbegley** [comment]
Hey,

Unfortunately not currently possible. I have an idea for how we could reimplement the component to support this that I want to try at the next opportunity.

In the meantime you could try [this workaround](https://github.com/facultyai/dash-bootstrap-components/issues/769#issuecomment-968249009)

**Comment by GitHunter0** [comment]
Thanks man, I appreciate the feedback.
